### ISSUE TITLE
Feature for zooming images?

### ISSUE THREAD

**Issue by gitrequests** [biati-digital/glightbox#10]
By dblclick or click some icon.

**Comment by mcstudios** [comment]
I want to keep the library small, i'm open to this idea if more people want this to be implemented but for now there are no plans to integrate this feature.

**Comment by krtek4** [comment]
Hey,

I would also love to have zooming abilities, otherwise, maybe a recommendation for a library that might work with glightbox ?

**Comment by alinnert** [comment]
I also vote for this feature. I think it's super useful on mobile devices. There, I'd prefer a pinch zoom gesture if that's possible. [PhotoSwipe](https://photoswipe.com/), as a reference, does this really well. (I was just looking für an alternative, that's easier to use.)

**Comment by biati-digital** [comment]
In the latest version 2.0.3 now you are able to zoom and drag images on mobile and desktop.
