### ISSUE TITLE
Image URLs with params are wrongly interpreted as videos

### ISSUE THREAD

**Issue by benface** [biati-digital/glightbox#100]
**Describe the bug**
Clicking on the following gLightbox link (notice the `?hash` param) will open the image in an iframe, which seems to be the behavior for videos, and will let you scroll in the iframe to see the whole image instead of scaling the image to fit the viewport:
```html
<a href="/image.png?hash=some-string" class="glightbox">
  <img src="/thumbnail.png">
</a>
```

**Are you able to reproduce the bug in the demo site**
No, but that's because there are no such URLs on it.

**Expected behavior**
The image is constrained to the viewport.

**Desktop:**
 - OS: macOS
 - Browser: Safari, Chrome, Firefox, and Edge
 - Version: 2.0.5

**Comment by biati-digital** [comment]
Please take a look at this [https://github.com/biati-digital/glightbox/issues/73](https://github.com/biati-digital/glightbox/issues/73) and also read the documentation if you have doubts
