### ISSUE TITLE
Unable to play mp4 video with non standard URL (it is just automatically downloaded)

### ISSUE THREAD

**Issue by fboumol** [biati-digital/glightbox#102]
First of all, let me thank you for this great piece of software. I am using the demo provided and it works wonderfully well.

I am having trouble (I have tried with mozilla-firefox and also with chromium) when I modify the very demo and I try to use:
```
<a href="http://disco.uv.es/cgi-bin/in-public?fileman:es:imgdump:pub:/cloud/accesibleweb//testglightbox.mp4:feboumo:" class="glightbox3">
    <img src="small.jpg" alt="image">
</a>
```
The problem is that the file is downloaded instead of being played.

My conjecture is that the trouble comes from the fact that this non standard 'http://disco.uv.es/cgi-bin/in-public?fileman:es:imgdump:pub:/cloud/accesibleweb//testglightbox.mp4:feboumo:' is not recognized as a mp4 video. Following this intuition and searching in the closed bugs I have tried to use without success the following version (which somehow tries to specify the video type):
```
<a href="http://disco.uv.es/cgi-bin/in-public?fileman:es:imgdump:pub:/cloud/accesibleweb//testglightbox.mp4:feboumo:" data-glightbox="type: video/mp4" class="glightbox3">
    <img src="small.jpg" alt="image">
</a>
```
Any suggestion to solve/avoid this problem? My interest is to able able to use glightbox even when the URL is such strange as the one given above.

**Comment by biati-digital** [comment]
Hi @fboumol glad you like GLightbox. For videos with that kind if url you just need to specify the type directly in your link adding data-type="video" please take a look at the docs if you need more help.

**Comment by fboumol** [comment]
I have read the documentation and I am still thinking that things are not OK in the particular case of the link I said before (i.e., 'http://disco.uv.es/cgi-bin/in-public?fileman:es:imgdump:pub:/cloud/accesibleweb//testglightbox.mp4:feboumo:' ).

I am now using the following code (from your suggestion):
```
<a href="http://disco.uv.es/cgi-bin/in-public?fileman:es:imgdump:pub:/cloud/accesibleweb//testglightbox.mp4:feboumo:" data-type="video" class="glightbox3">
    <img src="small.jpg" alt="image">
</a>
```
and I am having the very same feedback (i.e., the video is downloaded instead of playing it).

Could someone tell me if the previous code line is working (in the sense of playing instead of downloading) in your computer? Just to be sure that this is my problem instead of a "bug" in the software.

**Comment by biati-digital** [comment]
The problem is not with GLightbox, it can be the server configured to force the download of certain files, etc. even if you enter with the url of the video directly in the browser the video will be downloaded instead of being displayed normally in the browser.
