### ISSUE TITLE
Support for dragging to next and previous on the Desktop

### ISSUE THREAD

**Issue by kerns** [biati-digital/glightbox#104]
**Please describe the feature you want to be implemented.**
Mouse support for clicking/dragging an image left/right to initiate previous/next image calls.

**Explain why the feature is useful**
A lot of people coming from Photoswipe expect this behavior. It feels natural and is easy to implement. I think it could be helpful on hybrid devices, tablets and laptops with touch enabled displays.

**Have you seen it somewhere else?**
Photoswipe and other galleries.
http://photoswipe.com/

**Additional context**
A library like this could make it easier to implement.
https://draggabilly.desandro.com

**Comment by biati-digital** [comment]
Duplicate of #11
