### ISSUE TITLE
When opening a base64 image it keeps loading forever and I can't close glightbox.

### ISSUE THREAD

**Issue by robinparadise** [biati-digital/glightbox#107]
![WhatsApp Image 2020-05-04 at 9 50 50 AM](https://user-images.githubusercontent.com/2571925/80947240-fed08500-8def-11ea-8e8b-33f3fd3959d8.jpeg)
**Please describe the feature you want to be implemented.**
I think it is essential to open this type of images

**Comment by biati-digital** [comment]
Can you explain why do you think it's essential to support base64 images? I don't see any advantage of using base64 images in a Lightbox when it's primarily used to display large images and the base64 code can be quite large. Is it only to avoid a request to the server? if you have other use cases please mention them.

**Comment by biati-digital** [comment]
Closing as there was no response

**Comment by hafen** [comment]
This is being requested by others here: https://github.com/quarto-ext/lightbox/issues/1 which uses this library.

A common use case for this is when people want a self-contained single html file to share that includes all of the images base64 encoded. Of course it's not ideal to have a lot of images built directly into the page but there are situations where it is nice to have. Here the use of Lightbox isn't so much about large images as much as it is about having a simple document where images can be magnified with Lightbox when needed.

I'm not sure if that's enough of a reason to revisit this but pointing it out in case it is and is something that could be accommodated without too much effort.
