### ISSUE TITLE
Resolve source type when using setElements

### ISSUE THREAD

**Issue by martinbroos** [biati-digital/glightbox#109]
**Please describe the feature you want to be implemented.**
When using an href link to vimeo or youtube the source type does not need to be provided the library will resolve this itself.
When using setElements to create a dynamic gallery you must provide a type and source yourself. So now I need to duplicate some of the regexes to resolve this source type based on the video url. Is i possible that GLightbox also extends this information when setElements is used by checking the given urls ?

**Explain why the feature is useful**
It will prevent code duplication and makes using setElements easier.

```
        {
            'href': 'https://www.youtube.com/watch?v=Ga6RYejo6Hk',
            'source': 'youtube', // make plugin resolve this
            'type': 'video', // this would also be nice if plugin could resolve this based on url.
        }
```

**Comment by martinbroos** [comment]
Ok weird now that i'm testing this it does seem to work without defining a source attribute. Both vimeo and youtube play as expected. Can you confirm this? 
If so this would be great and this was a non issue :)

**Comment by biati-digital** [comment]
The source attribute is **not** required, the library check the url before adding the video. 

I'm working on an update so the **type** attribute can also be ignored and let the library do the same work it does for regular links.

**Comment by biati-digital** [comment]
Closing this, please check the latest update 2.0.6
