### ISSUE TITLE
setElements(…) + reload(…)/open()/openAt(…)/goToSlide(…) won't update a lightbox already showing

### ISSUE THREAD

**Issue by mnoorenberghe** [biati-digital/glightbox#113]
Btw. thank you very much for this project. It seems to be one of the best vanilla JS lightbox libraries from my research.

**Describe the bug**
I would like to be able to be able to replace lightbox contents while one is already showing (e.g. using up/down keyboard shortcuts) without closing and re-opening (which is jarring).

The names/descriptions of `setElements` and `reload` make me think this is supposed to work but it doesn't. They have no visible effect on an already showing lightbox.

The root issue seems to be that `build()` returns immediately if `this.built` is `true` and nothing accounts for the `elements` changing. I have a WIP patch to fix this in only a few lines for my use with the options I use but I wanted to check if I'm doing something wrong. The readme doesn't suggest `setElements` is only for use while closed.

**Are you able to reproduce the bug in the demo site**
N/A. I don't think any of the demo galleries attempt to do this.

**To Reproduce**
1. Open a lightbox with a set of images A
2. Elements/images are updated e.g. from a keyboard shortcut or an AJAX request completing
3. Sites uses `reload()`/`open()`/`openAt(…)`/`goToSlide(…)` etc. to change the current slide

**Expected behavior**
The new slide content should be rendered.

**Post the code you are using**
I tried many different approaches and they all needed changes that didn't use the public API:
Setup:
```js
var lb = new GLightbox({});
lb.setElements([
  { href: "1.jpg", title: "1" },
  { href: "2.jpg", title: "2" },
]); 
```
A:
```js
lb.reload();
lb.showSlide(0);
```

B:
```js
lb.reload();
lb.openAt(0);
```

C:
```js
lb.reload();
lb.goToSlide(0);
```

**Screenshots**
N/A. The lightbox stays stuck on the previous view/slide and nothing changes even though the `elements` are replaced and `reload` is called.

**Desktop:**
- All

**Smartphone:**
 - All

Thank you.

**Comment by biati-digital** [comment]
Hi @mnoorenberghe That's because setElements was meant to work only for initialization so you could set all items (for example) after an Ajax call or after a custom script that generates the list, etc. It wasn't meant to work with an active/open instance and because of that any method you call after that won't work.

Can you give me an example of how it could be used with an active Lightbox instance and why it could be useful? (use case example)

**Comment by mnoorenberghe** [comment]
I tried to mention my use case buried in my comment: I want to use up and down arrow keys to jump between different sets of images. In my case I have a grid of images where each row has a old, new, and comparison image which I want to be able to navigate with left/right arrows (already working). To make it faster to review I would like up/down arrows to move to respective adjacent rows. Example: https://mnoorenberghe.github.io/mozscreenshots/web/?oldProject=mozilla-central&oldRev=34d71b4a00863e7615463592662dfe362c4a993e&newProject=mozilla-central&newRev=786823305560b03316cb758207f76838388603af

Click on one of the links in the table and use up/down keys. It’s kinda working in a Jaclyn way with a close and quick re-open but I want to reduce the flicker as much as possible.

**Comment by mnoorenberghe** [comment]
Btw. here are some of the workarounds I had to put in to get it to kinda work now: 
* https://github.com/mnoorenberghe/mozscreenshots/blob/7b4875722f09b1080a221289ef6599f78ef97274/web/lightbox.js#L192-L197
  * Close without an animation then immediately re-open.
* https://github.com/mnoorenberghe/mozscreenshots/blob/7b4875722f09b1080a221289ef6599f78ef97274/web/lightbox.js#L305-L310
  * Since I have to call .close() a few places in order to quickly re-open (since I can't just updating the elements while it's open), I need to handle `onClose` differently in these two cases. I can submit a separate PR for that: an argument to `onClose` callbacks to know whether the close was from a user action (e.g. ESC or clicking the close button) vs. the `.close()` API.

**Comment by biati-digital** [comment]
Hi @mnoorenberghe setElements will require some changes to work when the Lightbox is open, I'll  take a look as soon as I've some time to see if we can adjust this method.

By any chance did you try the insertSlide method?

**Comment by mnoorenberghe** [comment]
> Hi @mnoorenberghe setElements will require some changes to work when the Lightbox is open, I'll take a look as soon as I've some time to see if we can adjust this method.

I'm willing to write the patches if they are something you would consider.

> By any chance did you try the insertSlide method?

No, because it didn't really align with what I need. I need to be able to also remove slides.

**Comment by biati-digital** [comment]
Awesome, all pull requests are welcome if you have the time. 👍

**Comment by dminkovsky** [comment]
> Can you give me an example of how it could be used with an active Lightbox instance and why it could be useful? (use case example)

I am trying to do this to. In my case, it is because I have hundreds of images, and will soon have thousands. I don't want thousands of dom elements to be created/appended when I open this plugin (https://github.com/biati-digital/glightbox/blob/325f6d7aa094fe67d6d7cb7d2a92595c043b42dc/src/js/glightbox.js#L2047). So, in my case, I would like to lazily control the elements as the user navigates.

**Comment by biati-digital** [comment]
Hi, i had a few hours today so i implemented this, **setElements** now replaces all the slides even when the lightbox is open, **insertSlide** can now also be used even with the lightbox open and there's a new method **removeSlide**

You can find more information in the Readme.

**Comment by dminkovsky** [comment]
Super cool, thank you. Look forward to trying this out.
