### ISSUE TITLE
2.0.6 breaking changes

### ISSUE THREAD

**Issue by treeshuh** [biati-digital/glightbox#115]
Thank you for continuing development on this project, we appreciate the effort for ongoing improvement. 

### Description
2.0.6 includes many nice improvements, but by [semver](https://docs.npmjs.com/about-semantic-versioning) should probably have been a major version since it includes breaking changes.

#### Breaking Change 1:  this.settings.selector no longer optional
In the docs, passing `selector` is optional, since you can instead opt to pass in elements:
> Instead of passing a selector you can pass all the items that you want in the gallery.

However, 2.0.6 adds this line: 

https://github.com/biati-digital/glightbox/blob/325f6d7aa094fe67d6d7cb7d2a92595c043b42dc/src/js/glightbox.js#L1931

which errors out if `selector` is not passed in, since you are calling `substring` on `undefined`

##### Suggestion:
add a null check before calling substring

#### Breaking Change 2: this.settings.selector no longer compatible with old selectors
In 2.0.5, `selector` was the class name, which glightbox then appended to a `.` to make the query selector. However, in 2.0.6, glightbox expects the whole query selector. This means that code that worked on 2.0.5 will not work on 2.0.6.

Example of breaking:
``` javascript
const lightbox = Glightbox({
  selector: 'myClass'
});
```
In 2.0.5, this would bind to all elements of `document.querySelectorAll('.myClass')`, which is all elements with class `myClass`.
In 2.0.6, this would bind to all elements of `document.querySelectorAll('myClass')`, which is nothing or the wrong thing, since a string without a `.` is going to select <myClass> tags.

So without a code change, code on 2.0.5 that had explicit class as selector will no longer work.

#### Breaking Change 3: New inlining of width/height changes default look
In 2.0.6 there are new lines of code that inline `width` and `maxWidth` to elements:
https://github.com/biati-digital/glightbox/blob/325f6d7aa094fe67d6d7cb7d2a92595c043b42dc/src/js/glightbox.js#L1031

https://github.com/biati-digital/glightbox/blob/325f6d7aa094fe67d6d7cb7d2a92595c043b42dc/src/js/glightbox.js#L1042

Note that even if we don't pass in a width, there is a default width that these elements will have inlined:
https://github.com/biati-digital/glightbox/blob/cc15d51f3140634e4661e4dc049018a2e1b858ca/src/js/glightbox.js#L28

The problem with these lines is that it changes the default look of the lightbox. For example, in our project, we wanted the inline content to be full width, which used to be the default look as defined in your CSS:
https://github.com/biati-digital/glightbox/blob/325f6d7aa094fe67d6d7cb7d2a92595c043b42dc/dist/css/glightbox.css#L244

However, with the new inlined `width` and `maxWidth`, the actual size of the inline content is smaller (for screen sizes > 900px) if we don't make any code changes. This makes our inlined content look squished since we use `%` to determine the width relative to the parent. There are workarounds to revert back to 2.0.5 looks, but these require code changes in 2.0.6.

**Comment by biati-digital** [comment]
Hi @treeshuh you are probably right about the version 

**Breaking Change 1: this.settings.selector no longer optional**
This is an error, the selector should be optional

**Breaking Change 3: New inlining of width/height changes default look**
Is there any way I could see your project? Is there a problem if you pass `width: 100% or 100vw` when you initialize GLightbox?

There are still some errors that I need to work on, I just had a few hours free and was able to work on this update. If you have some free time pull requests are welcome.

**Comment by biati-digital** [comment]
btw, thank you for your kind words, this type of comments makes my day 😄

**Comment by Ariane-B** [comment]
I also really appreciate the update. Thank you for taking the time. :)

The new `openAt()` method is exactly what I wanted.

**Comment by biati-digital** [comment]
Hi @Ariane-B thank you, I'm really glad the update worked for you 😄

**Comment by TidyLuke** [comment]
+1 for open at! Thank you for this.

**Comment by biati-digital** [comment]
Closing this, we are now at 3.0.0

**Comment by jsunsawyer** [comment]
Just ran into this on a fairly recent project build. Didn't even realize that production was broken (and probably has been for a while). Our deploy process runs yarn install and had upgraded the version during the deployment of some other minor change since we launched this particular site.

Anyone who is on version 2 may be experiencing the same issue, and have broken galleries from breaking changes without even noticing it. @biati-digital As this change is fairly recent, it might be a good idea to revert breaking changes in version 2 so others don't experience this same issue? Then again, you already broke it and some may have fixed it for your minor version bump. Not sure what's right here.
