### ISSUE TITLE
The 'see more' link in the description throws an JS error when clicked

### ISSUE THREAD

**Issue by zothynine** [biati-digital/glightbox#116]
First off, thank you for updating this library!
In the following function I get an error when the "See more" link is clicked in a slide description.
This only happens, when the description is not viewed as overlay (wider viewports).

```
function getClosest(elem, selector) {
  while (elem !== document.body) {
    elem = elem.parentElement;
    var matches = typeof elem.matches == 'function' ? elem.matches(selector) : elem.msMatchesSelector(selector);
    if (matches) return elem;
  }
}
```
`Uncaught TypeError: Cannot read property 'matches' of null`

The bug can be reproduced on the GLightbox Demosite https://biati-digital.github.io/glightbox/

### Steps to reproduce the behavior:
1. Go to https://biati-digital.github.io/glightbox/.
2. Make sure the description is not viewed as overlay.
3. Click on an image with a description, for instance the cat picture.
4. Click the read more link.

**Comment by biati-digital** [comment]
Hi, this should be fixed in the latest version 3.0.2.
