### ISSUE TITLE
"navigator is not defined" on Gatsby build

### ISSUE THREAD

**Issue by brisa-pedronetto** [biati-digital/glightbox#117]
**Describe the bug**
I love this library and I really want to use it in my upcoming project so I'll ask for some help here. My website is a Gatsby project that uses Glightbox (imported with a simple `import GLightbox from "glightbox"` in a component).

Everything goes fine on development until I try to build, at which point it gives me the error: `  WebpackError: ReferenceError: navigator is not defined`

I'm guessing it's some issue with Server Side Rendering Gatsby performs, when `navigator` is not available. As a matter of fact I think the issue happens on line 10 of the file `src/glightbox.js`:

```
const isMobile = navigator.userAgent.match(/(iPad)|(iPhone)|(iPod)|(Android)|(PlayBook)|(BB10)|(BlackBerry)|(Opera Mini)|(IEMobile)|(webOS)|(MeeGo)/i);
```

Does anyone have an idea on how to fix this so the library can also be used with SSR? Or maybe this issue is irreconcilable with the library's philosophy?

**Are you able to reproduce the bug in the demo site**
Yes

**To Reproduce**
1. Start Gastby project
2. Add Glightbox in a componend using `import GLightbox from "glightbox"`
3. Attempt to build project

**Expected behavior**
A clean build.

**Post the code you are using**
Mentioned in the description.

**Comment by biati-digital** [comment]
Hi @brisa-pedronetto I'm glad you like this library. 

That part of the code is really old, I think there are better ways to detect mobile devices. If you want and have time you are welcome to fork and find an alternative for that line, if not I'll take a look as soon as I have some free time.

**Comment by brisa-pedronetto** [comment]
Thanks for the reply! Yes, I'll come back here if I happen to find a good solution for this.

**Comment by biati-digital** [comment]
There's a new update, 3.0.0, could you please try it and let me know if you still have the same error?

**Comment by brisa-pedronetto** [comment]
Hey there, thanks for looking into this! At the moment I'm quite busy with other tasks but I'll come back when I mange to test. Otherwise I hope it will be useful for future users too! :)

**Comment by biati-digital** [comment]
i'm closing this as it has been inactive for a couple of months, feel free to open a new issue if you still have problems with this.
