### ISSUE TITLE
Calling `destroy()` throws an error when lightbox modal is not open

### ISSUE THREAD

**Issue by CommissarXiii** [biati-digital/glightbox#120]
**Describe the bug**
Calling `destroy()` on the lightbox instance when not 'open' throws an error.

![image](https://user-images.githubusercontent.com/165624/83289311-7bb20d00-a1aa-11ea-807d-c3c4db55f1f0.png)

The error appears to be thrown when trying to add a class to a non-existent modal element:

https://github.com/biati-digital/glightbox/blob/master/src/js/glightbox.js#L2179

**Are you able to reproduce the bug in the demo site**
Yes

**To Reproduce**
Steps to reproduce the behavior on the demo site:
1. Open the console in DevTools
2. run `window.lightbox.destroy()`

**Expected behavior**
The lightbox instance should be destroyed without error regardless of whether or not the lightbox is 'open'

**Post the code you are using**
```
<html>
  <head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/glightbox/dist/css/glightbox.min.css">
    <script src="https://cdn.jsdelivr.net/gh/mcstudios/glightbox/dist/js/glightbox.min.js"></script>
  </head>
  <body>
    <!-- Gallery -->
    <a href="http://placekitten.com/600/600" class="glightbox" data-gallery="gallery1">
        <img src="http://placekitten.com/200/200" alt="image">
    </a>
    <a href="http://placekitten.com/600/600" class="glightbox" data-gallery="gallery1">
        <img src="http://placekitten.com/200/200" alt="image">
    </a>
    <!-- Initialze after HTML is rendered -->
    <script type="text/javascript">
      const options = {}
      const lightbox = GLightbox(options);

      lightbox.destroy()
    </script> 
  </body>
</html>
```

**Comment by biati-digital** [comment]
Hi, the error has been fixed in the latest version 3.0.0
