### ISSUE TITLE
Videos are not playing in Instagram's in-app browser

### ISSUE THREAD

**Issue by suryavardhan** [biati-digital/glightbox#121]
**Describe the bug**
Video is not playing on Instagram's in-app browser

**Are you able to reproduce the bug in the demo site**
Yes

**To Reproduce**
1. Go to instagram profile (Shall use my profile @pixelglimpse)
2. Click on the link in bio (Glightbox demo link)
3. Scroll down to Videos section

**Expected behavior**
This is only happening in in-app browser

**Screenshots**

**Desktop:**

**Smartphone:**
 - Device: POCO X2
 - OS: Android 9
 - Browser Instagram APP - In-App browser
 - Version

**Comment by biati-digital** [comment]
I don't think there's a way to debug this, if anyone has an idea please let me know.
