### ISSUE TITLE
When set version to image, opened like video

### ISSUE THREAD

**Issue by fatihmert** [biati-digital/glightbox#122]
**Describe the bug**
When set version to image (or any http get query), opened like video. Example url;
[https://i.picsum.photos/id/237/200/300.jpg?v=5](https://i.picsum.photos/id/237/200/300.jpg?v=5)

Not only version you can set any HTTP GET query string. If this set any that, you will see image opened in iframe like video.

**Are you able to reproduce the bug in the demo site**
No.

**To Reproduce**
1. Set your a and img tag image url via http get query
2. Click your image for test

**Expected behavior**
Without opened iframe.

**Comment by biati-digital** [comment]
Please before opening an issue take a look at the description and closed issues.

You can specify the url **type** so in those cases GLightbox can know that the url is an image.
