### ISSUE TITLE
Make ZoomImages optional

### ISSUE THREAD

**Issue by Hirbod** [biati-digital/glightbox#124]
I would like to be able to add a a data-zoomable="false" to any image and a general "zoomable" when instantiating to disable it globally. Currently, the zoom feature is baked in.

**Comment by biati-digital** [comment]
Hi @Hirbod, when asking a feature request please use the **Feature request** template, this feature was asked before, when I asked a reason for this the user replied 

> it's quite a difficult answer why we would need this...

I'm closing this for now, feel free to open a new issue following the correct template and a valid explanation of how this will help a lot of users and not only a few.
