### ISSUE TITLE
Works with AJAX but not Fetch API

### ISSUE THREAD

**Issue by crunchpaste** [biati-digital/glightbox#125]
First of all excuse my incompetence, as I'm rather new to web development.

I'm using a json file and template literal to fill a gallery grid. The json file looks like this:

`
[
{
"english":"Some Name, Rotation",
"img":"mGeorgiev",
"title":"Cyrillic Name, ротация"
},
{
"english":"Other Name, Reflection Symmetry",
"img":"kPavlova",
"title":"Other Cyrillic Name, огледална симетрия"
}
]
`

When using this AJAX (jQuery) request:

`      var json = (function () {
      var json = null;
      $.ajax({
          'async': false,
          'global': false,
          'url': "tree.json",
          'dataType': "json",
          'success': function (data) {
              json = data;
          }
      });
      return json;
      })();`

with this template literal:

`
        <a href="media/tree/${gall.img}H.jpg" class="glightbox" title="${gall.title}">
          <picture>
            <source media="(max-width: 425px)" srcset="media/tree/${gall.img}M.webp" type="image/webp">
            <source media="(max-width: 425px)" srcset="media/tree/${gall.img}M.jpg" type="image/jpeg">
            <img height="300" width="300" loading="lazy" class="painting" src="media/tree/${gall.img}L.jpg" alt="image">
          </picture>
        </a>`
`

It seems to work and the gallery displays properly. Each thumbnail opens the proper full resolution image.

Then again when using Fetch to fill the template the thumbnails link to the actual full resolution image, not the lightbox. Strangely enough, if I put some static HTML image with `class="glightbox"` it works fine. Moreover I can scroll through all of the rest of the images as if everything is normal. I just can't make the thumbnails to link to the lightbox.

`
function getWork(json){
  fetch(json)
  .then((res) => res.json())
  .then((data) => {
    var output = '';
    let width = window.innerWidth
    || document.documentElement.clientWidth
    || document.body.clientWidth;
    data.forEach(function(artwork)
`

I'm sure this has something to do with the timing of the fetch. I've tried reloading the gallery using `lightbox.reload()` as stated in the README.

I'll update with a live example as soon as possible.

**Comment by biati-digital** [comment]
Hi @crunchpaste i think your issue will be more appropiate for stackoverflow, it's recommended that you only posts issues with the library itself or feature requests as i do not have a lot of time to invest on this library and the time i have i use it to fix bugs or implement new things, you'll have more luck on stackoverflow.
