### ISSUE TITLE
Disable Plyr completely and just show the original YouTube embed iframe

### ISSUE THREAD

**Issue by henk23** [biati-digital/glightbox#126]
**Please describe the feature you want to be implemented.**
Make it possible to set `plyr: false` to disable Plyr completely and just show the original YouTube embed iframe without any "enhancing" control overlays.

**Explain why the feature is useful**
The original youtube embed iframe already has all the controls and is familiar to the user. There is no need for any "enhancement".

**Comment by henk23** [comment]
Nevermind. Just found out how to do it: `data-glightbox="type: external;"` :)

**Comment by biati-digital** [comment]
Hi. A setting to disable Plyr will never be added for several reasons:

1.- Plyr offers a unified interface for all types of videos, YouTube, Vimeo, self hosted video and even audio.

2.- You don't have to be familiar with a player to understand it, I mean everyone knows how to use a video player, play, pause, change audio, etc.

3.- Plyr offers an extensive API to control the players so it's easier to maintain.

4.- When Glightbox was created it used the YouTube player, Vimeo player an a custom player, I had to maintain 3 different API's to control the players. That's a lot of work and I'm not going back to that.

You can set the type as **external** to display it as an iframe but you will not be able to autoplay the video and it could have more disadvantages that I'm not gonna take a look as the iframe was not intended to display videos.

I'm closing this for now, feel free to open new issues if you find a bug.

**Comment by mrleblanc101** [comment]
I've struggled to find this, the `data-type="external"` is not documented anywhere
