### ISSUE TITLE
How to integrate in angular projects?

### ISSUE THREAD

**Issue by biswajitpaul01** [biati-digital/glightbox#128]
Hi,

This plugin has tons of options that I like most. Can anyone suggest to me how to integrate with Angular 2 with an HTTP call? I have tried adding styles & scripts in angular.json file with the mentioned HTML structure provided in the example. But the plugin does not open any lightbox. The page navigates to the image URL.

Thanks in advance.

**Comment by biati-digital** [comment]
Hi, the issues section here is intended for bugs with the library itself or feature requests, If you have doubts about implementation please post your issue in stackoverflow as i do not use Angular and the probability of someone else answering you is close to 0
