### ISSUE TITLE
CSS properties bugs in 3.0.0

### ISSUE THREAD

**Issue by RawMajkel** [biati-digital/glightbox#129]
**Describe the bug**
1. CSS property "overflow-scrolling" doesn't exist.
2. CSS Unknown pseudo-element or pseudo-class ::last-child.

**Are you able to reproduce the bug in the demo site**
No.

**Expected behavior**
1. Remove the "overflow-scrolling" property and keep "-webkit-overflow-scrolling"
2. It should be ":last-child", 

**Post the code you are using**
The code is in dist css files.

**Screenshots**
https://screen.proudmedia.eu/v2new/msedge_2020-06-22_18-03-47.jpg

**Comment by biati-digital** [comment]
Thank you for letting me know. Fixed in the latest version 3.0.1.
