### ISSUE TITLE
Slide descriptions only scrollable as overlays

### ISSUE THREAD

**Issue by zothynine** [biati-digital/glightbox#130]
Descriptions in slides are only scrollable when they are viewed as overlays. On right, left, bottom positions they are not scrollable when expanded with the "See more" link.

**Are you able to reproduce the bug in the demo site**
Yes|No.

**To Reproduce**
Go to https://biati-digital.github.io/glightbox/.
Make sure the description is not viewed as overlay.
Click on an image with a description, for instance the cat picture.
Click the read more link.

**Expected behavior**
Long Text shoud be scrollable.

**Screenshots**
![Chrome macOS description](https://user-images.githubusercontent.com/6057489/85708696-bc873e00-b6e4-11ea-8e79-86c5416725ee.png)

**Desktop:**
 - OS: any – tested on macOS 10.13
 - Tested on Chrome
 - Version 83.0.4103.116

**Smartphone:**
 - Device:  Google Pixel 4
 - OS: Anrdoid
 - Chrome
 - Version 81.0.4044.1.138

**Comment by biati-digital** [comment]
Thank you for the pull request, closing this now 😄
