### ISSUE TITLE
Incorrect descPosition data attribute in example

### ISSUE THREAD

**Issue by juddlyon** [biati-digital/glightbox#131]
In [README.md under **Slide Options**](https://github.com/biati-digital/glightbox#slide-options) the configuration via data attributes example is incorrect.

`data-descPosition` should be `data-desc-position` since data attributes are required to be lowercase. JS will map it to _descPosition_ automatically. 

_Side note: "desciption here" is missing an R._

Fixed version:
```
<!-- Multiple data attributes / You can use the options as separated data attributes -->
<a href="large.jpg" data-title="My title" data-description="description here" data-desc-position="right" data-type="image" data-effect="fade" data-width="900px" data-height="auto"></a>
```

By the way, Glightbox is pretty awesome!

**Comment by biati-digital** [comment]
Hi @juddlyon, thank you, the examples have been updated.

I'm glad you like GLightbox.
