### ISSUE TITLE
Responsive video

### ISSUE THREAD

**Issue by nickdekruijk** [biati-digital/glightbox#14]
I would like videos to be able to scale with the window size. Respecting aspect ratio.
By default it's set to 900 x 506 but if your window is smaller then that it gets awkward.
When it doesn't fit width then the video gets smaller but with a black background. When it doesn't fit height the video gets cropped at the bottom.

Besides that, I think 960 x 540 is a better default video size as 506 is actually a rounded number so not perfect 16:9 ratio. Although personally I set is to 1280 x 720 anyway.

**Comment by mcstudios** [comment]
Does this happen with a specific browser? i'm checking the videos but they are resized correctly with the browser window (or at least i'm not able to see anything awkward), Do you have a working example? 

About the default video size i think you are right, i'm going to check it.

**Comment by nickdekruijk** [comment]
Any browser on my MacBook. (Safari, FF, Chrome)
Samples on http://glightbox.mcstudios.com.mx have te issues too.
<img width="1094" alt="screen shot 2018-06-24 at 11 50 57" src="https://user-images.githubusercontent.com/607302/41817932-f49510b4-77a4-11e8-94cb-210a4aabcb8f.png">
<img width="1244" alt="screen shot 2018-06-24 at 11 50 42" src="https://user-images.githubusercontent.com/607302/41817933-f4ac7510-77a4-11e8-95ee-db761815b160.png">

**Comment by biati-digital** [comment]
Hi, please download the latest version, now videos are resized correctly when the screen height is lower than the video height.
