### ISSUE TITLE
Option to disable preloading and/or gallery

### ISSUE THREAD

**Issue by haengle** [biati-digital/glightbox#140]
I am implementing glightbox on a site where a list of 7 links on a page will open a unique iframe (from pages on the same domain) in the lightbox. When 1 link is clicked, glightbox is creating slide elements for all 7 "slides" and preloading 2 of the iframes in addition to the selected one, which is causing issues as the browser is loading the same site 3 times. 

It would be great if there was an option to disable preloading in general or to disable the gallery function for external/iframe targets.

Thank you

**Comment by biati-digital** [comment]
I think an option to disable preloading could be useful, I'll add it in the next update.

**Comment by biati-digital** [comment]
The new option to disable preloading has been added in the latest version 3.0.2, please check the README for more information.
