### ISSUE TITLE
Issues building Glightbox slides: `can't access property "create", t.instance is undefined`

### ISSUE THREAD

**Issue by fuego161** [biati-digital/glightbox#142]
**Describe the bug**
I can't seem to get any GLightbox instance to build correctly, every time I try I'm met with the error `Uncaught TypeError: can't access property "create", t.instance is undefined`. I'm trying to create the GLightbox instance by passing the elements array.

**Are you able to reproduce the bug in the demo site**
Please see [this JSFiddle](https://jsfiddle.net/3xzjpL9d/). This JSFiddle simply takes your example code and tries to initiate, it fails.

**To Reproduce**

Just run the JSFiddle, you'll see it shows an error in the output window. Inspect the console to see the error I mention above.

**Expected behavior**
I've set up GLightbox instances like this in the past, exactly with this method, and it's worked on previous versions.

**Post the code you are using**
The JSFiddle is using your example, here is the code I am trying to use:

```javascript
import GLightbox from 'glightbox';

const videoTriggers = document.querySelectorAll('.video-trigger');

if (videoTriggers.length) {
  const videoLightbox = GLightbox({
    elements: [
      {
        href: 'path-to-local-video',
        type: 'video',
        source: 'local',
        width: 900,
      },
    ],
  });

  for (const trigger of Object.values(videoTriggers)) {
    trigger.addEventListener('click', (e) => {
      e.preventDefault();
      videoLightbox.open();
    });
  }
}
```

**Comment by biati-digital** [comment]
I just published an update that should fix this error, please try it and let me know if it's working for you.

**Comment by biati-digital** [comment]
I just published an update that should fix this error, please try it and let me know if it's working for you.

**Comment by fuego161** [comment]
This works. Thanks for the quick fix!
