### ISSUE TITLE
Ability to set data attributes for prev/next/close buttons.

### ISSUE THREAD

**Issue by smarinade** [biati-digital/glightbox#144]

**Comment by biati-digital** [comment]
Hi @smarinade, this will probably not be implemented but you can easily add them, there's a undocumented setting called "lightboxHtml" it allows you to overwrite the entire html code of the lightbox [View the code here](https://github.com/biati-digital/glightbox/blob/8fab388270406a2d3dadca28f1add38b0a7d0ccc/src/js/glightbox.js#L111)

So you can do something like this:

```javascript
const lightboxHtml = `<div id="glightbox-body" class="glightbox-container">
    <div class="gloader visible"></div>
    <div class="goverlay"></div>
    <div class="gcontainer">
    <div id="glightbox-slider" class="gslider"></div>
    <button class="gnext gbtn" tabindex="0" aria-label="Next" data-customattribute="example">{nextSVG}</button>
    <button class="gprev gbtn" tabindex="1" aria-label="Previous">{prevSVG}</button>
    <button class="gclose gbtn" tabindex="2" aria-label="Close">{closeSVG}</button>
</div>
</div>`;

const glightbox = GLightbox({
  lightboxHtml: customHTML,
});
```

The settings "lightboxHtml" and "slideHtml" were created to easily adjust the interface and create templates but i need to find some time to add them to the docs with examples and probably rename them as Html looks weird.

**Comment by smarinade** [comment]
Thx @biati-digital. Ill check it out .

**Comment by biati-digital** [comment]
The README has been updated with information about this.

**Comment by quarkcore** [comment]
```
	<script src="https://cdn.jsdelivr.net/gh/mcstudios/glightbox/dist/js/glightbox.js"></script>
	<script type="text/javascript">
		const customSlideHTML = '<div class="gslide">[...]</div>';

		const lightbox = GLightbox({
			touchNavigation: true,
			draggable: false,
			slideHtml: customSlideHTML,
			selector: '.bellvue-lightbox'
		});
	</script>
```

this doesn't seem to work.. :(

**Comment by quarkcore** [comment]
```
	<script src="https://cdn.jsdelivr.net/gh/mcstudios/glightbox/dist/js/glightbox.js"></script>
	<script type="text/javascript">
		const customSlideHTML = '<div class="gslide"></div>';

		const lightbox = GLightbox({
			touchNavigation: true,
			draggable: false,
			slideHtml: customSlideHTML,
			selector: '.my-lightbox'
		});
	</script>
```

This doesnt seem to work. The instance I grabbed from the debugger still got the default html string.. :(

**Comment by biati-digital** [comment]
I need to update the docs, you need to use **slideHTML** not _slideHtml_ sorry for that.
