### ISSUE TITLE
Possible to play HTML5 Audio?

### ISSUE THREAD

**Issue by roypardi** [biati-digital/glightbox#145]
I've searched through the issues (and the web) and I don't see anything about `glightbox` being able to play audio. Would it be possible to add this (or give me some tips on how I can implement this myself). 

I see that `Plyr` is able to handle audio so maybe this wouldn't be too difficult?

I've tried a few things: specifying "audio" as type in my `elements` declaration (below), along with trying "video" – but neither worked. I guess I can load an iframe and handle it there – or maybe use the `content` tag. I've taken a first look at the `glightbox` code but before I start hacking, I thought I would ask here.

Any guidance would be very appreciated!

```
    'href': upath.joinSafe(projectPath, "assets", "audio", "girl.mp3"),
    'type': 'audio'
```

**Comment by biati-digital** [comment]
hi, glightbox does not support audio for now, setting the type to audio or using an iframe won't work, this is something that i plan to implement in the future but currently i'm really busy, i can not provide help with this but you are welcome to checkout the code in core/slide-parser.js, core/slide.js  and slides/video.js as it's really similar.

**Comment by roypardi** [comment]
Hi – thanks for the quick reply! 
I took a look at those files you mentioned and can see how to go about it.
