### ISSUE TITLE
unable to implement youtube default styles

### ISSUE THREAD

**Issue by LoisJo** [biati-digital/glightbox#149]
Thanks for creating such a plugin! just one question . Is it possible to keep the default CSS styles of you tube videos in the lightbox? Currently it has the styles of plyr. Need help on this.

**Comment by biati-digital** [comment]
Not possible, and everything related to the player should be posted in the Plyr repository but i really doubt this is something they will consider.

**Comment by LoisJo** [comment]
got it.. 
Thank u
