### ISSUE TITLE
IE11 does not support ".includes()"

### ISSUE THREAD

**Issue by haengle** [biati-digital/glightbox#151]
When loading iframe popups in IE 11, the lightbox does not work because of a JS error around the use of ".includes()"

On line 1901, "if (url.includes("goajax=true")" is the issue - 
In my project, I changed that line to use indexOf (which is what the string search for the hash is using):

`if (url.indexOf("goajax=true") > -1)`

and the popups function correctly in IE 11. I don't have any popups using Ajax so I don't know if that change will affect any of the Ajax functions.

**Comment by biati-digital** [comment]
Hi @haengle thank's for letting me know, i'll fix it in the next update.

**Comment by biati-digital** [comment]
Fixed in the latest version 3.0.5
