### ISSUE TITLE
How to load only the object I click on

### ISSUE THREAD

**Issue by jarisgv** [biati-digital/glightbox#152]
On a page I have dozens of objects (gallery, iframes and links) to open via GlightBox, but when I click on one of the objects the plugin loads all the links so that the only object I want to see is shown. This can take a long time and the user's experience is compromised, causing them to even give up browsing.
How can I change it?

**Comment by biati-digital** [comment]
Not sure what do you mean, GLightbox only loads the clicked element and preloads the prev and next item, there's also a setting to configure that, please take a look at the readme, post an example and please follow the issue template.
