### ISSUE TITLE
Implement consistent CSS namespace for purgecss

### ISSUE THREAD

**Issue by alancwoo** [biati-digital/glightbox#153]
Due to the naming convention in the stylesheet, there are so many different prefixes one has to try to manually whitelist.

**Please describe the feature you want to be implemented.**
Ideally the stylesheet/convention would prefix evertying with `glightbox-` so that purgecss whitelist would be a one-liner.

**Explain why the feature is useful**
For any project using purgecss or similar

**Have you seen it somewhere else?**
For example, `Tippy.js` uses a `namespace-prefix` to produce a consistent class name: https://github.com/atomiks/tippyjs/blob/master/src/scss/index.scss

**Additional context**
Purgecss whitelisting: https://purgecss.com/whitelisting.html

**Comment by biati-digital** [comment]
Hi @alancwoo i'm not even sure this could be a feature as the only purpose of this is to whitelist the classes in purgecss, this isn't something i will consider as i've limited time, you are welcome to send a Pull Request if you want.

**Comment by nam-co** [comment]
@alancwoo Hi, did you ever find a white/safe list for making it work?

**Comment by gingerchew** [comment]
I can't speak for them figuring out a whitelist, but if i'm reading the [purgecss options](https://purgecss.com/configuration.html#options) right, you can pass the path to the node_module folder.

```js
// don't copy and paste, pseudo code 
module.exports = {
  content: ['index.html'],
  css: ['style.css', 'node_modules/../../styles.css']
}
```
