### ISSUE TITLE
Clicking outside the content to close only works in specific areas

### ISSUE THREAD

**Issue by Eschon** [biati-digital/glightbox#154]
**Describe the bug**
Clicking outside the image to close the lightbox only works when clicking right/left of the image, clicking the areas above or below has no effect.

**Are you able to reproduce the bug in the demo site**
Yes.

**To Reproduce**
1. Go to https://biati-digital.github.io/glightbox/
2. Click on one of the images
3. Click the area above the image (I'll include a screenshot that marks the areas where the click has no effect)

**Expected behavior**
The lighbox closes

**Screenshots**
<img width="2038" alt="Screenshot 2020-09-07 at 10 37 03" src="https://user-images.githubusercontent.com/11647830/92367566-dd154080-f0f6-11ea-97fa-e4150614b6a5.png">

**Desktop:**
 - OS: Mac OS Catalina 10.15.6
 - Browser Chrome, Firefox, Safari
 - Version 85, 80, 13.1

**Comment by biati-digital** [comment]
Hi @Eschon, thank you for the detailed issue, the error is Fixed in the latest version 3.0.5

**Comment by Eschon** [comment]
Thanks for the quick fix! I've updated to 3.0.5 and everything works now.
