### ISSUE TITLE
IE 11 "Multiple definitions of a property not allowed in strict mode" when bundling and minifying glightbox

### ISSUE THREAD

**Issue by Eschon** [biati-digital/glightbox#155]
**Describe the bug**
When bundling and minifying the library with our app the following segment gets merged into the defaults:

https://github.com/biati-digital/glightbox/blob/38ca3af04c18b2f2aac3e70a3d7444686a86dde1/src/js/glightbox.js#L111

Which conflicts with

https://github.com/biati-digital/glightbox/blob/38ca3af04c18b2f2aac3e70a3d7444686a86dde1/src/js/glightbox.js#L72

**Are you able to reproduce the bug in the demo site**
No.
But the demo site doesn't seem to support IE 11 anyway

**Expected behavior**
Since the library works perfectly fine in IE 11 in development mode (no minifying) it should also work in production

**Desktop:**
 - Browser Internet Explorer
 - Version 11

The fix seems pretty straight forward. It should be no problem to just delete

https://github.com/biati-digital/glightbox/blob/38ca3af04c18b2f2aac3e70a3d7444686a86dde1/src/js/glightbox.js#L72

Since it gets overwritten a few lines later anyway. For now I've replaced the npm package with a copy of the library that has that line removed and now it works in IE 11 in production mode.

**Comment by biati-digital** [comment]
Fixed in the latest update 3.0.6
