### ISSUE TITLE
Slide parsing error as image description may not be a valid selector

### ISSUE THREAD

**Issue by ckybonist** [biati-digital/glightbox#156]
**Describe the bug**
The error happened when first character of image description is **dot**, for example:  `. 蛋黃切成30等份, 蒸熟備用.`

By viewing error stacktrace, I suspect the error is originated from slide-parser:
https://github.com/biati-digital/glightbox/blob/403b4293aaab4615e3f7d79789ce55d6c5f686c5/src/js/core/slide-parser.js#L141-L142

**Are you able to reproduce the bug in the demo site**
Yes

**To Reproduce**
1. Create a gallery
2. Give image a description with `. 蛋黃切成30等份, 蒸熟備用.`
3. Open the image gallery page on browser

**Expected behavior**
No error

**Post the code you are using**
```js
import GLightbox from 'glightbox';
import 'glightbox/dist/css/glightbox.min.css';

const glightbox = GLightbox({
  touchNavigation: true,
  loop: false,
  width: '100%',
  skin: 'icook',
  selector: 'data-glightbox',
  moreLength: 48,
  moreText: "全部內容&nbsp;<i class='icon-chevron-down-regular'></i>"
});
```

**Screenshots**
![image](https://user-images.githubusercontent.com/3832925/93694066-0217a380-fb3a-11ea-9d76-0a5fe4df521b.png)
`image-gallery.js` is the module using `glightbox`

**Desktop:**
 - OS: macOS 10.14.6
 - Browser: Edge
 - Version: 85.0.564.60

**Comment by biati-digital** [comment]
Yes, as stated in the REDME, GLightbox can use the content of a div as the description so if you have **description=".mydesc"** the code will search for a div with the class name of "**mydesc**" and display it's content in the description, this is useful when the description requires HTML like links, tables, etc.

If you want to use the dot you'll have to add the text in a div and use as description **-description=".yourdivclass"**

**Comment by ckybonist** [comment]
It would be great we can use separate data-attribute for selector and text, e.g. `data-description` and `data-description-selector`, just a suggestion : )
