### ISSUE TITLE
Plyr will be loaded even if it has already been loaded.

### ISSUE THREAD

**Issue by nicobayati** [biati-digital/glightbox#157]
**Please describe the feature you want to be implemented.**

Hello, I want to use GLightbox and plyr seperately and together on one page. I include Plyr directly into the HTML code, but i noticed that GLightbox still includes the Plyr Source on the first time I open a video. I have not found a way to prevent this.

It would be nice to check of the Plyr class already exists and if it does, Plyr class could used without load the whole plyr.js (or plyr.min.js) file.

**Explain why the feature is useful**
I think it is better for the performance if the file is not loaded again

**Comment by robinjessome** [comment]
Or, is there a way for Plyr to be loaded and available to use outside the lightbox? Just wondering about the best way to use it across any videos on a site for consistency.

> GLightbox will only inject the player library if required and only when the lightbox is opened.

I get why you do this, but can we toggle that off and use one set of Plyr options to customize?

**Comment by biati-digital** [comment]
i'll add a fix in the next update.

**Comment by biati-digital** [comment]
Fixed in the latest update 3.0.6
