### ISSUE TITLE
Uncaught (in promise) ReferenceError: evt is not defined

### ISSUE THREAD

**Issue by Hirbod** [biati-digital/glightbox#158]
Newest Version, with multiple galleries on one site, I get:
Uncaught (in promise) ReferenceError: evt is not defined
@biati-digital 

```
                    this.apiEvents.push({
                        evt: evt,
                        once: once,
                        callback: callback
                    })
```

**Comment by gaz-think3** [comment]
Did you fix this? I am having the same issue when I call .destroy()

**Comment by lysyi3m** [comment]
Related to https://github.com/biati-digital/glightbox/issues/175 

Made a PR with fix https://github.com/biati-digital/glightbox/pull/176
