### ISSUE TITLE
Next - Previous on mobile

### ISSUE THREAD

**Issue by onigetoc** [biati-digital/glightbox#162]
Hi,
great Lightbox.

I have some suggestion mostly for mobile.

For mobile, the Next Previous arrow should be visible inside the popup.
It may interesting to swipe left and right on mobile for Next / Previous elements.
May be history because 1 / 3 time i thing like i'm on a app. and and go back on Android back et i lost the page i was in.

**Comment by biati-digital** [comment]
The arrows will not be visible on mobile by default, if you want to display the arrows you can adjust the CSS to do so. You can already swipe for next and previous slide on mobile

**Comment by spurin** [comment]
@biati-digital thanks for glightbox, it's amazing.

Adding more context here should someone wish to edit the css and enable the left/right navigation button, whilst in mobile mode.  The following changes, worked for me -

```
.glightbox-clean .gprev {
  position: absolute;
  /*top: -100%;*/
  top: 45%;
  left: 30px;
  width: 40px;
  height: 50px;
}

.glightbox-clean .gnext {
  position: absolute;
  /*top: -100%;*/
  top: 45%;
  right: 30px;
  width: 40px;
  height: 50px;
}
```

@onigetoc mentioned, for reference.
