### ISSUE TITLE
iOS < 10 not working

### ISSUE THREAD

**Issue by ckybonist** [biati-digital/glightbox#164]
**Describe the bug**
Clicking the image will not open the lightbox

**Are you able to reproduce the bug in the demo site**
Yes

**To Reproduce**

1. On iOS < 10 device, open Safari / Chrome
2. Navigate to `https://icook.tw/recipes/273676`
3. Click the recipe cover or step image
4. Lightbox not open
5. Open the console, one of the error would be `TypeError: Attempted to assign to readonly property.`

**Expected behavior**
Lightbox will open when user clicks the cover / step image

**Post the code you are using**
```js
const glightbox = GLightbox({
  touchNavigation: true,
  loop: false,
  width: '100%',
  skin: 'icook',
  selector: 'data-glightbox',
  moreLength: 48,
  moreText: "全部內容&nbsp;<i class='icon-chevron-down-regular'></i>",
  onOpen: () => {
    isGalleryOpen = true;
    window.history.pushState(null, '');
  },
  onClose: () => {
    isGalleryOpen = false;
    window.history.back();
  }
});
```

**Screenshots**
![image](https://user-images.githubusercontent.com/3832925/97536996-049ed000-19f9-11eb-95c5-82a17a6714c0.png)
![image](https://user-images.githubusercontent.com/3832925/97537010-0bc5de00-19f9-11eb-94ee-27a249a09202.png)

**Smartphone:**
 - Device: iPhone 6S
 - OS: iOS 9
 - Browser: Chrome 58.0.3029 / Mobile Safari 9.0
 ps. Test on BrowserStack

**Comment by ckybonist** [comment]
Just commit a [PR](https://github.com/biati-digital/glightbox/pull/165) to fix this issue, please have a look.
@biati-digital

**Comment by Hirbod** [comment]
I would not support any iOS 9 platform. Nearly all major apps even dropped iOS10 support and only support iOS 11+
