### ISSUE TITLE
PLYR doesn't work when require.js is present

### ISSUE THREAD

**Issue by Lefthandmedia** [biati-digital/glightbox#170]
**Describe the bug**
We have a site that partly uses require. Because of this PLYR doesn't get initialised

**Are you able to reproduce the bug in the demo site**
no, but i can on any testsite

**To Reproduce**
 - add require JS in the head of your page
- try to start a videoslide

**Expected behavior**
I would expect the slide to show PLYR with my video

**Post the code you are using**
It looks like PLYR gets defined by require on some object. PLYR itself expects to be registered on window["Plyr"] but its not there. 
Imo its better to check if Plyr isn't bundled in the project before injecting those assets. to prevent unneccesary downloads

**Desktop:**
 - MacOS
 - Browser [all]

**Smartphone:**
Yes also on phones

**Comment by biati-digital** [comment]
Hi, I think the same, there's already an issue #157 requesting that, i'll update the code as soon as i've some free time.

**Comment by Lefthandmedia** [comment]
This is still not resolved. when require.js is present on a page Plyr does not work.
 I still think you should check if the Plyr Module as been bundled in the project BEFORE  loading Plyr from the CDN.

**Comment by biati-digital** [comment]
GLightbox checks if the Plyr class exists globally if not then it will load it from the CDN, this will work for most of the users, I'm not planning to do more changes to this part, I could add an option to disable loading Plyr from a CDN but this is something I need to review.
