### ISSUE TITLE
Add 'copyright' text support

### ISSUE THREAD

**Issue by colorcube** [biati-digital/glightbox#172]
**Please describe the feature you want to be implemented.**

In addition to the _title_ and _description_ it would be nice to be able to display a copyright text.

Surely it could be done by placing a copyright text in the description, but that doesn't look very nice.

A copyright text should be displayed more subtle. I propose a small overlay text like so:

```
--------------------------------

             image


(c) copyright text
--------------------------------
title
description
--------------------------------
```

**Explain why the feature is useful**
It seems more and more important to display the proper copyright for media on the internet.

**Implementation**

I may implement that and would like to know if that is something that would be merged?

I haven't looked into it very detailed and made only a quick test.
HTML and css could look like this

    <div class="gslide-media gslide-image">
        <img src="...">
        <div class="copyright">(c) Mr. Photo 2019</div>
    </div>

    .gslide-media {   
        position: relative;
        .copyright {
            position: absolute;
            bottom: 1em;
            left: 1em;
            text-shadow: 0px 0px 5px #000;
            color: #fff;
            opacity: 0.3;
            font-size: 0.8em;
        }
    }

The feature might be available for images only because it makes no sense for videos or other media!?

**Comment by colorcube** [comment]
This is what it might look like. The copyright text is in the lower left corner of the images (very subtle):

![screenshot-2020-11-19-12-53-21](https://user-images.githubusercontent.com/13253123/99663156-78675200-2a66-11eb-9cd8-133d92798468.png)

![screenshot-2020-11-19-12-51-09](https://user-images.githubusercontent.com/13253123/99662806-0989f900-2a66-11eb-82be-fe3a8c69632b.png)

**Comment by biati-digital** [comment]
Hi @colorcube For me this is a no go, the slide description can already be used to add copyright or anything you want. GLightbox can be used in many ways so everyone can decide what's the best way for them to add the information they need and to be honest it's hardly visible in the second screenshot. I'll tag this a feature request and see if more people are interested in this.

**Comment by colorcube** [comment]
Thanks for your quick feedback.

Yes it's hardly visible in the second screenshot - that was a quick try.
I can understand to be not interested in a very specific feature.

To add a bit more background, in some circumstances it's mandatory to add copyright information to images.
On the other hand, it looks ugly as description. Often I get the request to add those information as subtle as possible.

My problem is that many lightboxes do not allow to change the html template. Even with a custom template I can't pipe custom content to the template. Often you're restricted to a title and description.

I would be happy to implement the copyright thingy as an addon to glightbox (instead of a fork), but I don't see how that's possible. Any advice would be appreciated.

**Comment by colorcube** [comment]
If anybody is interested, here's a fork with support for copyright information:

https://github.com/colorcube/glightbox

**Comment by biati-digital** [comment]
Actually this could be accomplished with the API, you can use the option "slideExtraAttributes" to register your new data attributes (this is currently undocumented)

```javascript
const lightbox = GLightbox({
    slideExtraAttributes: {
        copyright: ''
    }
});
```
GLightbox will get the value of those data attributes automatically, then you can use the event "slide_before_load" to append that data when the slide is created for the first time.

```javascript
lightbox.on('slide_before_load', (slide) => {
    const { slideIndex, slideNode, slideConfig } = data;
    const copyright = slideConfig.copyright;

    slideNode.querySelector('.copyright').innerHTML = copyright;
});
```

Just an idea... you can download the latest version and try it.

**Comment by colorcube** [comment]
That looks exactly what I was looking for. I will try that (in the next days).

**Comment by biati-digital** [comment]
Closing this as the original issue has moved to another direction, feel free to open new issues if you found issues with the API

**Comment by colorcube** [comment]
Sorry for the late feedback.

It works fine except from a small error in the example. It has to be:
`const { slideIndex, slideNode, slideConfig } = slide;`

Thanks 

My code is:

```javascript
        const lightbox = GLightbox({
            slideExtraAttributes: {
                copyright: ''
            },
            slideHTML: `<div class="gslide">
                            <div class="gslide-inner-content">
                                <div class="ginner-container">
                                    <div class="gslide-media">
                                        <div class="gslide-copyright"></div>
                                    </div>
                                    <div class="gslide-description">
                                        <div class="gdesc-inner">
                                            <h4 class="gslide-title"></h4>
                                            <div class="gslide-desc"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>`
        });

        lightbox.on('slide_before_load', (slide) => {
            const { slideIndex, slideNode, slideConfig } = slide;
            const copyright = slideConfig.copyright;

            slideNode.querySelector('.gslide-copyright').innerHTML = copyright;
        });
```

SCSS:

```scss
// show copyright in lower left corner of image - very subtle
.gslide-media {
    position: relative;

    .gslide-copyright {
        display: none;
    }

    &.gslide-image {
        .gslide-copyright {
            display: block;
            position: absolute;
            bottom: 0;
            left: 0;
            padding: 1em;
            width: 100%;
            text-align: left;
            text-shadow: 0 0 8px rgba(0, 0, 0, 0.7);
            color: rgba(255, 255, 255, 0.75);
            font-size: 11px;
        }
    }
}
```
