### ISSUE TITLE
Inline content doesn't include event listeners from the original nodes

### ISSUE THREAD

**Issue by kylewetton** [biati-digital/glightbox#173]
Inline content that may have event listeners assigned to them are cloned without these listeners into the lightbox.

Example: https://codesandbox.io/s/frosty-bardeen-bvhl5?file=/index.html

I understand that cloneNode() doesn't do this out the box, in fact I'm battling to figure out how this would even be done save for just moving the nodes instead of cloning them.

The only reference to this being possible is jQuery ironically with their clone() method. Not sure how that works?

**Comment by biati-digital** [comment]
Hi @kylewetton nodes are cloned without events, this is not possible, there's no way to get all the registered events of a node with plain javascript, jQuery handles events in a different way, it has a record of all attached events to nodes (if i remember correctly) but only the events that were set with jQuery.

You need to use the API to set events in the slider content. Please take a look at the README -> Events, you'll only need the  "**slide_after_load**" event.
