### ISSUE TITLE
Scroll feature for Zoomed-in Image for Desktop Users

### ISSUE THREAD

**Issue by sajjadalis** [biati-digital/glightbox#174]
**Important.**
Someone posted a similar issue which was rejected for being not an issue. https://github.com/biati-digital/glightbox/issues/135

**Please describe the feature you want to be implemented.**
I know that drag is the feature for zoomed-in image but even on my own website, whenever i open an image, i try to scroll down first and then i say, oh right, it needs to be dragged. My partner (non-developer) also had similar experience and asked me if there is a way to scroll it down with mouse wheel.

**Explain why the feature is useful**
PC users are not used to drag stuff around and scroll is a common method for going up and down. I think it's pretty common to use mouse wheel when someone see page is going outside the screen. And I think it's important to keep the both features, mouse scroll as well as drag because drag feature on PC can help going right and left.

**Comment by biati-digital** [comment]
Hi @sajjadalis i'm sorry but i'm not planning to replace the existing functionality or add and maintain another one, you are welcome to fork and implement that and if you want you can send a pull request to share it with the community.
