### ISSUE TITLE
"data-title" Getting Overwritten when "title" is present

### ISSUE THREAD

**Issue by sayontan** [biati-digital/glightbox#178]
I am the author of a WordPress plugin that displays galleries from various sources and attaches lightboxes to them (https://wordpress.org/plugins/photonic).

As a part of the next iteration of my plugin I was looking to add GLightbox to my codebase. While building this out, though, I encountered a problem. In my markup I use both, `title` and `data-title`. The `title` attribute has the title without any markup, and the `data-title` has the title linking to an external URL for the photo (e.g. a URL on Flickr).

When I try this, though, GLightbox seems to be ignoring the `data-title` and printing just the `title`. I looked through the code and it looks like this is the culprit, in file glightbox.js (line 1977 in https://github.com/biati-digital/glightbox/commit/4e89877e134c1172e6653584042dfee4a2a3d715):

`          if (nodeType == 'a') {
            var title = element.title;
            if (!isNil(title) && title !== '') data.title = title;
          }`

If you do a `console.log(data.title)` before and after the `if (!isNil...)` line, you will see that the `data.title` is getting overwritten by the `title`.

**Comment by biati-digital** [comment]
Yes, this should not be happening, data-title should not be overwritten if it has a value, i'll publish an update this weekend

**Comment by biati-digital** [comment]
Fixed in the latest update 3.0.6
