### ISSUE TITLE
The description contains the <A> tag

### ISSUE THREAD

**Issue by rolandcsige** [biati-digital/glightbox#18]
HTML:
`<li class="box visible">
          <a href="demo/img/large/gm7.jpg" class="glightbox2" data-glightbox="title:Description Bottom; description: You can set the position of the desciption; descPosition: right;">
						<img src="demo/img/small/gm7.jpg" alt="image">
					</a>
        </li><div class="glightbox-desc">
							<p>You can set the position of the desciption in different ways for example top, bottom, left or right</p>
							<p>Duis quis ipsum vehicula eros ultrices lacinia. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere
								cubilia Curae Duis quis ipsum vehicula eros ultrices lacinia. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere</p>
						</div>`
JS (541. row):
`var nodeDesc = element.parentNode.querySelector('.glightbox-desc');`

**Comment by biati-digital** [comment]
Hi, please download the latest version, make sure the div with the description is outside your a tag, checkout the readme or the index.html for more information.
