### ISSUE TITLE
Thumbnail are not fully loading - Mobile devices

### ISSUE THREAD

**Issue by qaleaddev** [biati-digital/glightbox#181]
**Describe the bug**
It seems that when accessing the page that has a lightbox for the first time, iPhone and iPad devices are not fully rendering Thumbnail(s). The issue can be fixed by completely exiting the browser and reopening the page. Refreshing doesn't fix it.

**Are you able to reproduce the bug in the demo site**
YES

**To Reproduce**
1. Navigate to a page that has a lightbox photos for the first time
2. When all the Thumbnails photos are loaded
3. Then certain Thumbnails are not loaded completely (Loaded mid-way)

**Expected behavior**
I expect for all Thumbnails to be loaded

**Post the code you are using**

<div class="row">
                <div class="col-md-12">
                   <ul class="box-container three-cols">
                        <li class="box">
                            <div class="inner">
                                <a href="1.JPG" class="glightbox">
                                    <img src="1.JPG">
                                </a>
                            </div>
                        </li>
                        <li class="box">
                            <div class="inner">
                                <a href="2.JPG" class="glightbox">
                                    <img src="2.JPG" alt="image">
                                </a>
                            </div>
                        </li>
                        <li class="box">
                            <div class="inner">
                                <a href="3.JPG" class="glightbox">
                                    <img src="3.JPG" alt="image">
                                </a>
                            </div>
                        </li>
                      </ul>
                   </div>
                 </div>

**Screenshots**
See here: 
![bug](https://user-images.githubusercontent.com/75215315/100547991-d00c7700-3237-11eb-809d-2e6f720ca43b.jpg)

**Desktop:**
NA

**Smartphone:**
 - Device: iPhone XS MAX PRO, iPad 6 Gen
 - OS: iOS
 - Browser: Safari, Chrome
 - Version: Latest

Notes:
1- the images I am using are 133KB in size, so small
2- the rest of the Thumbnails are loading perfectly, just certain ones on the top of the gallery
3- It consistent and happens on mobile devices only
4- internet connection is great
5- doesn't happen on local (Only on deployed server)
6- happens when accessing the page for the first time, refreshing doesn't fix it, only when exiting and reopening the page again.
7- Using the original code of the author, didn't change anything or set anything. 

Thoughts?

**Comment by biati-digital** [comment]
This is the first time i hear this, i'm testing on an iPhone 11 with Safari and i'm not able to reproduce that error using the demo site.  

GLightbox will simply create an img tag and add your image URL, i really don't think it's related to GLightbox, unfortunately i don't have the time to check it, you could try searching for "image partially loaded" in google or stackoverflow.

**Comment by qaleaddev** [comment]
Hey @biati-digital, thanks for your prompt response. 

I figured it out, I was using the same photo file size for both the thumbnail and modal photo. It seems that thumbnails file size have to be in smaller size. I resized all photos specifically for the thumbnail to be of a smaller size and all works now (60KB)

Please close this bug as resolved. Thanks so much!
