### ISSUE TITLE
Multiple YouTube videos will always play last in group

### ISSUE THREAD

**Issue by n-dawson** [biati-digital/glightbox#182]
**Describe the bug**
When you have multiple YouTube links sharing a selector, clicking any will always play the last video in the group. The video you've selected will be shown but it will be the last video in the group of slides that is actually playing.

**Are you able to reproduce the bug in the demo site**
No*

*The videos shown on the demo site are from 3 different sources. Change all three links to YouTube however and the issue will appear.

**To Reproduce**
1. Download the demo
2. Change the href for the first and third example from other sources to YouTube videos
3. Click any of the thumbnails
4. The video you've selected will appear while the video that's playing will be the last in the list.

**Expected behavior**
The video clicked will be the video that plays.

**Desktop:**
 - OS: macOS Catalina
 - Browser Firefox, Chrome
 - Version: 83.0(FF), 86.0.4240.198 (Chrome)

**Comment by biati-digital** [comment]
? please share a live demo or the code to copy paste.

**Comment by n-dawson** [comment]
Thanks for your response. I've created a very simplified demo based on the example site:

```
<link rel="stylesheet" href="https://biati-digital.github.io/glightbox/dist/css/glightbox.css">

<ul>
    <li>
            <a href="https://www.youtube-nocookie.com/embed/FmyWmfujfF4" class="glightbox">
                <img src="https://biati-digital.github.io/glightbox/demo/img/small/gm10.jpg" alt="image" width="200">
            </a>
    </li>
    <li>
            <a href="https://www.youtube-nocookie.com/embed/Ga6RYejo6Hk" class="glightbox">
                <img src="https://biati-digital.github.io/glightbox/demo/img/small/gm11.jpg" alt="image" width="200">
            </a>
    </li>
    <li>
        <a href="https://www.youtube-nocookie.com/embed/Pqbb0p2mGIE" class="glightbox">
            <img src="https://biati-digital.github.io/glightbox/demo/img/small/gm12.jpg" alt="image" width="200">
        </a>
    </li>
</ul>

<script src="https://biati-digital.github.io/glightbox/dist/js/glightbox.js"></script>

<script>
    var lightboxVideo = GLightbox({
        selector: '.glightbox'
    });
</script>

```

**Comment by biati-digital** [comment]
thank you for the code, i'm not able to replicate the error you mention, if i click the first link i see the correct video, the same for the others.

**Comment by n-dawson** [comment]
I'll dig in to the code over the weekend but it's worth pointing out that this issue is new. We updated 3.0.5 -> 3.0.6 to solve an Android playback issue which is when we discovered this new problem. I've since looked back at the older setup and it's not an issue there.

**Comment by biati-digital** [comment]
i'm testing in the latest version 3.0.6 and not able to see the error you mention, anyway if you find something let me know.

**Comment by biati-digital** [comment]
Hi @n-dawson  Did you find something? Did you try it with the demo site? i'm still not able to replicate this issue. If you don't have time to test it now i'll close this issue.

**Comment by Nuuou** [comment]
I know this is closed, but I'm also experiencing a similar issue (with Vimeo, and it playing a seemingly random slide video).
Similar to @n-dawson, I started noticing this issue after updating from 3.0.5 -> 3.0.6.

Downgrading to 3.0.5 has resolved this issue for me again.

I've put together a demo of this bug in 3.0.6:
https://codesandbox.io/s/glightbox-306-bug-v4u66

Notice that on page load, clicking either Video 1 or Video 3 play the incorrect video (both play Video 2 in this instance).
