### ISSUE TITLE
YouTube autoplay broken on iOS

### ISSUE THREAD

**Issue by n-dawson** [biati-digital/glightbox#183]
**Describe the bug**
When you open a YouTube video in the lightbox on an iPhone, it looks as though it's loading but then stops. The player controls show a pause button as though the video is playing. The user must click pause and then play again in order to start the video.

**Are you able to reproduce the bug in the demo site**
Yes

**To Reproduce**
1. Go to demo site on an iPhone and click the YouTube video example

**Expected behavior**
Ideally autoplay the video but if not possible, correctly recognise the video state as not playing.

**Post the code you are using**
Example code.

**Screenshots**
![IMG_0159](https://user-images.githubusercontent.com/3666437/101259131-ea09f600-371e-11eb-8f83-da4c6d6797bd.png)

**Smartphone:**
 - Device: iPhone XS
 - OS: 14.2
 - Browser Safari

**Comment by biati-digital** [comment]
Yep, that's weird, i just simply call the play method from Plyr, not sure why it's stopped, i'll take a look at this.

**Comment by biati-digital** [comment]
This is not related to the library, there's several issues on the Ply repository about this [https://github.com/sampotts/plyr/issues/1422](https://github.com/sampotts/plyr/issues/1422) There's nothing we can do to change this.

I've added more information in the README.
