### ISSUE TITLE
Separating Video/Picture Thumbnail Appearance

### ISSUE THREAD

**Issue by ux-paul-grossmann** [biati-digital/glightbox#185]
Hey,

is there a way to integrate a play button overlay on every thumbnail? I mean the default-nonhover-state. Right now I'm trying to add this via css ::after and/or doing a workaround by simply placing that triangle play button right in photoshop and export it. Yet I can imagine that this feature is what users expect to find to be able to distinguish between an element indicating itself as a picture or video. Additionally the duration could also be displayed on this thumbnail. What do you think? 

`<a href="path/to/vid.mp4" class="glightbox3">
       <img src="path/to/thumbnail.png" alt="image" class="d-block w-100">
</a>`

![image](https://user-images.githubusercontent.com/27516495/102019177-3afa9980-3d72-11eb-9ee1-b71726d03412.png)

**Comment by biati-digital** [comment]
Sorry, this is not related to GLightbox, that it's entirely up to you. You'll have better luck on Stackoverflow as that it's really basic CSS
