### ISSUE TITLE
Add support for flickr video

### ISSUE THREAD

**Issue by MPParsley** [biati-digital/glightbox#186]
Flickr adds the following header: `x-frame-options: DENY`.

When embedding a flickr video, this results in the following error:
`Refused to display 'https://live.staticflickr.com/video/***' in a frame because it set 'X-Frame-Options' to 'deny'.`

Either we need to add documentation for the proper data-type or data-format to use for Flickr or add support to render Flickr video's without using an iframe.

Edit: currently showing Flickr video's should be possible using inline content instead of using an iframe.

**Comment by biati-digital** [comment]
As stated in the Readme, only YouTube, Vimeo and self hosted videos are supported.

There's no plans to add support to other services as that it's the job of Plyr, you are welcome to create an issue the the Plyr repository asking support for Flickr, if they add it GLightbox can use it.
