### ISSUE TITLE
closeOnOutsideClick area not working

### ISSUE THREAD

**Issue by Alexufo** [biati-digital/glightbox#188]
Mouse click on red area works well but on other areas it does not work . In example on https://biati-digital.github.io/glightbox/ 
I can not reproduce this issue. I see this issue in my integration. How I can debug it?

![2020-12-24_20-49-41](https://user-images.githubusercontent.com/1562329/103102007-2b5d3980-462b-11eb-9caf-2f57f09402a1.png)

It works well on desktop. Mobile browser has it.

example

1. https://codepen.io/Alexufo/pen/NWRwqKN and press button
2. open devtool
3. toggle to mobile device bar
4. set width of browser to 670px

black areas doesnot react to click. Modal popup will not be closed

![image](https://user-images.githubusercontent.com/1562329/103112479-b9a2e100-4666-11eb-96ac-b030d96182bd.png)

**Comment by biati-digital** [comment]
That setting will only work for desktop, on mobile you swipe up/down to close

**Comment by Alexufo** [comment]
Swipe up/down doesnot work as you can see in example.

**Comment by Alexufo** [comment]
I use glightbox as popup and I dont want to change behavior between desktop and mobile. If I can close popup on desktop by tap outside - this approach must works on mobile.

as solution


```
glightbox.on('open', () => {
    let gbody= document.querySelector('#glightbox-body');

    gbody.addEventListener("touchend", function(event) {
        console.log(event.target);
        if (event.target.id !== "your_modal_id") {
            glightbox.close();
            return;
        }
    });
});
```

**Comment by biati-digital** [comment]
Yeah, on mobile swipe up/down only works for certain type of slides, for inline content it was deactivated because you can add any kind of content, the content can be larger than the screen and use scroll to navigate or you could implement your own touch events to the slide content, etc. 

Glad you found a solution for your integration, I'll close this issue now, if you find any bugs please let me know.

**Comment by Alexufo** [comment]
it should be documented. This is not expected (and not easy to understand) behavior.  Looks like a bug until you said about working scheme

**Comment by Alexufo** [comment]
it should be documenteted

**Comment by biati-digital** [comment]
Not sure if this should be documented, there has been more than 100k downloads and this is the first issue mentioning this but in any case pull requests are welcome.
