### ISSUE TITLE
draggable: false option not working

### ISSUE THREAD

**Issue by CoolS2** [biati-digital/glightbox#192]
**Describe the bug**

Still draggable with mouse

               `let elements = [];

                Object.keys(gallery).map((k) => {
                       elements.push({
                            'href': gallery[k].big,
                            'type': 'image'
                        })
                })

                const myGallery = GLightbox({
                    elements: elements,
                    draggable: false,
                    startAt: index,
                    dragToleranceY: 0,
                    touchNavigation: false,
                    height: '50%',
                });

                myGallery.open();`

**Desktop:**
 - Browser chrome
 - Plugin Version 3.0.6

**Comment by biati-digital** [comment]
This should be fixed in 3.0.7

**Comment by viliusle** [comment]
Still does not work if using with `setElements`

**Comment by frankie-tech** [comment]
Hey there @viliusle,

Since this is an old issue, would you mind creating a new one? I know you've filled out a couple over the last couple of days, but it helps us keep track of things 😊
