### ISSUE TITLE
Audio files not supported ?

### ISSUE THREAD

**Issue by Okipa** [biati-digital/glightbox#193]
**Describe the bug**

Audio files are not handled in audio player.

**Are you able to reproduce the bug in the demo site**

No, as there is no audio file example.

**To Reproduce**

1. Instead of an image, set the the link URL targeting an audio file.
2. Click on the link, it will not open the audio file in an audio player but a lightbox background will be displayed instead.

**Expected behavior**

A link with an audio file should be opened in an audio player.

**Post the code you are using**

```HTML
<a class="glightbox" href="https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_700KB.mp3" title="Audio file">
    <img src="https://biati-digital.github.io/glightbox/demo/img/small/gm1.jpg" alt="image">
</a>
```

**Screenshots**

<img width="1440" alt="Capture d’écran 2020-12-28 à 14 58 25" src="https://user-images.githubusercontent.com/5328934/103219177-4aa2e200-491d-11eb-9a0e-985b1e86693a.png">

**Desktop:**

 - OS: MacOS 11.1
 - Browser: Chrome 87.0.4280.88

**Comment by Okipa** [comment]
I didn't know if I should post this as a bug or a feature request, so please do not feel offended if that was intentionally not supported (well, I hope not !).
 
Would you know a quick workaround in a order to be able to handle audio files opening with glightbox ?

By the way, your lightbox library is the better I was able to find on the Web, and I am searching for some hours now ! Thanks a lot for the good work !

**Comment by Okipa** [comment]
FYI I managed to work something out. Here is what I've done in order to add audio files support. You may be interested to reuse parts of it if you wish to add audio files support.

Another information: I use you library to only open the clicked `href` in `glightbox` rather than opening everything in gallery. This is why the treatment is embedded in this logic and , sorry for that.

### JS part

```js
async function getMimeType(url) {
    return new Promise(function (resolve) {
        const xhr = new XMLHttpRequest();
        xhr.open('HEAD', url);
        xhr.onreadystatechange = function () {
            if (this.readyState === this.DONE) {
                console.log(this.getResponseHeader('Content-Type'));
                resolve(this.getResponseHeader('Content-Type'));
            }
        };
        xhr.send();
    });
}

_.each(document.querySelectorAll('[data-lightbox]'), (item) => {
    item.addEventListener('click', function (e) {
        e.preventDefault();
        const url = this.getAttribute('href');
        getMimeType(url).then((mimeType) => {
            const isAudio = mimeType.startsWith('audio/');
            const lightbox = GLightbox({
                skin: isAudio ? 'audio' : null,
                elements: [
                    isAudio ? {
                        skin: 'bg-primary',
                        content: '<audio class="w-100" controls autoplay><source src="' + url + '"/></audio>',
                        height: 'auto'
                    } : {href: url}
                ],
                zoomable: false
            });
            lightbox.open();
        });
    });
});
```

## SASS part

```sass
@import '~glightbox/dist/css/glightbox.min.css';

.glightbox-audio {

    .gslide-inline {
        background: none !important;

        .ginlined-content {
            background: none !important;
        }
    }
}
```

**Comment by biati-digital** [comment]
Hi, Audio files are not supported, I'm still considering adding support in a future version.
