### ISSUE TITLE
Make all required resources local.

### ISSUE THREAD

**Issue by styromaniac** [biati-digital/glightbox#198]
I have a site that I would really like to have Glightbox, but because of the nature of the network (it's P2P), people prefer that sites have all resources be local instead of external. Can you please provide an identical version of Glightbox that is without CDN dependency?

**Comment by biati-digital** [comment]
What CDN dependency are you referring to?

**Comment by styromaniac** [comment]
>plyr: {
      >css: 'https://cdn.plyr.io/3.6.3/plyr.css',
      >js: 'https://cdn.plyr.io/3.6.3/plyr.js',

**Comment by biati-digital** [comment]
You can configure that, simply store those files in your server and set the url to your local files, you can find more information in the README.

**Comment by styromaniac** [comment]
I tried editing it to

plyr: {
  css: 'plyr.css',
  js: 'plyr.js',
  
  and then including Plyr's dist files in the same folder. Now the video doesn't play, but instead the loader keeps spinning.

**Comment by biati-digital** [comment]
You need to pass the full url to those files https://...

**Comment by styromaniac** [comment]
I can't do that. Links must be relative. The site is accessed through localhost or other IP addresses, depending on the user's customizations

**Comment by biati-digital** [comment]
Sorry, then it will not work, the code needs the full url

**Comment by biati-digital** [comment]
Alternatively you can just download Plyr js and css files and add them directly in your site, Glightbox will detect it and will not include the cdn files.

**Comment by styromaniac** [comment]
What folder would I drop the dist files into?

**Comment by biati-digital** [comment]
does not matter, GLightbox just simply checks if Plyr has been loaded and if so it will skip the CDN files. just download plyr and add the script tag in your HTML, you can check the Plyr documentation for more information.

**Comment by styromaniac** [comment]
Oh, cool!

**Comment by styromaniac** [comment]
![Screenshot from 2021-01-20 17-41-53](https://user-images.githubusercontent.com/43807387/105249939-ed2e3980-5b46-11eb-8764-6d6e12c98028.png)

<script src="dist/plyr.js"></script>

Something isn't right.

**Comment by biati-digital** [comment]
did you include the Plyr CSS file?

**Comment by styromaniac** [comment]
> did you include the Plyr CSS file?

My bad.

**Comment by styromaniac** [comment]
Button SVGs are still loading from the clearnet.

**Comment by biati-digital** [comment]
That's not GLightbox, that's Plyr, you'll have to read the Plyr docs, I'm 100% sure those svg can also be customized but can't remember right now how.

**Comment by styromaniac** [comment]
> That's not GLightbox, that's Plyr, you'll have to read the Plyr docs, I'm 100% sure those svg can also be customized but can't remember right now how.

Maybe data URI would fix it.
