### ISSUE TITLE
Use inline content directly instead of cloning it

### ISSUE THREAD

**Issue by DanielBielczyk** [biati-digital/glightbox#199]
I have a form that opens in lightbox. I bind submit event listener on the form which sends data with ajax. But when the popup opens, there is no listener. Original form stays in DOM and clone is put into lightbox - without listener cloned.
Is there any option to change this behavior? Or more generally - what is the reason to not use original element and clone it instead? IMHO using the original element would be more logical.

**Comment by biati-digital** [comment]
Has been explained a few times before why the elements are cloned.

Just set your listeners using the API.

```javascript
lightbox.on('slide_after_load', (data) => {
  // data is an object that contain the following
  const { slideIndex, slideNode, slideConfig, player, trigger } = data;

  // Add your listeners to
  slideNode.querySelector...
});```
