### ISSUE TITLE
Aria-hidden

### ISSUE THREAD

**Issue by delrueba** [biati-digital/glightbox#202]
**Please describe the feature you want to be implemented.**
Good work on implementing the body scroll lock!
To improve accessibility it would be wise to add aria-hidden=true on all root elements except the glightbox-container.

**Explain why the feature is useful**
Screen readers have different ways of navigating a web page, aside from tab and shift tab.
By placing aria-hidden=true on all root elements except the glightbox-container when the page is obscured by the gallery, and removing this attribute again when the gallery is closed: the page is also hidden for screen readers.

I understand we can tap into the open and close events, but I feel this is something that should be default behavior.

**Have you seen it somewhere else?**
https://stijlgids.stad.gent/v4/components/detail/modal.html

**Comment by biati-digital** [comment]
Definitely, I'll add this in the next update.

**Comment by biati-digital** [comment]
This has been added in 3.0.8
