### ISSUE TITLE
failure to detect image sourcetype

### ISSUE THREAD

**Issue by bbbart** [biati-digital/glightbox#204]
**Describe the bug**
A GLightbox pointing to an image gets wrongly detected as begin of the type `external` when the URL to the image does not end on jpg, jpeg, png, .... In my case, I'm having a URL like "/static/img/logo.png?h=12345", with 12345 a random number generated each time the image changes to force refresh caches.

**Expected behavior**
I would expect GLightbox to detect the sourceType correctly, for example by parsing the URL and removing the queryString before the regexp matching (or some other "intelligent" url parsing).

**Comment by biati-digital** [comment]
this will be improved in the future as ie11 support will be removed, in the meantime you can specify the type, checkout the docs or the other closed issues.

**Comment by bbbart** [comment]
got it; thanks for the prompt  reply!
