### ISSUE TITLE
Lightbox closes if dragging up on image, despite dragToleranceY: 0

### ISSUE THREAD

**Issue by ChrissiQ** [biati-digital/glightbox#205]
**Describe the bug**
If there is an image in the lightbox, dragging up on it on a mobile device/mobile size on Chrome/Safari closes the lightbox.  The behaviour of closing when scrolling up can normally be disabled by setting `dragTolerance: 0`, but it does not work when trying to scroll down when an image is at the top of the lightbox.

**Are you able to reproduce the bug in the demo site**
No, this is expected behaviour for your demo, but it should be able to be turned off via dragToleranceY or some other means.  My modal has content which scrolls, but users cannot scroll down past an image, since dragging the image always closes it and can't be turned off unless touch events are completely disabled.  I still want touch events, but not to close when swiping up.

**To Reproduce**
1. Add an image at the top of a lightbox which has enough content to scroll.
2. Try to scroll down by dragging the image with a touch device.
3. The modal closes instead of scrolling down.  Usually this seems to be expected behaviour so that image lightboxes close when scrolled up, but it must be able to be turned off because it breaks modals that have an image + more content below to scroll down to.

**Expected behavior**
I expect to be able to disable the behaviour where the modal closes when the user swipes up, since this is resulting in my modals with an image at the top being unable to be scrolled through.  Attempting to scroll closes the modal.

I am not including code, and it happens on all browsers/devices with touch events if you have an image at the top of a scrolling modal.  The modal can't be scrolled since dragging on the image closes it.

**Comment by biati-digital** [comment]
I'm not sure what you mean, images should not add scroll, unless you zoom the image but in that case the other events are disabled and it's really not scroll as we simply adjust the image position with CSS, the image should adjust it's size to fit the viewport, can you share a demo?

I'll check dragToleranceY as 0 should disable that functionality.

**Comment by ChrissiQ** [comment]
There is an image at the top of the modal content and text below which cannot be seen until one has scrolled past the image.  Scrolling past the image on a touch device does not work, because attempting to drag up on the image closes the modal instead of scrolling down.

**Comment by ChrissiQ** [comment]
@biati-digital This seems to be the offending code: https://github.com/biati-digital/glightbox/blob/f74dac2e2160ddc0f06664f7535cae591482246a/src/js/core/touch-navigation.js#L181

**Comment by ChrissiQ** [comment]
Demo: https://jsfiddle.net/qwtj1vz6/1/show

Use a small touch device. When you attempt to scroll down the modal content, it will close because you dragged the image up.

Demo code: https://jsfiddle.net/qwtj1vz6/1/

**Comment by biati-digital** [comment]
There's a few things wrong with your example, first, you can not add HTML inside a data attribute, you need to encode it or add your description in a different div, please checkout the README for more information, second, that's not the original GLightbox CSS so or slide HTML, GLightbox does not work like your example, for mobiles, the description is displayed below with a link to read more. If expanded, the description is displayed above the image so you only scroll the text

![CleanShot 2021-02-10 at 21 30 04](https://user-images.githubusercontent.com/1219228/107599788-586ba880-6be7-11eb-8138-cefb4ad3205a.png)

![CleanShot 2021-02-10 at 21 31 23](https://user-images.githubusercontent.com/1219228/107599792-5b669900-6be7-11eb-9e03-80a25039b7f6.png)

Please use the GLightbox CSS and slide HTML in your example, as slide images were not intended to work the way you are doing it, if your project requires to display them like that then it's better that you set you slide as inline as inline content can be scrolled without problems.

**Comment by ChrissiQ** [comment]
Thank you for looking into this.

I understand that this isn't the normal slide HTML, but I didn't think it should break due to our changes.  The docs do indicate that the lightbox is themeable and you can write different HTML with the `slideHTML` setting, so I don't see why that would interfere with the correct functioning of the slides.

I'm not aware of any rule regarding not including HTML inside data attributes.  Do you mean just for this library that you don't support this usage?  Regardless, it does not seem to be causing any particular problem - we can remove all the HTML from that attribute and the functionality is identical.  So I don't see why that's relevant here.  It has no effect on the issue we are seeing whether we use HTML in there or not.

The glightbox library CSS actually is included and used in the demo, but as you can see we have a lot of CSS overrides on our project for a custom theme and appearance. I was not aware that reskinning the modal with custom CSS should cause this sort of bug. I know it is different than the default appearance, but it still seemed like it should work, since there is not really any change to the basic functionality here - just to the appearance.

Thanks for the info about using the `inline` type.  I will give that a try and hope that fixes it.  I can understand that maybe the image media type is intended for a specific effect, and if using the inline type bypasses that, maybe that should be documented?  Just a thought.

Thanks again!

**Comment by biati-digital** [comment]
Yes, GLightbox is themeable, the problem is that you are modifying the most basic type of slides "image slide" to make it work in a different way, you are basically modifying the image slide to make it work like an inline slide, you are better of using an inline slide.

For this library, it depends entirely on the HTML you add, there's been users adding links inside the link and other kind of HTML that may not be parsed correctly even by the browser, si I do recommend to keep it separated or encode it.

The problem is that I do not know if your changes make it work in a different way and to be honest I don not have time to review your code so there's nothing I can do on this part.

There are several types of slides, Inline slides are created to handle any kind of HTML, image slide handles images, video slides handles videos, etc. to be honest I thought this was pretty straightforward, When I've some free time I'll review the docs and probably add some other examples.
