### ISSUE TITLE
Newb Initialization Issues

### ISSUE THREAD

**Issue by stallarida** [biati-digital/glightbox#206]
Despite following examples, I continue to get an "Uncaught ReferenceError: GLightbox is not defined" error.

CODE:
script is def getting included.  If I add, for example, a console log or alert to glightbox.js it fires.

CODE at bottom of page:
<script>
  document.addEventListener('DOMContentLoaded', function(event) {
    const lightbox = GLightbox({
        selector:  'glightbox3',
        touchNavigation: true,
        loop: true,
        autoplayVideos: true,
        onOpen: () => {
            console.log('Lightbox opened')
        },
        beforeSlideLoad: (slide, data) => {
        }
    });
})
</script>

gallery code:
<%= link_to image_tag(entry.images[image]), :class => "glightbox3", :'data-gallery' => 'gallery1' do %>
    <%= image_tag(entry.images[image].variant(resize_to_fill: [200, 300]).processed, :class =>"", data: {alt: 'image'}) %>
<% end %>

Which results in:

<a class="glightbox3" data-gallery="gallery1" href="https://8038fbb2b6f24c1788891f50e3a57cd7.vfs.cloud9.us-west-2.amazonaws.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBaUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--51d336cb73b5270ad1f7a722396120967a34f8fe/g10.gif">

<img class="" data-alt="image" src="https://8038fbb2b6f24c1788891f50e3a57cd7.vfs.cloud9.us-west-2.amazonaws.com/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBaUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--51d336cb73b5270ad1f7a722396120967a34f8fe/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCam9UY21WemFYcGxYM1J2WDJacGJHeGJCMmtCeUdrQ0xBRT0iLCJleHAiOm51bGwsInB1ciI6InZhcmlhdGlvbiJ9fQ==--0bf893f052599156b73dc10d1f6f61577efcd510/g10.gif" />

 </a>

**Comment by biati-digital** [comment]
Please take a look at the docs and demo site, if you need help please post it on stackoverflow. this is only for issues related to the library or feature requests.
