### ISSUE TITLE
By clicking on the "SEE MORE" link in .gslider-description, the modal window is closed

### ISSUE THREAD

**Issue by jarisgv** [biati-digital/glightbox#211]
**Describe the bug**
I customized the layout of the option **Image with Captions** to look like Twitter/Facebook post in modal window.
Everything looks fine in large screens, but when I try to use it in devices such as iPad or mobiles phones with large screens (tested also on my physical devices) the text appears truncated and as I click on the 'See more' link, the window closes suddenly.

**Bug**

>>> WORKING
![Glitghbox-Modal-Window-Bug_01](https://user-images.githubusercontent.com/19142770/110063535-1a772580-7d4a-11eb-800f-3d00f65a12b2.gif)

>>> FAILS
![Glitghbox-Modal-Window-Bug_03](https://user-images.githubusercontent.com/19142770/110063592-3084e600-7d4a-11eb-9e8f-7590f422a5b9.gif)

**Comment by frankie-tech** [comment]
Can you include a link to the code example?

**Comment by jarisgv** [comment]
Hi @frankie-tech 

https://byjaris.com/code/c/glightbox/

You can check it here

**Comment by frankie-tech** [comment]
Thank you for doing that, I'm also seeing that on my phone and computer as well. It is also possible to reproduce the issue on the demo site. 

I'm only able to reproduce it when the iPhone/iPad simulator is in landscape mode, if it is in portrait the description expands just fine.

I'll look take a look into this 🙂

**Comment by frankie-tech** [comment]
@jarisgv I found what is causing your problem *I think* - if you add `closeOnOutsideClick: false` to your config object, that will prevent the slide from closing when the `See More` link is clicked.

The event callback inside of this if statement [here](https://github.com/biati-digital/glightbox/blob/master/src/js/glightbox.js#L994-L1005), fires when you click on the `See More` link. Adding that config option will get you most of the way there.

**Comment by jarisgv** [comment]
@frankie-tech 
Thank you so much !!!
It's working perfectly now with after your support
Tested in iOs, Android and Chrome.
Once more, thank you for your attention !!!
![1203](https://user-images.githubusercontent.com/19142770/110224624-eae82a80-7ebb-11eb-8a88-d35cef0b95c8.gif)

**Comment by frankie-tech** [comment]
Glad to hear it 😊
