### ISSUE TITLE
Adding a download button

### ISSUE THREAD

**Issue by yujiri8** [biati-digital/glightbox#217]
How to add a download button? We want to have a button, similar to the close button, that downloads the image on click/tap.

I looked at the possibility of doing this by modifying the lightbox HTML as described in the README, but I don't believe that will work because the HTML is a constant string so it cannot depend on the slide being shown, meaning it cannot contain a download link.

**Comment by frankie-tech** [comment]
Sounds like you need to change some HTML `before_slide_change`s!

It's for an older version of GLightbox, but #69 has a couple examples you can use to give you an idea of how it could work.
