### ISSUE TITLE
Vimeo video does not launch on Chrome 89 (unless muted)

### ISSUE THREAD

**Issue by didrip** [biati-digital/glightbox#220]
**Describe the bug**
Video loads but does not play on Chrome 89 (ok on Chrome 88).

**Are you able to reproduce the bug in the demo site**
Yes, the first video of the left (skeleton) does not play.

**To Reproduce**
1. Click on one of the video thumbnails
2. Click play

**Expected behavior**
When clicking on play the video should start to play.

**Post the code you are using**
https://codesandbox.io/s/glightbox-307-bug-chrome-89-3gdbc

**Screenshots**
![image](https://user-images.githubusercontent.com/18724661/112128366-a7353680-8bc6-11eb-8781-201df78d4e3a.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 89

**Smartphone:**
not tested on smartphone

====

edit: I forgot to mention that it also happens with `autoplayVideos` set to `false` (first thing I tried)

**Comment by didrip** [comment]
It is actually when the video is not muted that the video does not play. After clicking mute button, one can play the video. After unmuting, then the video stops again.

![image](https://user-images.githubusercontent.com/18724661/112147706-4f55fa00-8bdd-11eb-9451-c61520fc81df.png)

**Comment by frankie-tech** [comment]
Thanks for filing a bug report!

When I test the CodeSandbox you added, it is working for me sporadically, is this the same for you? Also I find this error in the console:

<img width="959" alt="image" src="https://user-images.githubusercontent.com/26461046/112169962-0b58fa00-8bc9-11eb-97b1-357edbbe8edd.png">

This makes me think that it has something to do with Vimeo's iFrame JS API, and how it is managing [autoplay permissions](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes).

If that is the case, it is out of our control. I will investigate a little further though 😊

**Comment by frankie-tech** [comment]
As I thought, this is not something that is out of our control. You can try looking at the issues in Vimeo's player repo [issues](https://github.com/vimeo/player.js/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc), or filing your own.

I'll close this for now, but I'd be interested to hear how it ends up 😊

**Comment by didrip** [comment]
> 
> 
> Thanks for filing a bug report!
> 
> When I test the CodeSandbox you added, it is working for me sporadically, is this the same for you? Also I find this error in the console:
> 
> <img alt="image" width="959" src="https://user-images.githubusercontent.com/26461046/112169962-0b58fa00-8bc9-11eb-97b1-357edbbe8edd.png">
> 
> This makes me think that it has something to do with Vimeo's iFrame JS API, and how it is managing [autoplay permissions](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes).
> 
> If that is the case, it is out of our control. I will investigate a little further though 😊

Yes Indeed I saw the same error in the logs, but not every time, that is why I thought this was not an `autoplay` problem.

I will check the repo and let you know. In the meantime I have put my videos on mute and unmute them on load.

```js
const glightbox = GLightbox({
	selector: '.project-block',
	touchNavigation: true,
	loop: false,
	autoplayVideos: true,
	closeButton: true,
	plyr: {
		// plyr CSS and JS URLS are required here otherwise "Inject videos api error"
		css: 'https://cdn.plyr.io/3.6.2/plyr.css', // default value
		js: 'https://cdn.plyr.io/3.6.2/plyr.polyfilled.js', // polyfilled version
		ratio: '16:9', // required otherwise error split undefined
		config: {
			muted: true // bug on chrome 89
		}
	}
});

// unmute video on load (bug on chrome 89)
glightbox.on('slide_after_load', (data) => {
	$(data.slideNode).find('video').prop('muted', false);
});
```

This workaround makes video playing normally on other browser and in plays them muted on Chrome 89 (because the call `.prop(muted, false)` does not work on Chrome 89).

**Comment by didrip** [comment]
I was not able to reproduce the issue on the vimeo demo website => https://player.vimeo.com/api/demo

Click on (external) play button plays the video normally in Chrome 89 despite not muted.

After further investigation it turns out that adding some props to the iframe `allow` attribute did the trick.

 `allow="autoplay; fullscreen; accelerometer; encrypted-media; gyroscope;picture-in-picture"` (copied from vimeo demo website).
        

I made a demo here => https://codesandbox.io/s/vimo-player-api-test-s0x19?file=/index.html:236-685

**Comment by didrip** [comment]
`el.setAttribute("allow", "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture");`

see https://github.com/vimeo/player.js/issues/389#issuecomment-466648134

**Comment by frankie-tech** [comment]
You're too fast for me!

Before I could even bring up plyr as a possibility, you found the line of code that was causing the issue.

I'll reopen the issue, have my morning joe, and see about adding to that allow attribute.

Thank you for your diligence! 😊

**Comment by didrip** [comment]
I was too fast actually! The `createIframe` function that I linked is not used to generate the vimeo iframe.

This is done by plyr.js here => https://github.com/sampotts/plyr/blob/aa3378fd7303c42059728155719ff57952bb0fcc/src/js/plugins/vimeo.js#L107

You can follow the issue here => https://github.com/sampotts/plyr/issues/2151

In my opinion however this issue should stay opened until plyr.js is fixed and the plyr.js version is updated in GLightbox.

**Comment by frankie-tech** [comment]
I agree!

Again, thank you for taking the time to research all of this.

Cheers! ☕️☕️☕️

**Comment by didrip** [comment]
Working workaround until the [PR is accepted on plyr.js side](https://github.com/sampotts/plyr/pull/2152) is to used the versions I built available on https://plyr-js.netlify.app/

example:

```js
	const glightbox = GLightbox({
		selector: '.video',
		touchNavigation: true,
		loop: false,
		autoplayVideos: true,
		closeButton: true,
                plyr: {
			// both plyr CSS and JS URLs are required here otherwise "Inject videos api error"
			css: 'https://cdn.plyr.io/3.6.4/plyr.css', // default value
			js: 'https://plyr-js.netlify.app/plyr.polyfilled.min.js', // fixed polyfilled version
			ratio: '16:9', // required otherwise error split undefined
    }
	});
```

**Comment by didrip** [comment]
The PR has been merged on plyr.js side, we just need to wait for a new release now.

**Comment by dramspro** [comment]
Hi all, new version of plyr with related fixes released! https://github.com/sampotts/plyr/releases/tag/v3.6.5

**Comment by frankie-tech** [comment]
🎊 You love to see it. 🎊 

For the time being, you can of course swap it in yourself by following the instructions [here](https://github.com/biati-digital/glightbox#video-player).

Thanks for pulling this all together @didrip
