### ISSUE TITLE
Uncaught ReferenceError: GLightbox is not defined

### ISSUE THREAD

**Issue by Venegrad** [biati-digital/glightbox#224]
Not working with es modules

![image](https://user-images.githubusercontent.com/9676703/112796952-5fedf080-9073-11eb-8546-1f1c2e8fe1c1.png)

![image](https://user-images.githubusercontent.com/9676703/112796963-63817780-9073-11eb-836f-c2c2c55f03eb.png)

![image](https://user-images.githubusercontent.com/9676703/112796982-6c724900-9073-11eb-971b-038579de7891.png)

![image](https://user-images.githubusercontent.com/9676703/112797012-75fbb100-9073-11eb-8cfc-955109f32554.png)

![image](https://user-images.githubusercontent.com/9676703/112797042-801daf80-9073-11eb-8540-796681b0fcd3.png)

**Comment by Venegrad** [comment]
import GLightbox from "glightbox";

working for me, pls add it to documentation

**Comment by frankie-tech** [comment]
The syntax you've provided is how the Webpack bundler [resolves](https://webpack.js.org/configuration/resolve/) npm package paths. It is not how ES modules are imported.

I'm glad you were able to resolve the issue.
