### ISSUE TITLE
Bookmarks? Full screen? Play? Back button close gallery?

### ISSUE THREAD

**Issue by garretwilson** [biati-digital/glightbox#226]
Your main [demo page](https://biati-digital.github.io/glightbox/) looks really slick! But the actual lightbox seems to have less functionality than competitors.

* Is there a button to go into full screen mode?
* Is there an option to have the browser "back" button close the gallery but stay on the same page? This is especially crucial on the mobile.
* Is there a way to update the URL with a custom slug for bookmarkable images?

I would gladly pay for a functional lightbox. Nobody seems to have a good one with complete functionality.

**Comment by biati-digital** [comment]
Hi @garretwilson GLightbox does not include the functionalities you mention and they are not planned as of now.

There's several paid lightbox libraries you can try for example fancybox 3.
