### ISSUE TITLE
Images preview in slideshow (Feature Request)

### ISSUE THREAD

**Issue by andimg93** [biati-digital/glightbox#227]
Would be great to have a image preview via the small images/thumbnails in slideshow to quickly navigate to a specific image.
See following image gallery as example:
https://nanogallery2.nanostudio.org/#nanogallery/nanogallery/people/people%2FPhoto%20by%20Naletu

The Mosaic 1 theme of it is in general awesome, maybe it could serve as inspiration for the further design of glightbox

**Comment by frankie-tech** [comment]
Hi @andimg93 this is a great looking gallery, and a very similar suggestion to #86!

This is out of scope for GLightbox right now, but can be done using `lightboxHTML`, `slideHTML`, and some of the [events](https://github.com/biati-digital/glightbox#events) included.

You can show your support there for the time being while we continue working on v4 😊

**Comment by biati-digital** [comment]
I agree that this is very similar to #86, we'll close this and keep the other Feature Request open.
