### ISSUE TITLE
Counter - something like (1/10)

### ISSUE THREAD

**Issue by Daaarkling** [biati-digital/glightbox#228]
**Please describe the feature you want to be implemented.**
Hi,
If there is a gallery with many images it would be nice to have a counter after lightbox is opened. So that user could see how many images there are and what is current image position. So something like `(2/10)`. It could be displayed in top left corner. Hope I didn't miss anything in doc :-)

Nowdays this behaviour can be implemented with `customLightboxHTML` and event `slide_changed`. It's functional but...

**Explain why the feature is useful**
Coz it would be nice feature to have and people would not have to bother with custom templates.

**Have you seen it somewhere else?**
For instance here https://photoswipe.com/ just click on image. Counter is in top left corner.

**Comment by frankie-tech** [comment]
You're right this is possible with current APIs. #69 is the one that gets referenced most often, but that is from v2 I think (how time flies)

Since it is easy enough to roll out yourself, it is not planned on being added.
