### ISSUE TITLE
width / height settings do not work for image types

### ISSUE THREAD

**Issue by w00fz** [biati-digital/glightbox#234]
Setting custom width / height to an image type, gets ignored.  `data-width="250px"`

**To Reproduce**
1. Add an image with width setting:
   ```html
   <a href="demo/img/large/gm1.jpg" class="glightbox" data-type="image" data-width="250px">
       <img src="demo/img/small/gm1.jpg" alt="image">
   </a>
2. Click on it to open glithbox

**Expected behavior**
The image opens up with default width values and has no inline style to enforce the data-width.

**Comment by biati-digital** [comment]
Noted, the fix will be available in the next update.

**Comment by w00fz** [comment]
Awesome, thanks!  👍

**Comment by biati-digital** [comment]
Please try the latest version 3.0.9, this should be working now.

**Comment by scheibome** [comment]
With the new version it works again. Thank you.

**Comment by w00fz** [comment]
Confirming latest release works, thank you! 👍
