### ISSUE TITLE
GLightbox doesn't seem to work on dynamically set images

### ISSUE THREAD

**Issue by cocodedesigns** [biati-digital/glightbox#237]
**Describe the bug**
I cannot seem to assign GLightbox to images that are dynamically generated.  If I enter an image into my code then GLightbox will fire. If I use JavaScript to append or prepend an image to content, it will not.

**Are you able to reproduce the bug in the demo site**
No.

**To Reproduce**
1. Load GLightbox via CDN
2. Set code to generate images
3. Add GLightbox above `</body>`
4. Test 

**Expected behavior**
I expect Glightbox to fire when images are clicked.

**Post the code you are using**
Image Generation Code
`$('#photos').prepend('<a class="glightbox" style="background-image:url(\'[IMAGE URL]\');" href="'[IMAGE URL]'" data-gallery="gallery01"><span></span></a>');`

`<div id="photos"></div>`

GLightbox Code
    `const lightbox = GLightbox({ 
        autoplayVideos: true
      });`

**Desktop:**
 - OS: Windows 10 Pro
 - Browser Vivaldi
 - Version 3.8.2259.42

**Comment by frankie-tech** [comment]
Hey there @cocodedesigns,

Is your GLightbox code inside of a `$(document).ready` callback of some kind?

For example, if your code is ordered like this:

```js
const lightbox = GLightbox();

$(document).ready(() => /* prepend HTML */);
```

Then there is no guarantee that GLightbox will run when your HTML is in the DOM.

If your append code is running before GLightbox, and isn't asynchronous in any way, then you need to use a GLightbox method like `setElements` or `insertSlide`.

**Comment by frankie-tech** [comment]
Since there hasn't been a response after 7 days, I'm going to go ahead and close this issue.
