### ISSUE TITLE
When touch is activated images swipe independently of their descriptions

### ISSUE THREAD

**Issue by raphaelriehl** [biati-digital/glightbox#238]
**Describe the bug**
Hi, thank you already for this awesome library !
Unfortunately I encounter a problem: 
when i swipe image if touch device, if images have a description, image move but not their description.
Normally, it is class "ginner-container" who receive translate3d rule but when it's a touch device, this is "gslide-media" class who is targeted.

**Are you able to reproduce the bug in the demo site**
Yes.

**To Reproduce**
1. Enable touch option if you are on desktop 
2. Click on image in "Images with Description"
3. Swipe on the image to go to next image
4. Image move but not description

**Video**
https://user-images.githubusercontent.com/16758858/118811807-b7f3e700-b8ad-11eb-9695-5390ede3ae16.mp4
The first part is the normal behavior, the bug is in the second part of this video. 

**Devices and Tools:**
 - OS: Probably all
 - Browser: Chrome (mobile and desktop) and Firefox (desktop) and maybe others
 - Version: Glightbox 3.0.8

**Comment by frankie-tech** [comment]
Hey there @raphaelriehl,

Just want to double check the devices and tools section of your issue report.

If you exclude the device simulator inside of dev tools, specifically what browsers and OS are you finding this bug in.

**Comment by raphaelriehl** [comment]
Hi @frankie-tech, i encounter too this bug on my Android 11 Phone with Chrome and Firefox.

**Comment by biati-digital** [comment]
This is something that definitely needs to improve, touch events were first created for mobile devices and not desktop. On mobile the image is moved independently from the description, this is on purpose as i was trying to duplicate the way Facebook worked (at least at that time, do not use Facebook anymore)

I've applied a fix, v4 will improve this functionality. I'll submit an update this week.

https://user-images.githubusercontent.com/1219228/119060976-e69abc00-b998-11eb-9237-6d7ee198002a.mp4

**Comment by frankie-tech** [comment]
Something that was brought up in [#221](https://github.com/biati-digital/glightbox/issues/221) was taking advantage of CSS Media Queries for [Interaction Media Features](https://www.w3.org/TR/mediaqueries-4/#mf-interaction).

I'm wondering if this would be a good opportunity to explore that idea a little?

**Comment by biati-digital** [comment]
Hi @frankie-tech  That's planned for V4, CSS Interaction Media Features are not supported by IE11 so it will be difficult to include that new feature now and still support IE.

V4 will drop support for IE11 so i can finally implement some of the latest browser features without worrying about ie.

As soon as i've something more stable to share i'll let you know so we can discuss the best way to implement this and make some tests.

**Comment by raphaelriehl** [comment]
Hi @biati-digital,
thanks for this quick fix ! It's works for me.
I close this issue. Good luck for the work on V4 !
