### ISSUE TITLE
Force touchevent for desktop touch app

### ISSUE THREAD

**Issue by Chousse** [biati-digital/glightbox#239]
Hi 
I recently have a problem with your lib, works perfectly on dev environnement but when I tested on windows touchscreen in an electronapp; it doesn't work as I wish.

so I create a new setting : forceDesktopTouch:false
and I change 2625 line to : 
if (isTouch$1 && this.settings.touchNavigation || this.settings.forceDesktopTouch) {
          touchNavigation(this);
        }

**Comment by frankie-tech** [comment]
Hey there @Chousse,

Thanks for the suggestion! Fortunately, we already have `draggable` as an option.

In the future please use the issue templates provided 😊
