### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by nghiepit** [biati-digital/glightbox#242]
Hi guys,
 
Currently, this library does not provide a TypeScript Declaration file,
We need support `@types/glightbox` available on npm or local provide declaration file.

It would be nice if the `glightbox` should be rewritten in Typescript.

Tks!

**Comment by frankie-tech** [comment]
Hi @nghiepit,

While I can appreciate the enthusiasm for TypeScript, it's not in scope right now. I would suggest adding this to your projects types file:

```ts
type GLightbox =  (options: {
    [key: string]: unknown,
}) => {
    [key: string]: unknown,
}
```

Then fill in the blanks as you need to 😊

**Comment by frankie-tech** [comment]
Since this isn't a feature request or bug report, I'm going to close this issue.
