### ISSUE TITLE
Styling is missing with webpack

### ISSUE THREAD

**Issue by Wndworks** [biati-digital/glightbox#243]
I'm importing GLightbox with webpack, but somehow the css is not loading. The javascript is working tho. I don't have this problem with another plugin that i'm using. Am i missing something? 

```
import GLightbox from 'glightbox';

document.addEventListener('DOMContentLoaded', function(event) {

	const lightbox = GLightbox({
	    selector: '.glightbox',
	});
});
```

**Comment by frankie-tech** [comment]
Hey there @Wndworks,

I'm sorry, but we don't offer support for build tools. When it comes to build tools, webpack especially, there are too many variables.

I can say your `import` is correct. Maybe double check your `css-loader` config? _Thats what I had to use on v4 at least_

You should also check out the webpack tag on [StackOverflow](https://stackoverflow.com/questions/tagged/webpack).

**Comment by kaanra** [comment]
Hi @Wndworks, funny enough I just ran into your exact same question around the time you posted this topic. You can import the CSS with webpack like so:

```
import Glightbox from 'glightbox';
import 'glightbox/dist/css/glightbox.css';
```

**Comment by Wndworks** [comment]
@frankie-tech I understand, thanks anyway. 
@kaanra So it's not just me ;) Thanks for the solution!
