### ISSUE TITLE
Autoplay slideshow

### ISSUE THREAD

**Issue by johanmolen** [biati-digital/glightbox#244]
Hi guys!

What a wonderful package this is 👍 

I got one minor question is it possible to autoplay the gallery? (so going to the next image after X seconds)

Thanks in advance.

**Comment by frankie-tech** [comment]
Hey @johanmolen,

It's not built into GLightbox, but it wouldn't be hard to roll something out yourself.

GLightbox already exposes all the methods/events you would need. The `.nextSlide()` method and the `open`/`close` events should be all you need from GLightbox.

We're not planning on adding new features right now. I'll close this issue for now.
