### ISSUE TITLE
Image Zoom Does Not Seem to Work…

### ISSUE THREAD

**Issue by warling** [biati-digital/glightbox#245]
I've attached an absolutely minimal HTML document. If I understand GLightbox correctly, the linked image *should* open in a lightbox, the linked image should roughly fit the screen size, I should be able to zoom the image, and pan around the image with the mouse. Instead, my image opens in a small lightbox, and I can scroll up/down/left/right, but there is no zoom option and no pan option. Am I missing or misunderstanding something, or is there a bug in the library?

[lightbox-test.html.txt](https://github.com/biati-digital/glightbox/files/6557470/lightbox-test.html.txt)

**Comment by frankie-tech** [comment]
Hi @warling,

It sounds like your issues with zoom may be related to #223.

As this isn't a feature request or a bug report, I'm going to close this issue. See our support guidelines [here](https://github.com/biati-digital/glightbox#support).
