### ISSUE TITLE
Serve Responsive Images

### ISSUE THREAD

**Issue by iamrobert** [biati-digital/glightbox#248]
Is it possible to serve responsive images based on media size? 

So - if using mobile then we can serve a small image, and desktop the full-size image etc.

Light Gallery.JS does it like this:
 
```
<a href="large.jpg" data-responsive="small.jpg 640, medium.jpg 800">
        <img src="thumbnail.jpg" />
</a>
```
https://www.lightgalleryjs.com/demos/responsive/

The benefits are:
- Improves Load Speed
- Saves Mobile data

In the meantime, I guess I can serve a different <a href> based on screen size.

`<a href="large.jpg" class="show-for-large">`

**Comment by frankie-tech** [comment]
Hey @iamrobert,

That's a great idea, definitely a candidate for a either a plugin or new feature in the next version.

There is a way I can think of to do it right now, if you absolutely need a solution.

You can do something similar to #247 and set the elements ahead of time using the content field.

**Comment by amkdev** [comment]
support for img tag's srcset or a solution via a data attribute is really a must. I would really appreciate that too.

**Comment by frankie-tech** [comment]
Adding support for srcset attribute, or maybe like a `data-glightbox-srcset` config option, wouldn't be impossible to implement.

If you're comfortable using a 100% **untested**, **unsupported**, **unofficial**, **not-guaranteed-to-ever-be-looked-at-again** attempt at adding it, you can try [this](https://github.com/frankie-tech/glightbox/tree/propagate-srcset-attribute) which I pulled together real quick 😊

**Comment by amkdev** [comment]
Looks not too bad, Frankie. ;) I like it ... works for me so far. will test it a bit further.

**Comment by amkdev** [comment]
I found out that with the srcset-attribute it is mandatory to specify the size-attribute as well. Otherwise, the zoom functionality will output wrong values or better: the zoomed image will shown over it’s „natural“ size.

I implemented the size-attribute for testing by myself. now the zoom functionality works like on the none responsive glightbox-version.

Beside this, I found out, that the zoomed view is not 100% the pixel size of the image - 16/12 (w/h) pixels too less. weird. I will try to find out why.

**Comment by frankie-tech** [comment]
I'm just reading this in passing so excuse any formatting issues, but it sounds like just need to add this

```js
if (!isNil(data.srcset) && data.srcset !== '') {
    img.setAttribute('srcset', data.srcset);
    // add me!
    img.setAttribute('sizes', data.sizes);
}
```

Then add that to the data/settings object wherever I added the srcset to the data/settings that, right?

If that's the case, I'll just add that real quick, haha

**Comment by amkdev** [comment]
Yes, well ... i checked the code and everywhere I found something with srcset I added the same for the size attribute. :)

**Comment by frankie-tech** [comment]
With #264 being merged, I'm gonna go ahead and close this.

Thank you for the feature request @iamrobert, and for the help pseudo-coding @amkdev 😊
