### ISSUE TITLE
image alt attribute propagation to the lighbox interface

### ISSUE THREAD

**Issue by PiemP** [biati-digital/glightbox#252]
I have see the issue #118. About the possibilities to propagate the alt attribute of the image elements to the images in the glightbox interface, could have sense?

It's a request of a client. I have see other lightbox system that do the same like this one https://codyhouse.co/ds/components/app/lightbox .

Thank you.

**Comment by frankie-tech** [comment]
Hey there @PiemP,

You raise an excellent point!

I don't think this would be that hard to add in. *I think it's really only one line, but I'd need to test it.*

If you want to take a crack at it, feel free to make a PR! Otherwise it's on the to-do list 😊

**Comment by PiemP** [comment]
I have already modified the code on my local installation. Give me the weekend free and next monday I can prepare a PR about It. 😉

Conribution giude, I'm coming!
