### ISSUE TITLE
Image with query parameters

### ISSUE THREAD

**Issue by viliusle** [biati-digital/glightbox#254]
**Describe the bug**
If image has query parameter, like example.png?v=55, it will be seen as type = "external" by library. It should be seen as "image" type. 
Most of features still works, but there will be some weird things visible like scroll bars or right padding with white background.

**Are you able to reproduce the bug in the demo site**
Yes, if I download it locally, edit image source to "...?v=555"

**To Reproduce**
1. Open any example
2. modify image source that it has version, like example.jpg?v=77 or example.jpg?88 or even example.jpg?
2. Click on it
3. See weird things, mentioned above.

**Expected behavior**
image should be opened without any scroll bars or paddings.

**Desktop:**
 - Browser [chrome]

p.s. library is amazing, keep on supporting it.

**Comment by frankie-tech** [comment]
Hey there @viliusle,

Thanks for posting this issue! You're right it looks like the SlideConfigParser uses a regex to look for image file types that doesn't take into account URL params.

```js
if (url.match(/\.(jpeg|jpg|jpe|gif|png|apn|webp|svg)$/) !== null) {
    return 'image';
}
```

Is this fixed by using the `data-type` feature to coerce the slide into being an image? So add `data-type="image"`

**Comment by viliusle** [comment]
>Is this fixed by using the data-type feature to coerce the slide into being an image? So add data-type="image"

Yes, it is. But still it would be good to fix it in library. It is not a problem on small sites, but can be issue on bigger sites.

**Comment by frankie-tech** [comment]
> But still it would be good to fix it in library. 

I completely agree! We're in the middle of upgrading to the next major version, so a patch for this might be unlikely.

Of course, you're more than welcome to take a crack at it and make a PR 😊

**Comment by viliusle** [comment]
>Next major version

That's good, any ETA, info about new version? 
I can make PR, but if next version will come soon, I should wait too.

**Comment by frankie-tech** [comment]
I think it's safe to make a PR. It may be a little while before the next major version comes out.

Both the maintainer and I are swamped at our respective jobs, so for now I have mainly been keeping track of feature requests and possible enhancements.

**Comment by biati-digital** [comment]
The latest version 3.1.0 supports query parameters
