### ISSUE TITLE
grouping improvements

### ISSUE THREAD

**Issue by viliusle** [biati-digital/glightbox#256]
**Please describe the feature you want to be implemented.**
Allow to disable grouping using config or data attribute. I found only 1 [solution](https://github.com/biati-digital/glightbox/issues/64#issuecomment-742133641) how to avoid it: using extra code with querySelectorAll and click event, but this adds more code. For some type grouping makes little sense, like videos, inline HTML, iframes. 

**Explain why the feature is useful**
Inline, iframe, video types. Also sometimes you want easy way to have 2 or even more galleries in same page without writing lots of extra JS.

**Have you seen it somewhere else?**
Other libraries usually allows to set unique group like "group2" and disables grouping for some types automatically (inline, iframe, video).

**Comment by frankie-tech** [comment]
Hey @viliusle,

I think what you're looking for is actually [this](https://github.com/biati-digital/glightbox/issues/64#issuecomment-531381796) and using the `data-gallery` option.

Clicking on an item with that attribute will open up a lightbox with only items that also have that `data-gallery` value.

**Comment by viliusle** [comment]
1. You should improve documentation on README.md. Right now it is difficult to find out that you can use data-gallery to disable grouping. You can use words "group" or "grouping", so user will be able to find this info sooner.
2. Videos, inline elements and iframes types should not be grouped by default. Most of other similar libs already does this without any extra configuration. If in rare cases, developer needs it, it should be able to provide data-gallery and get grouping.  p.s. grouping inline alone is very strange.

**Comment by frankie-tech** [comment]
1. The documentation is in the middle of being improved. Obviously that is no easy task.

2. GLightbox is not a kitchen sink package. Part of why GLightbox is so useful is that it is malleable and has options. There are plenty of libraries out there that will do everything for you, if you prefer.

3. You can have multiple GLightbox galleries if you're only using things like `setElement`, if you look at the demo page and the JS there, you should get the idea.

**Comment by hasenov** [comment]
Hi, I had same issue, what I did is really simple but it works. All you need to do is add custom skin, disable dragging and all the navigations.
`const lightboxModal = GLightbox({
		selector: ".glightbox-modal",
		width: "auto",
		height: "auto",
		closeButton: false,
		skin: "modal-inline",
		draggable: false,
		keyboardNavigation: false,
		touchNavigation: false,
	});`
