### ISSUE TITLE
Image description/shadow off

### ISSUE THREAD

**Issue by sal0max** [biati-digital/glightbox#268]
**Describe the bug**
Image descriptions and its shadow are off by 15px, resulting in a brighter area below it.

**Are you able to reproduce the bug in the demo site**
Yes

**To Reproduce**
1. Open an image with an image description on a mobile device (e. g. with Android user agent)
2. To better see the issue, turn it into landscape orientation
3. See the light area at the bottom, below the descripton

**Code to solve this issue**
**The bug seems to be solvable by changing https://github.com/biati-digital/glightbox/blob/master/src/postcss/glightbox.css#L333 to `bottom: 0px`**

**Screenshots**
![Bildschirmfoto am 2021-07-17 um 01 36 58](https://user-images.githubusercontent.com/423373/126017954-9ab5438c-8a26-4eec-aa14-e74720cd166f.png)

**Desktop:**
No issue here

**Smartphone:**
All devices where [`isMobile()`](https://github.com/biati-digital/glightbox/blob/e5d809b5d6a699832eddbe39db665c0f5e590e24/dist/js/glightbox.js#L476) returns `true`.

**Comment by frankie-tech** [comment]
Hey there @sal0max,

Thanks for filing this issue!

I can confirm this is happening on my iPhone 12 as well. 

I'll add this as a bug and good first issue.

**Comment by clemensg** [comment]
Hi @biati-digital , Hi @frankie-tech , first of all thank you for this awesome lightbox library.

Any ideas how to proceed regarding this issue?

Until we have a good solution (making space for the description text below the image), should we maybe add a workaround that hides it in landscape orientations?

**Comment by frankie-tech** [comment]
@clemensg currently both I and the package maintainer are both busy at our own jobs.

You're more than welcome to make a PR yourself though.

**Comment by biati-digital** [comment]
This is fixed in the latest version 3.1.0
