### ISSUE TITLE
Double `px` value in inline CSS on video description

### ISSUE THREAD

**Issue by joergsteinhauer** [biati-digital/glightbox#273]
**Describe the bug**
The video description element has double `px` values on its `max-width` inline CSS style.

**Are you able to reproduce the bug in the demo site**
No

**To Reproduce**
1. Use a simple video GLightbox with `title` attributes on the trigger element
2. Click on the trigger element
3. When the GLightbox layer appears, the description part is as wide as the viewport, because the inline css style contains `...pxpx`

**Expected behavior**
The CSS style contains a valid CSS value (single `px`)

**Screenshots**

![image](https://user-images.githubusercontent.com/1843754/127472327-49ce2dcc-b8f4-4ed2-99c7-82da20c15038.png)

![image](https://user-images.githubusercontent.com/1843754/127472408-abe48f7e-a385-4c91-b9c2-eceda6fc5d17.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version:  92.0.4515.107

----------------------

Maybe related to https://github.com/biati-digital/glightbox/pull/229

**Comment by biati-digital** [comment]
Hi @joergsteinhauer  Are you using the latest version?

**Comment by joergsteinhauer** [comment]
> Hi @joergsteinhauer Are you using the latest version?

Ah, good point - indeed I use 2.0.5... so maybe its just outdated. Let me check it, maybe the problem is solved then for me.
