### ISSUE TITLE
Creating a tutorial for using lightboxes without plugins in WordPress (Gutenberg)

### ISSUE THREAD

**Issue by paaljoachim** [biati-digital/glightbox#274]
**Please describe the feature you want to be implemented.**

Some help getting this to work with WordPress - Gutenberg.

**Explain why the feature is useful**

Because I am updating this tutorial: https://www.easywebdesigntutorials.com/adding-a-lightbox-to-wordpress-without-using-a-plugin/ 
and your lightbox will be shown to a lot of people.

**Additional context**

I tried this approach:
Added glightbox.min.css, glightbox.min.js and glightbox-init.js  to a folder I called glightbox. I placed the glightbox folder into the root of the current theme I am testing this with. 

In the functions.php file I added:

```
/* Enqueue glightbox */
add_action( 'wp_enqueue_scripts', 'enqueue_glightbox' );
function enqueue_glightbox() {
 wp_enqueue_style( 'glightbox-css', get_template_directory_uri(). '/glightbox/glightbox.min.css' );
 wp_enqueue_script( 'glightbox',get_template_directory_uri() . '/glightbox/glightbox.min', array( 'jquery' ), '', true );
 wp_enqueue_script( 'glightbox-init', get_template_directory_uri() . '/glightbox/glightbox-init', array( 'glightbox' ), '', true ); 
}
```

In the glightbox-init.js file I added the following spaghetti kode. It is using some code from colorbox along with the selector for glightbox. I assume this will need to be adjusted. The plan is to use this for gallery and images and possibly also video.

```
/* Initialize jQuery uses the Colorbox code for GLightbox*/
jQuery(function( $ ){
 $('a[href*=".jpg"], a[href*=".jpeg"], a[href*=".png"], a[href*=".gif"]').colorbox({
    'selector': 'glightbox'
    });
});
```

Some advice on getting this to work would be very helpful!

Thanks!

**Comment by frankie-tech** [comment]
Hey there @paaljoachim,

Look through the documentation we have written up and you should have a better idea of where your code isn't working. We don't offer support for set up or troubleshooting, you can read more [here](https://github.com/biati-digital/glightbox#support). 

If you are still having a hard time, I would ask this question in StackOverflow with a WordPress and Javascript tag, you will be able to get more help there.

Closing due to being an unsupported issue topic.

**Comment by paaljoachim** [comment]
Thanks for the response @frankie-tech !

I am working on figuring out the correct code to use in a init.js file (or a php file that is).
As the readme is not clear enough for me in how to setup a separate init js file.
I will slowly get there, and when I do get it working then I plan on updating this issue for others who might happen to do a search for getting this working in WordPress.

Have a great day!
Thanks for creating a really nice looking lightbox!

**Comment by paaljoachim** [comment]
Here is a working glightbox code.
https://easywebdesigntutorials.com/adding-a-lightbox-to-wordpress-without-using-a-plugin/

I am using a basic init js file.

**Comment by gingerchew** [comment]
Awesome! Thanks for coming back and sharing :)

**Comment by vuduproject** [comment]
Sorry but to increment data-description?
