### ISSUE TITLE
Close Button unreachable via keyboard navigation on last slide

### ISSUE THREAD

**Issue by fcjm** [biati-digital/glightbox#282]
**Describe the bug**
When on the last slide of a slideshow, the "close"-button is unreachable via Tab-navigation.

**Are you able to reproduce the bug in the demo site**
Yes

**To Reproduce**
1. Go to https://biati-digital.github.io/glightbox/#examples
2. Click on the first Image Slideshow
3. Navigate through all the slides 
4. On the last slide the "Close"-Button is unreachable

**Expected behavior**
"Close"-Button should be reachable

**Comment by biati-digital** [comment]
Good catch and the code you mention it's exactly where the error is found,  it would be great if you create a PR.
