### ISSUE TITLE
YouTube video playback does not show the suggested links 

### ISSUE THREAD

**Issue by BTPDarren** [biati-digital/glightbox#287]
We have had a new site built and the developers have used this feature to playback a video embedded in our site

The video when viewed on YouTube directly shows a suggested link in top right at a given time but when played back using this it does not

Is there a setting I can tweak for this?

**Comment by biati-digital** [comment]
Hi. Everything related to the Player options or configuration should be posted on the [Plyr repository](https://github.com/sampotts/plyr), make sure to first read the README.
