### ISSUE TITLE
Video Lags on live server!

### ISSUE THREAD

**Issue by LogikaServices7** [biati-digital/glightbox#290]
![lightboxjavascript](https://user-images.githubusercontent.com/64137932/133913160-58506f10-a973-49fb-84b0-31ca8b50d4c9.jpg)
Hello! I'm using your video service and it works perfect on the localhost, but when the site goes live, the video can barely play more than 10 seconds without buffering. Any suggestions? Thank you!

**Comment by biati-digital** [comment]
Closing as this has nothing to do with the library or the player.
