### ISSUE TITLE
Custom lightbox not working

### ISSUE THREAD

**Issue by HightowerPL** [biati-digital/glightbox#292]
According to documentation lightbox structure can be easily changed using lightboxHTML option. However whenever I try to change it it still shows up a basic version. 

I am adding a sample "CUSTOM LIGHTBOX" text at top of it and it doesn't show up. 

const customLightboxHTML = `<div id="glightbox-body" class="glightbox-container customGLightbox">
    <div >CUSTOM LIGHTBOX</div>
    <div class="gloader visible"></div>
    <div class="goverlay"></div>
    <div class="gcontainer">
    <div id="glightbox-slider" class="gslider"></div>
    <button class="gnext gbtn" tabindex="0" aria-label="Next" data-customattribute="example">{nextSVG}</button>
    <button class="gprev gbtn" tabindex="1" aria-label="Previous">{prevSVG}</button>
    <button class="gclose gbtn" tabindex="2" aria-label="Close">{closeSVG}</button>
</div>
</div>`;

const popup = () => new GLightbox({
  lightboxHTML: customLightboxHTML,
  selector: 'js-popup',
  elements: null,
  closeButton: true,
  startAt: null,
  autoplayVideos: true,
  descPosition: 'bottom',
  width: 900,
  height: 506,
  videosWidth: 960,
  beforeSlideChange: null,
  afterSlideChange: null,
  beforeSlideLoad: null,
  afterSlideLoad: null,
  onOpen: null,
  onClose: null,
  loop: false,
  touchNavigation: true,
  touchFollowAxis: true,
  keyboardNavigation: true,
  closeOnOutsideClick: true,
  plyr: {
    css: 'https://cdn.plyr.io/3.5.6/plyr.css',
    js: 'https://cdn.plyr.io/3.5.6/plyr.js',
    ratio: '16:9', // or '4:3'
    controls: false,
    config: {
      youtube: {
        noCookie: false,
        rel: 0,
        showinfo: 0,
        iv_load_policy: 3,
        controls: 10,
      },
      vimeo: {
        byline: false,
        portrait: false,
        title: false,
        transparent: false,
      },
    },
  },
});

I would appreciate any help in this matter.

**Comment by frankie-tech** [comment]
Hey there @HightowerPL,

I'm sorry but we don't offer technical support, you can see our statement [here](https://github.com/biati-digital/glightbox#support).

I also recommend looking at previous issues, you may find your answer there.

Going to close since issue is requesting technical support.
