### ISSUE TITLE
String selector in CSS flags as issue in our sonarqube.org scans

### ISSUE THREAD

**Issue by markkes** [biati-digital/glightbox#293]
**Describe the bug**
String selector in CSS flags as issue in our sonarqube.org scans. Its the ".glightbox-mobile .glightbox-container .gslide-desc string" selector in the provided css file.

**Screenshots**
![Screenshot 2021-10-05 at 10 32 15](https://user-images.githubusercontent.com/1958786/135988851-821d6aed-c0c2-4583-8435-f4ad0dc769e2.jpg)

Could you explain/look in to this selector. I cant find a reason where this selector is needed since i cant find this html element in the code so i dont know why/where its used. If it is used can you rewrite it to a class?

**Comment by frankie-tech** [comment]
Hey @markkes,

You are right, there is a weird selector in our src file. I'm not sure why that is in there.

Just for our own notes it's on line 363 of the src css file.

I'm sure it can just be removed, I just don't have time to test it right now.

Thanks for spotting that and letting us know!

**Comment by markkes** [comment]
@frankie-tech Awesome, thanks for the quick reply. There are also multiple duplicate properties in the css that flag in sonarqube. Examples are:

- overflow in selector glightbox-container on line 6
- opacity in selecter on line 46
- margin in selector img on line 145
- display in selector &::before on line 207
- background in selector gslide-description on line 332

**Comment by biati-digital** [comment]
This should be fixed in 3.2.0
