### ISSUE TITLE
HTML lightboxes not positioned in center on tablets

### ISSUE THREAD

**Issue by ninetyninew** [biati-digital/glightbox#295]
**Describe the bug**
When using a tablet and trying to display a HTML lightbox the lightbox is not centered.

**Are you able to reproduce the bug in the demo site**
Yes

**To Reproduce**
1. Turn on chrome debugger responsive and select iPad
2. Go to https://biati-digital.github.io/glightbox/#examples
3. Click the first image under "Iframes and Inline Elements" heading (woman looking off to right with sky background)
4. See that lightbox is not centered

**Expected behavior**
Lightbox is centered for tablets, same as other views

**Post the code you are using**
None - demo site

**Screenshots**
![image](https://user-images.githubusercontent.com/56840277/137630983-e477c30b-e9c4-4c47-8a3c-844e00480ccc.png)

**Device:**
 - Device: iPad
 - OS: Version included with Chrome Debugger

**Comment by biati-digital** [comment]
This should be fixed in 3.2.0

**Comment by ninetyninew** [comment]
@biati-digital just a note here, that this appears to be fixed now when testing on an iPad, however if we test on an iPad mini its off center and you cannot see the arrows.
