### ISSUE TITLE
YouTube video button not clickable on iOS

### ISSUE THREAD

**Issue by bloomdigital** [biati-digital/glightbox#298]
**Describe the bug**
When trying to play YouTube videos on mobile (iOS Safari), the player button is replaced with the YouTube player button and becomes un-clickable. The only way to play the video is to click the pause button in the player controls which switches the player button to the GLightbox button which can then be pressed to play. Works fine on desktop.

**Are you able to reproduce the bug in the demo site**
Yes

**To Reproduce**
1. Click on button to open lightbox with YouTube link
2. Player appears and replaces play button with YouTube play button 
3. Press pause button to make GLightbox player button appear
4. Video now plays when pressed

**Expected behavior**
Expect GLightbox player button to be visible when the lightbox opens which can the be clicked

**Post the code you are using**
HTML
`<a href="https://www.youtube.com/watch?v=oXAcFnwyfpI" class="lightbox-video card-video__link">
<img src="{{root}}assets/img/thumb.jpg" alt="" loading="lazy">
</a>`

JS
`const lightboxVideo = GLightbox({
        selector: '.lightbox-video',
        touchNavigation: true,
	    loop: true,
	    skin: 'newlane'
    });`

**Screenshots**
When lightbox appears:
<img width="534" alt="Screenshot 2021-11-05 at 13 20 13" src="https://user-images.githubusercontent.com/3763251/140517742-fc331626-07e5-4428-a568-7f27d9e348e7.png">

When pressing pause button:
<img width="546" alt="Screenshot 2021-11-05 at 13 22 28" src="https://user-images.githubusercontent.com/3763251/140517770-56b01922-2111-4471-9086-ad3e90eea5bc.png">

Replicated on demo site:
![52074059-5835-49F1-9B7B-06FFFFE12100](https://user-images.githubusercontent.com/3763251/140582589-dc8d0e0b-bcb5-47e4-9bbe-6ab3c5e8afe4.jpeg)

**Smartphone:**
 - Device:  iPhone8, iPhone 12
 - OS:  iOS14.1, iOS 14.8
 - Browser : Safari

**Comment by biati-digital** [comment]
There's a youtube example in the demo site, in the videos section (second video), make sure you can replicate it in the demo and post a screenshot.

**Comment by bloomdigital** [comment]
> There's a youtube example in the demo site, in the videos section (second video), make sure you can replicate it in the demo and post a screenshot.

Apologies didn't see that, thanks. The same thing happens on the demo site so I have updated the issue.

**Comment by konradnetdreams** [comment]
> There's a youtube example in the demo site, in the videos section (second video), make sure you can replicate it in the demo and post a screenshot.

Yes, i confirm, YT video is not working on your site. Button is not clickable. Thank you for grat plugin, i hope i will be able to use it a lot as it's all i needed, good  job ! But without YT it's a huge problem.

**Comment by kodyxgen** [comment]
Hi,
I am facing the same problem, did you maybe found a fix for the problem ? 

Thank you!

**Comment by bloomdigital** [comment]
> 

Hi. Unfortunately not.

**Comment by Droppix** [comment]
same pb!
ios v15

**Comment by iamrobert** [comment]
Hi,

We made the following demo that seems to be working (glightbox #3):
https://taichungdesigner.com/video/2/index2.html

We are using the latest plyr code (v3.6.12)

We added the following css:

```
.plyr__poster{
 z-index: -500000 !important;
}
```

Glightbox setup. If you set muted to true it allows autoplay on iOS. 

```
        //DEFAULT LIGHTBOX
        var lightbox = GLightbox({
          touchNavigation: true,
          loop: true,
          autoplayVideos: true,
          width: '90vw',
          height: '90vh',
          videosWidth: '100vw',
          plyr: {
            css: 'css/plyr/plyr.css',
            js: 'js/vendor/plyr.js',
            config: {
              // muted: true,
              fullscreen: {
                enabled: true,
                fallback: true,
                iosNative: true
              },
              youtube: {
                //SEE YOUTUBE API: https://developers.google.com/youtube/player_parameters#Parameters
                origin: window.location.host + '/',
                iv_load_policy: 3,
                modestbranding: 1,
                playsinline: 1,
                showinfo: 0,
                rel: 0,
                enablejsapi: 1,
                noCookie: true,
              },
            }
          }
        });
```

**Comment by biati-digital** [comment]
This is not related to GLighbox, basically if you set autoplay to true, Plyr will try to play the video but if the browser does not allow it, the player becomes unusable.

Autoplay is only supported if the video either has no audio tracks or has the muted attribute on a mobile device (rightfully so, as most of the time it's a pain in the arse). This isn't something that the player can control but is a browser decision.

You can disable autoplay in mobile devices or as @iamrobert mentions, set muted to true.
