### ISSUE TITLE
Links and HTML stripped from custom description on mobile / can't add Download image link.

### ISSUE THREAD

**Issue by aspyct** [biati-digital/glightbox#299]
**Describe the bug**
Base problem: I need to add a "Download image" link somewhere on the slides. This would all disappear if I had a download icon somewhere on the screen :)

I tried adding the link in a description, either via the standard description, or with a custom description `<div>`.
```
<a href="pictures/fullsize/image_1.jpg" class="glightbox" data-description="<a href='http://www.mywebsite.com'>Link</a>"> 
    <img src="pictures/thumbnails/image_1.jpg">
</a>
```

It works perfectly fine on desktop, but it doesn't on mobile. It seems like all HTML tags are stripped.

**Are you able to reproduce the bug in the demo site**
Well, maybe. The demo site has a much longer description content and shows a "See more" link. But then it shows the links.

**To Reproduce**
Use the example code below.
Open it on a desktop browser. Click on the image and see the link appear below it.
Then open it on a mobile browser (or start the dev tools and refresh the window). The link is no longer usable. Inspection shows that the link doesn't even exist, only the text was kept.

**Expected behavior**
I should be able to click the link and add images, even on mobile.

**Post the code you are using**
```
<!DOCTYPE html>
<html lang="en-US">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>GLightbox Link in description bug demo</title>
  <link type="text/css" rel="stylesheet" href="files/css/glightbox.min.css" />
</head>
<body>
	<a href="image.jpg" class="glightbox" data-description="<a href='http://www.mywebsite.com'>Link</a>">
		<img src="pictures/thumbnails/image.jpg">
	</a>
	<script src="files/js/glightbox.min.js"></script>
	<script type="text/javascript">
		const lightbox = GLightbox({});
	</script>
</body>
</html>
```

**Desktop:**
 - OS: Windows 10
 - Browser: Edge
 - Version: 95.0.1020.53 (latest at the time of bug report)

**Smartphone:**
 - Device: Samsung S21
 - OS: Android 11
 - Browser: Samsung Internet Browser
 - Version: 15.0.6.3 (latest at the time of bug report)

**Comment by frankie-tech** [comment]
@aspyct You need give a code example.

**Comment by aspyct** [comment]
@frankie-tech There is a full html page example in my submission. Isn't that enough?

**Comment by frankie-tech** [comment]
Sorry, none of that showed up when I was looking at it on the mobile app. My bad.

Looking at the code a bit more it looks like description code is stripped more on mobile using the `slideShortDesc` method [here](https://github.com/biati-digital/glightbox/blob/master/src/js/core/slide.js#L158).

The [setting](https://github.com/biati-digital/glightbox#lightbox-options) you're looking for is `moreLength`. If the `moreLength` setting is more than 0, then the slide description on mobile will be stripped of HTML. By default `moreLength` is set to 60. If the text is longer than `moreLength`, then a "see more" link will be added. Inside of there will be the HTML, like the `<a>` tag in your description. If it is shorter, like how your's is just "Link", then no "see more" link is added, and it is just text.

The solution is to set `moreLength` to 0. The warning being if you later want to change your description to be the entire text of [Remembrance of Things Past](https://themillions.com/2007/09/world-longest-novel.html), the "see more" link will not be generated.

**Comment by frankie-tech** [comment]
Here's a crude working example: https://codepen.io/gingerchew/pen/1a9fa39380883be7bb70145d8f5bdad5

**Comment by aspyct** [comment]
> Sorry, none of that showed up in the mobile app, my bad.
Ahah, responsive design strikes again :)

Brilliant solution, I absolutely missed it. Thank you very much!
