### ISSUE TITLE
Inline Image Modal are not seen by Search Engines?

### ISSUE THREAD

**Issue by carstengrimm** [biati-digital/glightbox#300]
I am basically using glightbox to inline load hidden images (like mostly described in the demo/docs) whereas the data link with glightbox class reveals the hidden div into the modal window. Which works flawless from the user perspective.

```
<div class="text-center">
    <a href="#workshop-aufnahmen-vom-opel-zoo-modal" class="glightbox px-4 py-2 bg-primary-500 hover:bg-primary-700 text-white rounded" data-height="70vh">
        Workshop Aufnahmen ansehen    </a>
</div>

<div id="workshop-aufnahmen-vom-opel-zoo-modal" class="p-0" style="display: none; padding: 0;">
  <img ....>
  <img ....>
  <img ....>
  <img ....>
  <img ....>
</div>
```

However, it seems as if the images from there are not being picked up from Google image search, at least I can't find it with exact descriptions and stuff.

I am also providing a sitemap where the images are listed so google should be aware that those exist, but maybe they are not discoverable for Google (e.g., not seen on the website).

**Comment by frankie-tech** [comment]
Hey there @carstengrimm,

Sorry, but this sounds like an issue with Google SEO and how the SEO Bot finds content. That's outside of our control, so there's not anything we can help with.

Closing due to being outside of support scope.
