### ISSUE TITLE
Remove slide navigation

### ISSUE THREAD

**Issue by gregoirenoyelle** [biati-digital/glightbox#301]
Hi,

Thanks a lot for your tools. The effects and API are great. I just made a donation :)

Is-there a way to remove the navigation?
Sometime, on a grid of content (vidéo), I don't want to have the arrow or navigation. 

Cheers,
Grégoire

**Comment by frankie-tech** [comment]
Hey there @gregoirenoyelle,

Thanks for the support! I mentioned this in a previous issue #250, there isn't a setting that you're missing. It is a customization that can be done through CSS, so classes have been added to make that easier.

Hope that helps!

**Comment by gregoirenoyelle** [comment]
Hey @frankie-tech 
Ok, thanks a lot ! That’s helps. 
Cheers
