### ISSUE TITLE
Parsing error for Vimeo urls with 2 ids

### ISSUE THREAD

**Issue by charroma** [biati-digital/glightbox#304]
There is a bad parsing of the video ID for special vimeo url with 2 ids.
ex: https://vimeo.com/647464000/8d6b63c6b5

For these videos, the iframe url should have the ids the following way:
https://player.vimeo.com/video/647464000?...&h=8d6b63c6b5
for now it's:
https://player.vimeo.com/video/8?...

For now I have to use "slide_after_load" to replace the fix the iframe url.

**Comment by frankie-tech** [comment]
Hey there @charroma,

Please use the provided templates when filing a bug report.

**Comment by charroma** [comment]
**Describe the bug**
There is a bad parsing of the video ID for special vimeo url with 2 ids.
ex: https://vimeo.com/647464000/8d6b63c6b5

For these videos, the iframe url should have the ids the following way:
https://player.vimeo.com/video/647464000?...&h=8d6b63c6b5
for now it's:
https://player.vimeo.com/video/8?...

**To Reproduce**
Steps to reproduce the behavior:
1. Use a vimeo url in the following format as an href.
2. ex: https://vimeo.com/647464000/8d6b63c6b5

**Expected behavior**
Load correct video ID based on the url

**Post the code you are using**
```
<a href="https://vimeo.com/647464000/8d6b63c6b5" class="vimeo">video</a>
<script>
const lightbox = GLightbox({selector : '.vimeo'});
</script>
```

**Desktop:**
 - OS: MacOSX 11.6
 - Browser Firefox, Safari, Chrome
 - Latest version

**Comment by biati-digital** [comment]
Hi @charroma, you need to open this issue in the Plyr repository, even if we pass your full url to Plyr, the generated iframe has the src attribute like `https://player.vimeo.com/video/647464000?loop=false&autoplay=false&muted=false` and as a result you'll see a "This video does not exist" error.

**Comment by natebeaty** [comment]
Fwiw, I still had this same issue years later, and here's the code I used in `slide_after_load` to fix the issue (borrowing regex from [an unmerged commit in plyr](https://github.com/sampotts/plyr/pull/2505/files/1c62f306246dcec825527b2f01002587996596f5) that should fix this eventually?) in case anyone else lands here:

```
    lightbox.on('slide_after_load', (data) => {
      // Check for hash in Vimeo URL (unlisted video)
      const regex = /^(.*vimeo.com\/|.*video\/)?(\d+)(\?.*&*h=|\/)+([\d,a-f]+)/;
      const found = data.slideConfig.href.match(regex);
      if (found) {
        // If hash is found, append it to the iframe src
        const iframe = data.slideNode.querySelector('iframe');
        iframe.src = iframe.src + '&h=' + found[found.length - 1];
      }
    });
```
