### ISSUE TITLE
Cannot use URLs with anchor hash/tag

### ISSUE THREAD

**Issue by dorneanu** [biati-digital/glightbox#305]
**Describe the bug**
I'd like to use the inline feature to load an URL like this: 

```
                            <li class="box">
                                <div class="inner">
                                    <a
                                        href="https://brainfck.org/#Serverless"
                                        class="glightbox4"
                                    >
                                        <p>Click me</p>
                                    </a>
                                </div>
                            </li>
```
However this doesn't work at all. I also tried to encode the "#" sign and used `https://brainfck.org/%23Serverless` but this didn't work as well. 

**Are you able to reproduce the bug in the demo site**
Yes

**To Reproduce**

- Clone the github repository
- Edit `index.html` by replacing in [line 271](https://github.com/biati-digital/glightbox/blob/master/index.html#L271) google maps URL with `https://brainfck.org/#Serverless` (or `https://blog.dornea.nu/2021/09/01/inbox-zero-using-getpocket/#buckets`)
- Save the file
- Open your browser and open `index.html` 
- Click on the picture (that was previously related to the Google maps URL)
- A new window is opened however no content is loaded

**Expected behavior**
I would expect the content of `https://brainfck.org/#Serverless` (or any other URLs including the hash sign) to load proplery. 

**Post the code you are using**

```
                            <li class="box">
                                <div class="inner">
                                    <a
                                        href="https://blog.dornea.nu/2021/09/15/bye-bye-scout24/%23thanks-to"
                                        class="glightbox4"
                                    >
                                        <p>Click me</p>
                                    </a>
                                </div>
                            </li>

```

**Screenshots**

![image](https://user-images.githubusercontent.com/3818045/145368705-3434db7f-41aa-435b-875f-1c7470d1604a.png)

![image](https://user-images.githubusercontent.com/3818045/145368753-f6228270-2dee-4e9a-b97e-2c0c8f3e95f0.png)

**Desktop:**
 - OS: Linux
 - Browser: Google Chrome
 - Version: 94.0.4606.71 (Official Build) (64-bit)

**Smartphone:**

**Comment by biati-digital** [comment]
It does not work like that, the inline slide will only check the content of the same page, it will not load the content from an external page.

This will be included in a future version.

**Comment by dorneanu** [comment]
Maybe I'm using it in the wrong way. If you say the "in-line slide will only check the content of the same page", how comes you have an example on the demo page where you load content from an external URL?

Thanks for clarification.

**Comment by biati-digital** [comment]
The entire page (the url you enter) is loaded with an iframe.

**Comment by dorneanu** [comment]
Okay, got that. And why is it not possible to load an URL (containing a hash sign) within an iframe?

**Comment by biati-digital** [comment]
Probably because the way the url is parsed, if contains for example #Serverless it will set it's type to inline instead of iframe and will not work correctly, that part of the code it's really old so it requires a lot of changes.

A future version will improve this.

**Comment by dorneanu** [comment]
Okay. Thanks for clarifying this.

**Comment by jorbig** [comment]
> A future version will improve this.

Any updates on this?
