### ISSUE TITLE
With sliderjs some Glightbox links do not work. 

### ISSUE THREAD

**Issue by gregoirenoyelle** [biati-digital/glightbox#310]
**Describe the bug**
I use Glightbox with [splide.js](https://splidejs.com/) on this [page](https://lab-elections.ouest-france.fr/). 

**Are you able to reproduce the bug in the demo site**
No.

**To Reproduce**
Steps to reproduce the behavior. 

1. Go to this [page](https://lab-elections.ouest-france.fr/)
2. Click on the middle image on a slider. 
3. Try to click on the sides images. 
4. On this case the lightbox stop working from time to time. 

**Expected behavior**
The click on each thumbnail should open the lightbox. On [archive page](https://lab-elections.ouest-france.fr/stories/), it works all the time. It's like there is a conflict with the [splide.js](https://splidejs.com/) . 

**Screenshots**
 I have made a screencast about the bug. Here is the [direct link](https://vimeo.com/661904086/56338ca5f2).

**Desktop:**
 - OS: MacOS 10.14.6
 - Browser Chrome Safari
 - Version 96 (Chrome)

**Smartphone:**
 - Device: iPad Pro
 - OS: iOS 14.8.1
 - Browser Safari

Thanks  a lot for your help.

**Comment by biati-digital** [comment]
This is not problem with this library or splidejs, you need to execute GLightbox once splide.js has been created completely or depending of how splide works (if it inserts slides dynamically), you might need to reload GLightbox. We can not provide any help with this.

**Comment by gregoirenoyelle** [comment]
Hi 
Thanks a lot for your answer. On splide.js I can fire some function on many [events](https://splidejs.com/guides/events/#move). 
I just want to know the right way to reload GLightbox. 
Best regards,
Grégoire

**Comment by gregoirenoyelle** [comment]
Hi,
that was a priority problem for the 2 scripts. Thanks for your help. 
Cheers,
Grégoire
