### ISSUE TITLE
adjust number of columns

### ISSUE THREAD

**Issue by joural** [biati-digital/glightbox#311]
hi There, just discovered this lightbox, and I was able to turn demo into pretty gallery,
however I was wondering if there is way to add more columns, I have 4 and and its 
bugging me that I'm unable to add more as half of my screen is empty, my thumbnails 
are 128x96 and stretching them makes them quite pixilated.
Sorry if that's proper noob enquiry.
Thank you.

**Comment by biati-digital** [comment]
Sorry, but it seems you are confusing what GLightbox is, you are talking about the demo site, that was just created to show GLightbox (when you click a thumbnail) 

You should not use the demo site, it was not created to be used by users and has not been updated in years.

**Comment by joural** [comment]
oh, yeah, ill get different layout then, sorry. while I'm here I was wondering if there is a way to add download video button so the video on server ( not hosted on vimeo on youtube) could be downloaded please? thank you & sorry again.

**Comment by frankie-tech** [comment]
That's not relevant to the GLightbox plugin either. You would want to search for a video download service, or something similar. You may want to look around StackOverflow or see if anyone in the Plyrjs community has done something like that, since that is the library we use to create the video player.

**Comment by joural** [comment]
i was able to add the download button to the video player by adding controls 


```
const lightbox = GLightbox({
    plyr:{
      config:{
        controls:['play', 'progress', 'mute', 'volume', 'fullscreen', 'download']
                  }
                }
  });
```
