### ISSUE TITLE
failed to check image type if with "?timestamp" after image name

### ISSUE THREAD

**Issue by myronchanhk** [biati-digital/glightbox#313]
When the img src has '?' sign with timestamp after the image extension (e..g 'jpg' ), glightbox fails to recognize the filename type as image.

Suggest solution: in the glightbox.js remove the '$' sign in the match function:

if (url.match(/\.(jpeg|jpg|jpe|gif|png|apn|webp|svg)$/) !== null) {
  return 'image';
}

that is:

if (url.match(/\.(jpeg|jpg|jpe|gif|png|apn|webp|svg)/) !== null) {

**Comment by biati-digital** [comment]
Please read the docs, you can define your `data-type`
