### ISSUE TITLE
Slider breaks

### ISSUE THREAD

**Issue by crpozo** [biati-digital/glightbox#317]
If you click the slider lightbox next/prev option multiple times (faster) the slider breaks. This using multiples slides, not only 3.

**Comment by frankie-tech** [comment]
Hey there @crpozo,

Thank you for bringing this to our attention. We do require that you use the provided issue templates when filing bugs though, they offer a guideline for what we need to properly debug these sorts of issues.

Please fill out that template and either edit your original issue or add it as a new comment below 🙂 Thanks!
