### ISSUE TITLE
Add option to disable autoplay for video player

### ISSUE THREAD

**Issue by Fedik** [biati-digital/glightbox#318]
**Please describe the feature you want to be implemented.**
Add options that allow to disable "autoplay" for video player.
Because embed videos (youtube, vimeo) does not work as expected on mobile (especially ios), it better to be able just open them without "autoplay".

Current workaround:
```javascript
const lightbox = GLightbox({ ...options });
lightbox.slidePlayerPlay = function(slide){};
lightbox.playSlideVideo = function(slide){};
```

**Comment by Fedik** [comment]
This will fix problems like #298

**Comment by frankie-tech** [comment]
Hey there @Fedik,

This is already available as an option when you create the GLightbox:

```js
const lightbox = GLightbox({
	autoplayVideos: false // now autoplay is disabled
});
```

Or is this not working for you? I'd love to see more code examples if you have them available if that is the case.

**Comment by Fedik** [comment]
Oh, sorry, I totally missed it,
I somehow searched for just "autoplay"  :smile:
