### ISSUE TITLE
Selector in HTML not working

### ISSUE THREAD

**Issue by vojjin** [biati-digital/glightbox#320]
**Describe the bug**
When I create regular HTML with, for example, class "glightbox1" and apply GLightbox, it is not working, it is opening image in a new window. However, when I wrap image with a jQuery and assign class "glightbox1", it is working. Strange.

in my js file I have added (opening at the end of html):

```
$(document).ready(function () {
....
	const lightbox = GLightbox({
		selector: ".glightbox1",
		touchNavigation: true,
		loop: true,
		autoplayVideos: true
	});
....
});

```

when I have a regular HTML code it is not working

```
<a href="/media/images/articles/25/gallery/22_0162.jpg" class="glightbox1">
<img src="/media/images/articles/25/gallery/22_0162.jpg" class="dotouch" alt="22_0162" title="22_0162">
</a>
```
however, if I just put html:
```
<img src="/media/images/articles/25/gallery/22_0162.jpg" class="dotouch" alt="22_0162" title="22_0162">
```
and in javascript, just before initiating glightbox:
```
	$('.dotouch').each(function () {
		let src = $(this).attr("src");
		$(this).wrap('<a href="' + src + '" class="glightbox1"></a>');
	});
```
it is working normally.

Very weird.

**Comment by biati-digital** [comment]
Definitely an error on your code, check the code in demo site. There's not much we can do without knowing your entire code but this is not an error with this library.
