### ISSUE TITLE
Multiple Glightbox on the same page, with the selector option.

### ISSUE THREAD

**Issue by gremo** [biati-digital/glightbox#321]
It seems that it's not possible, right now, to use the selector option with multiple Glightbox  on the same page. Looking at https://github.com/biati-digital/glightbox/blob/master/src/js/glightbox.js#L848, the `querySelectorAll` is invoked on `document`:

`document.querySelectorAll(this.getSelector());`

... this means that there is now way to have two different instances on the same page, with different settings:

```html
<!-- first glightbox (new GLightbox({ selector: 'data-glightbox-item' })) -->
<div id="glightbox-1">
  <a href="large.jpg" data-glightbox-item>
    <img src="small.jpg" alt="image" />
  </a>
</div>

<!-- second glightbox (new GLightbox({ selector: 'data-glightbox-item' })) -->
<div id="glightbox-2">
  <a href="large.jpg"  data-glightbox-item>
    <img src="small.jpg" alt="image" />
  </a>
</div>
```

Because the `document.querySelectorAll(this.getSelector());` will select both `data-glightbox-item` elements of both.

How to solve this? It seems I'm not able to use the `elements` option at all (it doesn't work).

**Comment by biati-digital** [comment]
ou need different selectors to create multiple instances in the same page.

**Comment by gremo** [comment]
OFC @iamrobert and @biati-digital , thanks, but I'm using [Stimulus](https://stimulus.hotwired.dev/) and I was writing a controller for this library.

With Stimulus, you work with `data-` attribute mainly.  An example markup:

```html
<!-- first glightbox (new GLightbox({ selector: 'data-glightbox-target="item"' })) -->
<div data-controller="glightbox">
  <a href="large.jpg" data-glightbox-target="item">
    <img src="small.jpg" alt="image" />
  </a>
  <a href="large.jpg" data-glightbox-target="item">
    <img src="small.jpg" alt="image" />
  </a>
</div>
```

With this markup, I can't pass the selector `data-glightbox-target="item"` because It won't work with two or more Glightbox on the same page.

**Comment by frankie-tech** [comment]
@gremo thats information that should be included in the original issue. this is why we offer the issue templates.

furthermore, there's nothing about stimulus that is _preventing_ you from using a class selector. you should read through their handbook again, the answer is in their most likely.

we can't help you integrate glightbox into a stimulus application.
