### ISSUE TITLE
Image gets unnecessary inline styles when zoomed

### ISSUE THREAD

**Issue by nico-heinrich** [biati-digital/glightbox#324]
Dear creators of the glightbox,

first of all: I love your lightbox and it is really easy to work with.
However, there is an issue when I zoom in on an image: "gslide-media gslide-image" gets this style ...

_"transform: translate3d(-180px, 0px, 0px);"_

The first value varies, depending on the size of the image. What it does? It keeps the image from being centered - WTF? Without this style, everything would be fine.

I hope you can help me!

Cheers,

Nico

**Comment by biati-digital** [comment]
The inline style is used so user can drag the image around on mobile devices, even with zoom you can move the image so obviously the image is moved using transform: translate3d...

For now there's no a way to auto center.
