### ISSUE TITLE
Default CSS should fade in icons/arrows/close buttons with the image

### ISSUE THREAD

**Issue by JiveDig** [biati-digital/glightbox#326]
Thanks for much for this script, it's great!

Right now the image zooms/fades in when opening the gallery, and it looks great, but it's mildly jarring that the navigation icons are shown immediately. They should food fade/transition in along with the image.

I'll likely edit the CSS myself, but I'm thinking it makes sense as a default.

**Comment by biati-digital** [comment]
Hi @JiveDig i'm glad you like it. 

Sorry but this probably won't be added, some people requested removing all animations so i think this is a personal preference.

Adding it to your project is the way to go.

**Comment by JiveDig** [comment]
Understood, thanks for the reply :)

I wonder if it would make sense to have all the animations be in a separate CSS file to be optionally loaded ¯\_(ツ)_/¯.
