### ISSUE TITLE
Looping videos without controls (not even on mousover)

### ISSUE THREAD

**Issue by DannyBen** [biati-digital/glightbox#327]
1. Would love to have the ability to enable loop on videos
2. Would love to have the ability to completely hide video controls (right now they are shown on mouseover)

This would allow showing MP4 as if they were animated gifs. I am looking to get this output for the video slide:

```html
<video muted autoplay loop src="video.mp4" />
```

**Comment by biati-digital** [comment]
1.- The video player already supports loop, please checkout the [Plyr Readme](https://github.com/sampotts/plyr) to learn more.

2.- You can find what you are looking for in the Plyr Readme or you can add some CSS to your project to hide the controls.

**Comment by DannyBen** [comment]
Yes, still. I wish we could just do without Plyr. Autoplaying a looping MP4 without controls is the simplest HTML tag possible, and now we just need to find ways to reduce the video player back to its basics.

Found the looping syntax, which is quite verbose...

```javascript
lightbox = GLightbox({
  selector: '.thumb',
  plyr: {
    config: {
      loop: {
        active: true
      }
    }
  }
});
```

**Comment by biati-digital** [comment]
Agree that the Plyr code is "quite verbose" but this is the first time someone has requested this,  it could be the simplest HTML tag but options must be created to allow the user to configure it globally or by slide, make tests with Plyr, etc. 

I think people will be ok using the plyr config to specify the "loop".
