### ISSUE TITLE
Glightbox doesn't start YouTube video with specific starting time.

### ISSUE THREAD

**Issue by Random366** [biati-digital/glightbox#328]
**Describe the bug**
Youtube video link with specific starting time from 45sec (e.g. https://youtu.be/XqZsoesa55w?t=45) doesn't work in GLightbox. It simply starts from the start.

I've tried changing the questionmark in timestamp with &t=45  ; adding letter "s" ?t=45s signaling the seconds in the end ; but it simply starts from the beginning everytime.

Any idea if there's an option to play it with GLightbox from a specific time?

**Comment by biati-digital** [comment]
This is something you need to post in the [Plyr repo](https://github.com/sampotts/plyr) as GLightbox simply passes your youtube url to the player.
