### ISSUE TITLE
Lightbox does not open preview for images with the extension .jfif

### ISSUE THREAD

**Issue by meilechwieder** [biati-digital/glightbox#330]
**Describe the bug**
If an image has a .jfif extension, glightbox tries to open the link as a vimeo video instead of an image

**Are you able to reproduce the bug in the demo site**
Yes. [(Link)](https://codesandbox.io/s/modest-keller-097nih?file=/index.html)

**To Reproduce**
1. Go [here](https://codesandbox.io/s/modest-keller-097nih?file=/index.html)
2. Click on the image
4. See image preview not openeing

**Expected behavior**
Open image preview on top of title

**Post the code you are using**
https://codesandbox.io/s/modest-keller-097nih?file=/index.html

**Comment by frankie-tech** [comment]
Hey there @meilechwieder 

`.jfif` files, as I understand it, are primarily used by cameras for photography. 

I would recommend converting it to `.jpeg`. 

If it _has_ to be a `.jfif`, then you could make a PR with the updated file regex in the slide parser js.

**Comment by meilechwieder** [comment]
It has to be a .jfif - that's the way I'm getting it from the image hosting
company. Not sure where in the code the file extension regex is

Also since I'm using it from jsdelivr cdn, I'll have to wait for next
release?

**Comment by biati-digital** [comment]
Hi @meilechwieder just set data-type="image", this is explained in the docs.
