### ISSUE TITLE
 Lightbox breaks with lazy loading attribute

### ISSUE THREAD

**Issue by meilechwieder** [biati-digital/glightbox#333]
I will put a clear description tomorrow from my computer 

**Describe the bug**

**Are you able to reproduce the bug in the demo site**
Yes|No.

**To Reproduce**

**Expected behavior**

**Post the code you are using**
Help me solve issues faster, if I can copy paste your code I can try to reproduce and fix the bug faster.

**Screenshots**

**Desktop:**

**Smartphone:**

**Comment by biati-digital** [comment]
Closing this as no more info was provided, open a new issue when you have all the info
