### ISSUE TITLE
import not working

### ISSUE THREAD

**Issue by firdausakbarr** [biati-digital/glightbox#337]
**Describe the bug**

**Are you able to reproduce the bug in the demo site**
Yes|No.

**To Reproduce**

**Expected behavior**

**Post the code you are using**
Help me solve issues faster, if I can copy paste your code I can try to reproduce and fix the bug faster.

**Screenshots**

**Desktop:**

**Smartphone:**

**Comment by gingerchew** [comment]
Hey there @firdausakbarr,

This issue hasn't been filled out properly. Please submit a new issue with the proper information.
