### ISSUE TITLE
Uncaught ReferenceError: GLightbox is not defined 

### ISSUE THREAD

**Issue by uixandy** [biati-digital/glightbox#340]
**Describe the bug**
Uncaught ReferenceError: GLightbox is not defined
    at (index):144:18

**Are you able to reproduce the bug in the demo site**
No.

**To Reproduce**
https://oxygen.uixandy.com/

Scroll to "Success Stories" -> I want the images to open in Glightbox on click. I wrapped images in link with class .glightbox and using the code below in the footer. Does not work for some reason.

**Expected behavior**

**Post the code you are using**
<script type="text/javascript">
const lightbox = GLightbox({
    selector:  'glightbox',
    touchNavigation: true,
    loop: true,
});
</script>

**Comment by gingerchew** [comment]
Hey there @uixandy,

We don't offer support for setting up GLightbox. Uncaught ReferenceError is very common issue to run into though. If you look on StackOverflow or search on Google, I'm sure you can find someone who has run into a similar issue to you.
