### ISSUE TITLE
Enabling the new Discussions feature for the repo

### ISSUE THREAD

**Issue by gingerchew** [biati-digital/glightbox#346]
**Please describe the feature you want to be implemented.**
Github (sort of) recently added the ability to have a discussion thread style section on the tab section at the top of the repo. I think we should look into enabling this.

**Explain why the feature is useful**
While the backlog of closed issues and StackOverflow help, the discussions section would allow for a more ongoing and asynchronous conversation to occur with multiple people. It would help move the onus away from just us, the maintainers, and spread it out towards the community.

**Have you seen it somewhere else?**
The petite vue github I think is a great example. They currently don't even have issues turned on, and instead opted for just the discussions. https://github.com/vuejs/petite-vue

![image](https://user-images.githubusercontent.com/26461046/182895609-3fb488c1-24e9-4e85-91ce-affb6e36e950.png)
An example of some of the categories people can choose

**Comment by biati-digital** [comment]
Great idea, **Discussions** should already be enabled.
