### ISSUE TITLE
long tap to enter in image selecting mode

### ISSUE THREAD

**Issue by aguaviva** [biati-digital/glightbox#347]
**Please describe the feature you want to be implemented.**
long tap to enter into image selecting mode, afterwards a click/touch will select images.

**Explain why the feature is useful**
it allows bulk operations

**Have you seen it somewhere else?**
pretty much in any cellphone image gallery 

**Additional context**
Any pointers on how to implement this myself are welcome

**Comment by gingerchew** [comment]
Hey there @aguaviva 

It sounds like what you're looking for is something that would be implemented by a more complex UI framework/library and not a lightbox/gallery.

If you're trying to mimic something you're seeing inside of a native environment like a mobile OS I would suggest checking out something from React Native or its many cousins.

Unless I'm mistaken in what I'm thinking of. If you can give a video/image example that would give me a better idea.

**Comment by biati-digital** [comment]
Hi, this would require a lot of code and a lot of time, this is not something i would consider adding to the lightbox.

**Comment by biati-digital** [comment]
I'll close this for now, thanks for the suggestion.
