### ISSUE TITLE
Setting title/description programmatically

### ISSUE THREAD

**Issue by 314parley** [biati-digital/glightbox#35]
Hi! I am very interested in your library. however, I was wondering if there's a way to set the title and description programmatically across all of the images? 

I attempted to set the href to different things, but none of which worked successfully.

any way I can make it work properly through setElements or another workaround?

**Comment by 314parley** [comment]
I don't have a live example of this, like
![screen shot 2018-10-22 at 8 17 47 pm](https://user-images.githubusercontent.com/1246441/47334413-a8e82200-d63b-11e8-8ec2-e7440d7aec9f.png)
, and imagine I have a large set of images, and I want to set the title, and description via javascript, dynamically.

I know about `data-title` `data-description`, but your setElements function requires an exact URL.

**Comment by mcstudios** [comment]
Can you provide some examples of how would you think the api should work to achieve what you want? i currently don't have time to invest on something like this but if you help me to define how the api should work we could solve this faster.

**Comment by mtness** [comment]
ok, a bit late to the party here,
but I found a solution without having to adjust anything.

one just has to build the data-glightbox tag via script _before_ the lightbox gets initalised!

In my case, the containing images already had their dataset filled, like data-copyright and data-description etc.

so, here: 
```html
[...]
<li class="splide__slide">
	<a href="https://picsum.photos/seed/a/1920/1080"  class="glightbox" data-type="image">
		<img src="https://picsum.photos/seed/a/800/450" alt=""  data-width="" data-height="" data-title="my image title" data-description='<p>my image description with markup and <a href="http://example.com">links</a></p>' data-copyright="my copyright" data-hires="https://picsum.photos/seed/a/3840/2160" class="img-responsive" title="my title" width="900" height="675" alt="my alt text" />
	</a>
</li>
[...]
```


``` javascript
// Get elements with the specified class name
let elements = document.getElementsByClassName('glightbox');
// Loop through the elements and add the desired attribute
for (var i = 0; i < elements.length; i++) {
	console.log(elements[i].querySelector('img').dataset.description);

	let elTitle = ( elements[i].querySelector('img').dataset.title )       ? 'title:'+ elements[i].querySelector('img').dataset.title +';' :'';
	let elText  = ( elements[i].querySelector('img').dataset.description ) ? '<span class="text">'+ elements[i].querySelector('img').dataset.description +'</span>' :'';
	let hires   = ( elements[i].querySelector('img').dataset.hires )       ? '<a href="'+ elements[i].querySelector('img').dataset.hires +'">HiRes</a> | ' : '';
	let elDown  = '<span class="down">Download: ' + hires + '<a href="'+ elements[i].querySelector('img').src +'">LowRes</a></span>';
	let elCopy  = ( elements[i].querySelector('img').dataset.copyright ) ? '<span class="copy">'+ elements[i].querySelector('img').dataset.copyright +'</span>' :'';

	let elDesc  = 'description:'+  elText + elDown + elCopy ;

	elements[i].dataset.glightbox = elTitle + elDesc;
}

```
