### ISSUE TITLE
Focus should be restored to original position after closing modal

### ISSUE THREAD

**Issue by cmachanic** [biati-digital/glightbox#351]
**Describe the bug**
If you close the modal when navigating via a keyboard, the tab order returns to the top of the page.

**Are you able to reproduce the bug in the demo site**
Yes

**To Reproduce**
1. Open a photo in the modal
2. Tab to the close button to close the modal
3. Continue tabbing where you left off, and you'll find yourself tabbing from the top of the DOM

**Expected behavior**
You should return to your original position in the tab order prior to opening the modal.

**Desktop:**
 - Tested on MacOS Chrome, Firefox and Safari
 - Tested on Windows Edge, Chrome and Firefox

**Comment by gingerchew** [comment]
A bit of a patch was talked about in this [discussion thread](https://github.com/biati-digital/glightbox/discussions/371#discussioncomment-3896378), in case anyone is looking for a possible fix in the mean time. 

I haven't had a chance to test it with a screen reader, but it should work for moving focus around.

If someone is having an issue implementing the patch, open a discussion thread and we can try and work it out, seeing as it is *unofficial* :)
