### ISSUE TITLE
view only filtered images

### ISSUE THREAD

**Issue by dominibase** [biati-digital/glightbox#372]
Congratulations on your script, which I tried to integrate it into the justifygallery script, with the addition of the filter on the images, only that when I would like to view with glightbox it always shows me the whole gallery and not the filtered images, I modified the script by removing and adding the glightbox2 class but to no avail, can you help me? thank you.

I am attaching file with script because the insertion by code does not go thanks
[SCRIPT.txt](https://github.com/biati-digital/glightbox/files/9838924/SCRIPT.txt)

**Comment by gingerchew** [comment]
Sorry we don't offer support for implementation or integration, you can start up a discussion and someone from the community may be able to help you.

Closing due to being outside support scope.
