### ISSUE TITLE
Glightbox style

### ISSUE THREAD

**Issue by pixelmatty** [biati-digital/glightbox#381]
Hi there

Just a short question: is it possible to address different styles for the lightbox in one site? I use it in contao 4.13 and want to show some elements with border and some elements without border in the lightbox.

thanks in advance
regards
pixelmatty

**Comment by gingerchew** [comment]
Hey there @pixelmatty 

I'm not entirely sure what you're asking for. It is possible to change the styles, yes. If you need help styling your the lightbox on your site, you will need to start a discussion in the discussions section. We like to leave the issues section only for issues and feature requests.

I don't know anything about "catao" so if you're having trouble adding custom CSS to your site, you would need to reach out to their support.

**Comment by pixelmatty** [comment]
Sorry, yes it's for discussion section. (I want to use different styles for different elements in one site)
