### ISSUE TITLE
Allow us to hide previous and next buttons with options

### ISSUE THREAD

**Issue by simkoG** [biati-digital/glightbox#386]
**Important.**
Before posting a feature request please make sure to search the closed issues, maybe the feature you want to implement has already been asked and denied for not providing a valid explanation or simply because it was something the user wanted for him or his project.

**Please describe the feature you want to be implemented.**
Right now you can hide only the exit button. But if you only have one element, the next and previous buttons are show but not clickable. You should add a config option like `closeButton` to hide the nav buttons. 

**Explain why the feature is useful**
If you have one element inside the Glightbox the nav buttons are not used. 

**Have you seen it somewhere else?**
-

**Additional context**
-

**Comment by gingerchew** [comment]
You can use CSS to accomplish that.

```css
.glightbox-button-hidden {
  display: none
}
```
