### ISSUE TITLE
Youtube lightbox loads infinitely if there is another Youtube IFrame API element defined

### ISSUE THREAD

**Issue by joonhyungshin** [biati-digital/glightbox#394]
**Describe the bug**
If you define a valid Youtube IFrame API element using `YT.Player()`, then GLightbox would not load a Youtube video.

**To Reproduce**
1. Copy-and-paste below code to 'index.html'.
2. Open with an innocent web browser.
3. Click on 'Lightbox' link.
4. Loads infinitely.

**Expected behavior**
A Youtube video should show up and play

**Post the code you are using**
Minimal reproducible example:
```html
<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/glightbox/dist/css/glightbox.min.css" />
		<script src="https://cdn.jsdelivr.net/gh/mcstudios/glightbox/dist/js/glightbox.min.js"></script>
	</head>
<body>
	<div id="player"></div>
	<a class="glightbox" href="https://youtu.be/M7lc1UVf-VE">Lightbox</a>
	<script type="text/javascript">
        var tag = document.createElement('script');
        tag.src = "https://www.youtube.com/iframe_api";
        var firstScriptTag = document.getElementsByTagName('script')[0];
        firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

        function onYouTubeIframeAPIReady() {
		const player = new YT.Player('player', {videoId: 'M7lc1UVf-VE', width: '640', height: '360'});
        }
        const lightbox = GLightbox({
            descPosition: "right"
        });
	</script>
</body>
</html>
```

**Screenshots**

**Desktop:**
 - OS: MacOS
 - Browser: Chrome
 - Version 108.0.5359.124 (arm64)

**Comment by biati-digital** [comment]
This is a known issue, when the site includes the youtube or vimeo API, Plyr never triggers the "ready" event when loading a video slide.  We'll need to check if other Plyr methods can fix this problem

**Comment by jwdevel** [comment]
I just hit this as well.

Is there any workaround?

**Comment by biati-digital** [comment]
@jwdevel no workaround yet
