### ISSUE TITLE
YouTube Shorts

### ISSUE THREAD

**Issue by leenasn** [biati-digital/glightbox#395]
I find that the videos don't play when YouTube Shorts URL is provided. Can someone guide me to fix it?

Thanks,
Leena

**Comment by gingerchew** [comment]
Hmmm, that is strange, can you post an example of the url you're using? There is a chance that plyr.js, and subsequently GLightbox, doesn't support that format yet.

**Comment by leenasn** [comment]
Here is a sample URL: https://www.youtube.com/shorts/Rj2JgmXzLxQ

Sorry, forgot to add it earlier.

**Comment by gingerchew** [comment]
Yup its like I thought, currently the regex that looks for the provider is this https://github.com/biati-digital/glightbox/blob/29e365d4148c72ac08da752a5d0ebbe595f7046f/src/js/slides/video.js#L38-L43

```js
        if (
            !provider &&
            (url.match(/(youtube\.com|youtube-nocookie\.com)\/watch\?v=([a-zA-Z0-9\-_]+)/) || url.match(/youtu\.be\/([a-zA-Z0-9\-_]+)/) || url.match(/(youtube\.com|youtube-nocookie\.com)\/embed\/([a-zA-Z0-9\-_]+)/))
        ) {
            provider = 'youtube';
        }
```

If someone wants to add to the regex the necessary regex pieces, I'm more than happy to review the PR :)
