### ISSUE TITLE
HTML Tags removed in Advanced Description on mobile

### ISSUE THREAD

**Issue by chrwal09** [biati-digital/glightbox#403]
Hi,
I use the advanced description for the lightbox. Works very well so far. However, on mobile devices the HTML tags in the description are removed.

HTML Code on Desktop:
<div class="gslide-desc" id="gSlideDesc_8">
 <h3>Title</h3>
 <p>Description 1</p>
 <p>Description 2</p>
</div>

HTML Code on Mobile Device

<div class="gslide-desc" id="gSlideDesc_8">Title Description 1 Description 2</div>

Is there a solution for this so that the HTML tags are also output on mobile devices?

Thank You

**Comment by IndoPy** [comment]
You need to set `moreLength:0`. gLightbox's default `moreLength` is `60`.

For full explanation, please see [here](https://github.com/biati-digital/glightbox/issues/299).

For example on how to set it, see [here](https://codepen.io/gingerchew/pen/gOxQJwM/1a9fa39380883be7bb70145d8f5bdad5).
