### ISSUE TITLE
Add @types/Glightbox

### ISSUE THREAD

**Issue by tomasvn** [biati-digital/glightbox#405]
**Please describe the feature you want to be implemented.**

Add types for the package

**Comment by gingerchew** [comment]
Hey there @tomasvn 

Currently, adding things like types or other typescript adjacent things isn't a high priority.

That said, if you are able to get the ball rolling, I'd be more than happy to help out/check your work.

**Comment by tomasvn** [comment]
@gingerchew Hi, I am not that well versed in TS, but I can try it.

**Comment by gingerchew** [comment]
If you want, we can start at creating types/interface for the config object (I imagine that's what people would want typing for the most) and then work from there.

**Comment by tomasvn** [comment]
@gingerchew this is my draft for DefinitelyTyped package

[TS playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEA7KBbEBnADlMCDiAMgJYDmAFgC4BGA9gB7wDeAUPG-APQBUXr78XeAE0aAVwqiqCIgDMYqBFExE+7QQAF0IBJQqZ0ALg4dQANxAQamEDHQA6EjRokIIO2BooOATzESpHJjQ3jYA+tjyaBQ26KpsXBxxRIjRMDI4CCLikiAA8pgURDSI6Exx-Ny8-NWCAOpkIBQNMPAUNPCiWvBQiN0QqciF5vDmtkW9NDLCfjnwAO5ETX7wHjQA1kQY5fwJ22yINADCThsgAPwG8LQ0rj0A3HucPI8C8ADKZDRz8HDQ0cAjIigGixao7RJgti-C5IUQoKQwB6Qp5VZGCD5fQHA1qLVwvDRaHQUPSGYyOZyudyeHwzAJBKAhGDhWAKVLoADEvxAUC0oQO0XQoQADAAOUIAJgAzBKhQBGEX4+CK9SgTBwMBQf74iGQ9CfBaIGQ0GGIOEIpGQyqKjHfGgtMhAxSIfma8agtE6sFEUyhSxQYDhG5EMDeE1mmwWtgAXzicStNXgADUiGh2iB4SAAaZHe0lCoE+UCdp4Lp9EYOA0IJg7NnU1SvGQwBwQIgALSdDiwQqQDAcSUANiFQ9lABYAJwjycAdlbAFV0MkSK2AArBGwrllRGKFz3wZKpdK4JMpkA0fKFYqlFjI+No9761oNK7eCDJBDFR8IbPAuzax5UF83xha5bkQSNqlvSF0QfJpFHET4YEATAJSjVSYiFcPcUCgEgEAACkwO0KHkRYAEo-2RAiYCIqBFmApxQPAipnmRV4bU-LFT2QnEKEpcjIUKHjzkuEDuTAx5ILBQQAFFkCoDC7XgYAiHQKA5IQWCrhwNYSBgMREABSZ2PpRk+LBaiSgiFsKDom5RPAmMkhSGxDwQY5DVIMob2Yu83kabosHACgfldGhTOqeQLxhdAiMXRj2AkhN4AAFWcFwMHmBpYJaGRRAgCB0DAOAW3gPUxAgAEpHgFtVNcAyYEVDLGmaVp2k6BBBm9aRcjeeAcrygqit6OYGl6KybEXBq+vywrtEQML+CmgbZphAAlcA7WAAAeAByaq1OAbb4AAH3gbainQAA5V1zG2gAaK56NEgA+OK2F8bIpBhLJ-DyAo3VewFUxhZNU3PN04gc-h92cjJ4FXbwYDBy9PMtbyoPgPA-PhmA7AAK1KMB0FKGR0PSuRPBWYA5pY3ZkUJ9AopixASABhKdgxrGIARvHSnx3rSeJ3SUEp6mPUefHGZgWLHg8dySBhNySZZiHmEcg9YaRkoUbBNm1HgK60HgQyNK0VwwDabKFJAOhUCCBBtocV9yGoehDoU7bgE1KBWxcUhKFoOhtsVd2uAAbU9ihvd952A4AXSDmmlUTlUQHSXKKETKAIFEe3Hb9l3A-m9hTcCu1JelrzUXRgBJEpon9I2pmwInF26EqLFLlp3pWHp4Gb0os4gdjFnTd10aaTV4G7uYeiC5J2JIQebG8X9E+VUA0-6TPs-a3KICLtgO7QFIGcuUPY+O2E8tZtHJP1hRG-Y9ANkQe7FnmdCh-9AEoBWaAiZauxJ2-t6CKnQO0buGpejRRfNIIKCwmgrCJqvO869U5QHTtvHOp0ew9ATmLZEz9kjl2ZjfKud8DbvimBpVOMhApG16MAguRtrCIDsPAXCAAvJwKB7rpFAPdA4iAQBkTXsnDeGCt5Z2wdtbhnh8FQV3PwKwLYpIyDoebEhytK6KkoY-Gh6j6EfiYQHP+II3AcLkbw3q-oQCCOKCIxUaDN4Z2kfbKxCjJJKPYJAcxaiNHWUuNFKWpDxK3wTHo42T5aFGOga+UAKwyA9Bwuw3C6B4l2JsQI+AVj7HCNEag8R6DMFuNOukx0niajeLYOU0A-jApaLIYqAAsnadS1sgpGhaKAAaRA-rIw-CgGgVBSaKRANmXA9gnFFJcVg+2vkEBDLgJU8EjwlkgCSh0xpYTyERPDC0QyYAknyHNjEQBSksDBAYexHphU+kXl6FILpihgBKWZoqDS6zNl0CCq+RAawOHFC5r1BSQyRmuHQCRW6ipZDwCFHueBn9FLKWMuxKyRA4BjN6f0th0y7wp1maUwcB94DrIIC2EgTQwwZkRDs60D4FIOgSRpXxXQqDiDaLisR+KJElJ3q0GAOcSWspAAAIQ5cUGyDE6WJxkjVd83TlLyvYm0UQRykBQGzIvB5HD0ALGsCRFB6NnGSNcfyoiQqabVJamqsgV0tUhUQFKuyMq7zVywjhEFeVMRQDoMpRqvRgDyBICQVugzhmkyNXfE1fLsEWpACS1VRyABiNxLBzAAIJ+tPg9Wy9xXXozlWpI2iqVLFo0msEA3haCwABMgB1Dyo0FhmaauZArLUEMhJW6tNBa32tII651+adGJ0OJYLoGkTH0ADX-YML8SBG3EAuZlT4cBDAQLUtweL0YEtbaU+Nwrx15EQLkJdjox1zqHWJEdPlI5UXgFOhgk8N5vgBMkUAdAm3sxjVI-lQoSXRS7BmwJsIaVNMTgAEWKf0D+wBEFdL3IgP5CAj5WQHvpPccgFBj2jS22N9sxxDkwIXK1jwFhwbINsm96MoMuJLCAfOIKWjJGQ1VVwx8KDobfVhtAOHm08ug2amRABWIU-ZiMrLUNaho+cqOo12ezWjprYPwYUt+U8UzuU7t5b+kTg4JMkvUyCWoQIqVBKZto+Tio8CWCoFnPuIJFjjCYyVDJpRblSxxduu+u78OnVoMSeRJLbnLkcw8uTOtwnswIE4TArnHSlA-C2YAX69Y-qEwgdI+UE2keRJYKwV7wN3iLfJUtyqrHKpTNhLYWmfM6Yy+2nLnawQVbUoVgtd8SsKuRWWjCQy2qKWDYAxwfc4CmG6Bh4RPz4ugG8wmXzun1KCqa4ox4QbsKLza8JR6w6rOJ3nJmD+iD1shvlewi6+zH7KDoBYUoGk2r1UTkku77QTvDfaG0Ub4yS1IA6TNrdtX5v1bbSOf9uXIQnZSq4eQiBcAAA1qXmg6wmA7AIEFkEGxts7+tLuGWu7d9iD2Sw8nOcGxUog4sKWAF8Xon2RVAPzgHOb7MFsNf7MJ4Lwaoc2B6LgIQiOIzI-ZtXahy2n4ZI-nlbo4hPCug1HlbwiTknqXaGqcZHAptBQUiKmFUxIe2Rh-Dn7+voe85AEIPcpQ4A4AaMAaFicaBZQWF0d+Cwpcz3foUKXnyxAu6tx3HkmZUvxCTgJwl-KstaE59hDNMu3jIEwO16jnXZKlZ68qtXfo3kkGD68dLbaD3g7BJn3twAk97Z8n5d6By5jQNMAu4Ml5c+011PX1a60YBbW2iKw6J1tqa976dNXpg7olQsy9IXetaNvh+-6XGnRfmM+nT0KrDzNOFPxYSS4wqib1PNjmtaHhO+bWCYue6h+No7WSIP7afhR+n+Zk9CfyeExZB7r0DwKA7bRGBUc5X7FKAUAh5DJCAl9P0SVH0AAJJKZpAgCLCCKLPWN-KBFYTwb-CwRXP-ZmdSJ8QA4A6hJ8d9b0IEUQezTdZva1TdaA2A+ApiBTPWWPNoVFIzRLCYVhZvUPbTQTAvZbElDBJg4IZMYEHNESXbSLegkPEXRrDidoN3IeSqI0MANqAyXoVFT7QeL4RUbtGtTvEqQiJQzjFzDSYyGwe6Jof1OQsZNdb0TUFbO+YfCbOtP7WAXSOYF7JXbA-7DgvgmXRQzoIQjTcvYvLmGAGEbGTWdAeyZgGMIAA)

**Comment by gingerchew** [comment]
That's a good question, I'm leaning towards just adding an `index.d.ts` file to the root. @biati-digital what are your thoughts?

**Comment by gingerchew** [comment]
> @gingerchew this is my draft for DefinitelyTyped package or the types should be here in the main repo?
> 
> [TS playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEA7KBbEBnADlMCDiAMgJYDmAFgC4BGA9gB7wDeAUPG-APQBUXr78XeAE0aAVwqiqCIgDMYqBFExE+7QQAF0IBJQqZ0ALg4dQANxAQamEDHQA6EjRokIIO2BooOATzESpHJjQ3jYA+tjyaBQ26KpsXBxxRIjRMDI4CCLikiAA8pgURDSI6Exx-Ny8-NWCAOpkIBQNMPAUNPCiWvBQiN0QqciF5vDmtkW9NDLCfjnwAO5ETX7wHjQA1kQY5fwJ22yINADCThsgAPwG8LQ0rj0A3HucPI8C8ADKZDRz8HDQ0cAjIigGixao7RJgti-C5IUQoKQwB6Qp5VZGCD5fQHA1qLVwvDRaHQUPSGYyOZyudyeHwzAJBKAhGDhWAKVLoADEvxAUC0oQO0XQoQADAAOUIAJgAzBKhQBGEX4+CK9SgTBwMBQf74iGQ9CfBaIGQ0GGIOEIpGQyqKjHfGgtMhAxSIfma8agtE6sFEUyhSxQYDhG5EMDeE1mmwWtgAXzicStNXgADUiGh2iB4SAAaZHe0lCoE+UCdp4Lp9EYOA0IJg7NnU1SvGQwBwQIgALSdDiwQqQDAcSUANiFQ9lABYAJwjycAdlbAFV0MkSK2AArBGwrllRGKFz3wZKpdK4JMpkA0fKFYqlFjI+No9761oNK7eCDJBDFR8IbPAuzax5UF83xha5bkQSNqlvSF0QfJpFHET4YEATAJSjVSYiFcPcUCgEgEAACkwO0KHkRYAEo-2RAiYCIqBFmApxQPAipnmRV4bU-LFT2QnEKEpcjIUKHjzkuEDuTAx5ILBQQAFFkCoDC7XgYAiHQKA5IQWCrhwNYSBgMREABSZ2PpRk+LBaiSgiFsKDom5RPAmMkhSGxDwQY5DVIMob2Yu83kabosHACgfldGhTOqeQLxhdAiMXRj2AkhN4AAFWcFwMHmBpYJaGRRAgCB0DAOAW3gPUxAgAEpHgFtVNcAyYEVDLGmaVp2k6BBBm9aRcjeeAcrygqit6OYGl6KybEXBq+vywrtEQML+CmgbZphAAlcA7WAAAeAByaq1OAbb4AAH3gbainQAA5V1zG2gAaK56NEgA+OK2F8bIpBhLJ-DyAo3VewFUxhZNU3PN04gc-h92cjJ4FXbwYDBy9PMtbyoPgPA-PhmA7AAK1KMB0FKGR0PSuRPBWYA5pY3ZkUJ9AopixASABhKdgxrGIARvHSnx3rSeJ3SUEp6mPUefHGZgWLHg8dySBhNySZZiHmEcg9YaRkoUbBNm1HgK60HgQyNK0VwwDabKFJAOhUCCBBtocV9yGoehDoU7bgE1KBWxcUhKFoOhtsVd2uAAbU9ihvd952A4AXSDmmlUTlUQHSXKKETKAIFEe3Hb9l3A-m9hTcCu1JelrzUXRgBJEpon9I2pmwInF26EqLFLlp3pWHp4Gb0os4gdjFnTd10aaTV4G7uYeiC5J2JIQebG8X9E+VUA0-6TPs-a3KICLtgO7QFIGcuUPY+O2E8tZtHJP1hRG-Y9ANkQe7FnmdCh-9AEoBWaAiZauxJ2-t6CKnQO0buGpejRRfNIIKCwmgrCJqvO869U5QHTtvHOp0ew9ATmLZEz9kjl2ZjfKud8DbvimBpVOMhApG16MAguRtrCIDsPAXCAAvJwKB7rpFAPdA4iAQBkTXsnDeGCt5Z2wdtbhnh8FQV3PwKwLYpIyDoebEhytK6KkoY-Gh6j6EfiYQHP+II3AcLkbw3q-oQCCOKCIxUaDN4Z2kfbKxCjJJKPYJAcxaiNHWUuNFKWpDxK3wTHo42T5aFGOga+UAKwyA9Bwuw3C6B4l2JsQI+AVj7HCNEag8R6DMFuNOukx0niajeLYOU0A-jApaLIYqAAsnadS1sgpGhaKAAaRA-rIw-CgGgVBSaKRANmXA9gnFFJcVg+2vkEBDLgJU8EjwlkgCSh0xpYTyERPDC0QyYAknyHNjEQBSksDBAYexHphU+kXl6FILpihgBKWZoqDS6zNl0CCq+RAawOHFC5r1BSQyRmuHQCRW6ipZDwCFHueBn9FLKWMuxKyRA4BjN6f0th0y7wp1maUwcB94DrIIC2EgTQwwZkRDs60D4FIOgSRpXxXQqDiDaLisR+KJElJ3q0GAOcSWspAAAIQ5cUGyDE6WJxkjVd83TlLyvYm0UQRykBQGzIvB5HD0ALGsCRFB6NnGSNcfyoiQqabVJamqsgV0tUhUQFKuyMq7zVywjhEFeVMRQDoMpRqvRgDyBICQVugzhmkyNXfE1fLsEWpACS1VRyABiNxLBzAAIJ+tPg9Wy9xXXozlWpI2iqVLFo0msEA3haCwABMgB1Dyo0FhmaauZArLUEMhJW6tNBa32tII651+adGJ0OJYLoGkTH0ADX-YML8SBG3EAuZlT4cBDAQLUtweL0YEtbaU+Nwrx15EQLkJdjox1zqHWJEdPlI5UXgFOhgk8N5vgBMkUAdAm3sxjVI-lQoSXRS7BmwJsIaVNMTgAEWKf0D+wBEFdL3IgP5CAj5WQHvpPccgFBj2jS22N9sxxDkwIXK1jwFhwbINsm96MoMuJLCAfOIKWjJGQ1VVwx8KDobfVhtAOHm08ug2amRABWIU-ZiMrLUNaho+cqOo12ezWjprYPwYUt+U8UzuU7t5b+kTg4JMkvUyCWoQIqVBKZto+Tio8CWCoFnPuIJFjjCYyVDJpRblSxxduu+u78OnVoMSeRJLbnLkcw8uTOtwnswIE4TArnHSlA-C2YAX69Y-qEwgdI+UE2keRJYKwV7wN3iLfJUtyqrHKpTNhLYWmfM6Yy+2nLnawQVbUoVgtd8SsKuRWWjCQy2qKWDYAxwfc4CmG6Bh4RPz4ugG8wmXzun1KCqa4ox4QbsKLza8JR6w6rOJ3nJmD+iD1shvlewi6+zH7KDoBYUoGk2r1UTkku77QTvDfaG0Ub4yS1IA6TNrdtX5v1bbSOf9uXIQnZSq4eQiBcAAA1qXmg6wmA7AIEFkEGxts7+tLuGWu7d9iD2Sw8nOcGxUog4sKWAF8Xon2RVAPzgHOb7MFsNf7MJ4Lwaoc2B6LgIQiOIzI-ZtXahy2n4ZI-nlbo4hPCug1HlbwiTknqXaGqcZHAptBQUiKmFUxIe2Rh-Dn7+voe85AEIPcpQ4A4AaMAaFicaBZQWF0d+Cwpcz3foUKXnyxAu6tx3HkmZUvxCTgJwl-KstaE59hDNMu3jIEwO16jnXZKlZ68qtXfo3kkGD68dLbaD3g7BJn3twAk97Z8n5d6By5jQNMAu4Ml5c+011PX1a60YBbW2iKw6J1tqa976dNXpg7olQsy9IXetaNvh+-6XGnRfmM+nT0KrDzNOFPxYSS4wqib1PNjmtaHhO+bWCYue6h+No7WSIP7afhR+n+Zk9CfyeExZB7r0DwKA7bRGBUc5X7FKAUAh5DJCAl9P0SVH0AAJJKZpAgCLCCKLPWN-KBFYTwb-CwRXP-ZmdSJ8QA4A6hJ8d9b0IEUQezTdZva1TdaA2A+ApiBTPWWPNoVFIzRLCYVhZvUPbTQTAvZbElDBJg4IZMYEHNESXbSLegkPEXRrDidoN3IeSqI0MANqAyXoVFT7QeL4RUbtGtTvEqQiJQzjFzDSYyGwe6Jof1OQsZNdb0TUFbO+YfCbOtP7WAXSOYF7JXbA-7Dg-PfdXgovaofgyYGgJQ9AIQjTcvYvLmGAGEbGTWdAeyZgGMIAA)

The typescript in the link you gave looks good to me, I wonder if there's a way to get the types from Plyr so that we don't need to constantly update our own in parallel. *(This may be wishful thinking though)*

**Comment by tomasvn** [comment]
Install plyr types as peerDep? So plyr options could be imported?

**Comment by gingerchew** [comment]
I couldn't find a `@types` package for plyr or a `.d.ts` file. So we may be in between a rock and a hard place.

**Comment by tomasvn** [comment]
I did find them, but it seems that is has different options https://github.com/sampotts/plyr/blob/master/src/js/plyr.d.ts

**Comment by gingerchew** [comment]
You can actually pass the plyr config to glightbox,the ones documented here are just the ones you're most likely to use.

**Comment by tomasvn** [comment]
@rokozeit There is an opened PR that is still in progress

**Comment by gingerchew** [comment]
@rokozeit https://github.com/biati-digital/glightbox/pull/411 you can find our WIP pr here. what is there should cover you or at least give you a reasonable head start
