### ISSUE TITLE
scrolls to top of the page, on mobile

### ISSUE THREAD

**Issue by tom100303** [biati-digital/glightbox#408]
**Are you able to reproduce the bug in the demo site**
No.

Hello.

On mobile.

When I click on the thumbnail, modal window opens, but when I close modal window with "x" , the page is scrolled to the top.

I noticed, that when I click on thumbnail, page scrolls to the top before modal opens.

How can I solve this problem?

**Comment by ian-cox** [comment]
Having the same issue and am not sure what is causing it.
Let me know if you ended up figuring this out.
