### ISSUE TITLE
Custom jquery code not working inside the popup box

### ISSUE THREAD

**Issue by r-interactive** [biati-digital/glightbox#437]
Hello,

I have a list <ul> inside the popup box, and I have some custom js code added. I am using the inline element (text content inside the popup box). The code will loop through all the list items and add the classname 'active' to one of the item every 4 seconds. 
The first item has the 'active' classname, after 4 seconds, the classname gets removed from the first one, and the 'active' classname gets added to the 2nd list item, etc...

The code below is not working when the list is inside the popup box. However, the code is working if the list is outside the popup box.
Why isn't my jquery code isn't working when I target the content inside the popup box?

The HTML list inside the popup:

```
<ul class="test-list-1">
<li class="test active">List item 1</li>
<li class="test">List item 2</li>
<li class="test">List item 3</li>
</ul>
```

my jquery code:

```
(function($){

  function cycle(){
     var items = $('.test-list-1 li');
     var i = 0;
     setInterval(function () {

          items.removeClass('active').eq(i).addClass('active');
          i++;
         
           if (i >= items.length ) {
               i = 0;
           }

     }, 4000);

  }

  cycle();
})(jQuery);
```

**Comment by gingerchew** [comment]
Duplicate: https://github.com/biati-digital/glightbox/issues/436

@r-interactive If you create a discussion someone may be able to explain in more detail what is wrong. This is not an issue with Glightbox.

**Comment by r-interactive** [comment]
@gingerchew - alright! thanks!
