### ISSUE TITLE
Is there a way to play a youtube video from a specific time?

### ISSUE THREAD

**Issue by kouroubel** [biati-digital/glightbox#439]
Is there a way to open a video from youtube at a specific time? My code now looks like this 

`<a href="https://youtu.be/YNNgHkPbODg?t=147" class="glightbox btn-watch-video d-flex align-items-center" data-startAt="100"><i class="bi bi-play-circle"></i><span>Στο πεδίο</span></a>`

but the video starts from the beginning instead of at 147s.

**Comment by gingerchew** [comment]
First, you gotta format all your `data-*` attributes in kebabcase. Otherwise you’ll run into issues.

Second, no there is not a way. You can do it pretty easily with the events provided. There is a player variable passed for some of the events.

**Comment by gingerchew** [comment]
If you need help beyond that, you can make a discussion and someone may be able to help you there. Otherwise, going to close this issue.
