### ISSUE TITLE
Add support for async content

### ISSUE THREAD

**Issue by massimo-cassandro** [biati-digital/glightbox#442]
It seems that glightbox is only active for loaded content, it would be helpful if it could be configured to work on asynchronous loaded content as well (using event delegation?).

**Comment by davidblanco-m** [comment]
x2

**Comment by gingerchew** [comment]
@massimo-cassandro can you give an example of what you mean? async content is a bit too vague for me to really understand what you're looking for.

**Comment by massimo-cassandro** [comment]
If you have content loaded by Ajax and this content has some glightbox elements, you need to initialize glightbox every time the content changes.
 
It would be very helpful if there was a way to delegate glightbox to the container, making it always active whatever content is loaded.

**Comment by gingerchew** [comment]
I see, there's an example of how to do that in the [documentation here](https://github.com/biati-digital/glightbox#methods) you'll need to scroll to the end of the code example. Gist of it is when the ajax call is complete, insert the slides using `insertSlide`

**Comment by massimo-cassandro** [comment]
OK, I missed it
Thanks
