### ISSUE TITLE
Remove .gslide-description from slideHTML

### ISSUE THREAD

**Issue by OlivierBlomme** [biati-digital/glightbox#456]
I am trying to hide the slide description by omitting .gslide-description html in slideHTML.

This is my code:

        let customSlideHTML = `<div class="gslide">
        <div class="gslide-inner-content">
            <div class="ginner-container">
                <div class="gslide-media">
                </div>

                <div class="gslide-description">  //Remove this block
                    <div class="gdesc-inner" style="display:none;">
                        <h4 class="gslide-title"></h4>
                        <div class="gslide-desc"></div>
                    </div>
                </div>  //End remove this block

            </div>
        </div>
    </div>`;

        const lightbox = GLightbox({
          slideHTML: customSlideHTML,
        });

But it errors with: Uncaught TypeError: Cannot read properties of null (reading 'parentNode') and doesn't load the slide.

Expected behaviour would be showing the slide without a title/description.

I am using version 3.2.0

**Comment by gingerchew** [comment]
Does hiding it with a `display: none;` not work? Custom HTML is an advanced feature and should be a last resort.

**Comment by OlivierBlomme** [comment]
display: none; does work. I couldn't find any option that disables the title/descripion, so i figured using custom HTML would be the recommended way. Thank you for letting me know it isn't.
