### ISSUE TITLE
Preload false not working

### ISSUE THREAD

**Issue by robozb** [biati-digital/glightbox#458]
The pop-up windows do not appear until the videos are loaded, even though the preload is turned off.

**Comment by biati-digital** [comment]
The preload option it's not related to that. That option is used to preload the content of slides, for example when you open a slide it will also preload the next and prev slides so when the user clicks the next/prev arrows the content it's already loaded. There's currently no option to disable what you mention.

**Comment by robozb** [comment]
So, does the preload='none' attribute have no effect on videos on the loaded pages? Does GLightBox always load the videos first before they are displayed?

**Comment by biati-digital** [comment]
GLightbox uses the library Plyr to handle everything related to videos and it simply waits until Plyr it's ready to play the video.

I'm closing this as it's not an issue, you can use the Discussion tab to ask about functionality or help to achieve what you want to do.
