### ISSUE TITLE
Duplicate instances on one page 

### ISSUE THREAD

**Issue by JamesAllgood** [biati-digital/glightbox#467]
**Describe the bug**
The gallery code is show multiple times on certain pages on my website. 

When this happens the last gallery works but the others just show the progress bar 

**To Reproduce**

1. Go to https://themeparkguide.co.uk/archive/Creek-Freak-Massacre
2. Scroll to the first gallery and click on a photo and it works
3. Scroll down to the next gallery and try click on a photo and it opens up the file in a window not using the Lightbox  

**Expected behavior**
It should show the gallery 

**Desktop:**
 - OS: MacOS and Windows 
 - Browser Safari and Firefox
 - Version Latest

**Comment by JamesAllgood** [comment]
Still having an issue where the first gallery works fine then the second and third just opens up photos like a file not using the light box

**Comment by gingerchew** [comment]
Can you create an isolated test case? Putting it into a codepen helps us immensely.

**Comment by JamesAllgood** [comment]
my issue turned out to be some parts of my code couldn't see the script. issue was on my side :)
