### ISSUE TITLE
Tag <a> doesn't display on description section

### ISSUE THREAD

**Issue by VictorPainter** [biati-digital/glightbox#48]
Hello! It's an actually cool plugin. But today I see some problem. When I try tag <a> at the description section it doesn't display. Moreover, the tag <p> with description doesn't display too. Please help me to fix this issue.

**Comment by mcstudios** [comment]
Hi @VictorPainter are you adding the a tag inside the data attribute? (data-description)?

**Comment by VictorPainter** [comment]
> Hi @VictorPainter are you adding the a tag inside the data attribute? (data-description)?

Hi! Here is my code.
`
<a href="<?php echo $url; ?>" class="glightbox2 button-prt" data-glightbox="title: <?php the_title(); ?>; descPosition: right;">View Details          
            <div class="glightbox-desc">
                  <?php the_content(); ?>
             
                  <a href="#">Visit Project</a>
            </div>
</a>`

**Comment by VictorPainter** [comment]
Hello! Can anybody help me to solve this problem? I'll never know why the link is cut from the description. I can use any tag there except <a>.

**Comment by biati-digital** [comment]
Hi, please download the latest version, make sure the div with the description is outside your a tag, checkout the readme or the index.html for more information. if you have any other problem feel free to open a new issue.
