### ISSUE TITLE
First image of config object won't appear when >= 769px but gallery acts normal if <769px

### ISSUE THREAD

**Issue by larsactionhero** [biati-digital/glightbox#483]
**Describe the bug**
I've run into this while using a link trigger to open a glightbox.
If screen size is >= 769px: first image of elements object won't show up.
If screen size is < 769px: gallery works as expected.

But when 1st item in config object does **not** contain the following entries...
```
'type': 'image',
'title': 'Another title',
'alt': 'image alt text'
```
...gallery works as expected, regardless of screen size (see example #2 in codepen)

**Are you able to reproduce the bug in the demo site**
No.

**To Reproduce**
1) this following codepen example uses the basic setup from the docs. 
in this example, the gallery elements are defined by the 'elements' object.
[https://codepen.io/larsactionhero/pen/MWRXpYb](https://codepen.io/larsactionhero/pen/MWRXpYb)

2. resize screen to >= 769px. first image won't show up.
3. resize screen to < 769px. first image will show up and gallery works as expected.

**Expected behavior**
It should open the 1st image right away.

**Post the code you are using**
[https://codepen.io/larsactionhero/pen/MWRXpYb](https://codepen.io/larsactionhero/pen/MWRXpYb)

**Screenshots**
Additional screenshot of my console error (taken from my current project where it appeared)
<img width="553" alt="Bildschirmfoto 2024-04-11 um 18 05 33" src="https://github.com/biati-digital/glightbox/assets/11157745/41bd5d7f-49f0-4402-b190-5eb70695e842">

**Desktop:**
 - OS: Mac OS
 - Browser Firefox 124.0.2, Chrome 123.0.6312.107, Brave 1.64.116

**Comment by gingerchew** [comment]
That is odd. If you use the last release from Github (3.2.0) the issue goes away.

**Comment by larsactionhero** [comment]
> That is odd. If you use the last release from Github (3.2.0) the issue goes away.

Thanks for your reply. 
But shown codepen example already uses v3.3.0.
