### ISSUE TITLE
`data-type="external"` is not documented

### ISSUE THREAD

**Issue by mrleblanc101** [biati-digital/glightbox#489]
I wanted to disable Plyr for my local `<video>`.
I found `data-type="external"` in #126

**Comment by gingerchew** [comment]
Hey there @mrleblanc101,

We're getting v4 ready so we likely won't be adding to the existing documentation. You can find it in [the code here](https://github.com/biati-digital/glightbox/blob/master/src/js/core/slide.js#L107-L110). It just tells GLightbox to use the [iframe slide type](https://github.com/biati-digital/glightbox/blob/master/src/js/slides/iframe.js).

**Comment by mrleblanc101** [comment]
I realized that external would not solve my problem because it put my video inside an iframe, I need to the video at the root of the slide, but I don't want to use Plyr. I hope this is solved in v4 🤞
