### ISSUE TITLE
Demo: Open block does not scroll.

### ISSUE THREAD

**Issue by dios-oleg** [biati-digital/glightbox#51]
**Describe the bug**
Demo "Images with Description".
Open block does not scroll.

**Are you able to reproduce the bug in the demo site**
Yes

**To Reproduce**
1. Go to https://mcstudios.github.io/glightbox/#examples Images with Description
2. Click on First image

**Expected behavior**
Scroll open block with offset image and text.

**Screenshots**
https://yadi.sk/i/ZnYiNUkCE2XNHg

**Desktop:**
 - Device: Notebook 15" 1366x768
 - OS: Ubuntu 18.04
 - Browser Firefox 66

**Comment by biati-digital** [comment]
Hi, thank you for letting me know about this error, i'll take a look.

**Comment by biati-digital** [comment]
Hi, please download the latest version, now slides are resized correctly when the screen height is lower than the slide height.
