### ISSUE TITLE
Vidstack

### ISSUE THREAD

**Issue by shmaltz** [biati-digital/glightbox#523]
Any plans to integrate [VidStack](https://github.com/vidstack/player), the successor to plyr?

**Comment by gingerchew** [comment]
Yes! But it probably won't be until the next version of GLightbox

**Comment by shmaltz** [comment]
Awesome! Integrating GLightbox into a project right now. Is there an ETA for the next version? And will there be major breaking changes?

**Comment by gingerchew** [comment]
The v4 beta branch is [available on GitHub here](https://github.com/biati-digital/glightbox/tree/v4-beta) but I wouldn't recommend it for production yet. I would expect breaking changes between v3 and v4, it is pretty close to a complete rewrite IMO.

The documentation will need updating so feel free to mess around with it, [but if you have questions please start a discussion, we're not ready to start handling issues surrounding v4.](https://github.com/biati-digital/glightbox/discussions/new/choose)
