### ISSUE TITLE
[FR] ability to set rel="" to have seperate galleries on one page

### ISSUE THREAD

**Issue by mediabeastnz** [biati-digital/glightbox#54]
It would be awesome to have the ability to some how group a bunch of gallery items together so you can have multiple galleries on one page.

Similar to how fancybox does (use to do?) it e.g. rel="my-gallery-1".

**Comment by biati-digital** [comment]
Hi, you can already do this using a data attribute, example: data-gallery="gallery-1"

**Comment by mediabeastnz** [comment]
Ahh perfect, thanks!
