### ISSUE TITLE
Allow exclusion of specific slide options

### ISSUE THREAD

**Issue by basterrika** [biati-digital/glightbox#542]
### Description
Currently, GLightbox imports all slide types by default, including video and iframe slides in `core/slide.js`.
```js
import ZoomImages from './zoom.js';
import DragSlides from './drag.js';
import slideImage from '../slides/image.js';
import slideVideo from '../slides/video.js';
import slideInline from '../slides/inline.js';
import slideIframe from '../slides/iframe.js';
import SlideConfigParser from './slide-parser.js';
import { addEvent, addClass, removeClass, hasClass, closest, isMobile, isFunction, isNode, createHTML } from '../utils/helpers.js';
```
While this approach ensures full functionality, it also includes features that may not be necessary for all projects. For example, in my project, I only need images and do not need video or iframe support. Loading unnecessary modules can increase package size and affect performance. Especially the video one that includes Plyr.

### Proposed Solution
Introduce an option within GLightbox initialization that allows the user to specify which types of slides to include. This could be accomplished by providing an inclusion matrix in the initialization options. For example:
```js
const lightbox = GLightbox({
  // Other configurations...
  includeSlides: ['image', 'iframe'], // Only include image and iframe slides
});
```

**Comment by gingerchew** [comment]
Something similar to this is implemented in v4. I don't remember off the top of my head, but its something like this:


```js
// pseudo code
import GLightbox from 'glightbox';
import { ImageSlide } from 'glightbox/slides';

const lightbox = GLightbox({
	plugins: [ ImageSlide({ ...config }) ]
});
```
