### ISSUE TITLE
2.0.2 scale portrait images bigger than viewport

### ISSUE THREAD

**Issue by carstengrimm** [biati-digital/glightbox#59]
after upgrading to 2.0.2. my portrait oriented images are cut off from the viewport if the text size is on 100%. As shown in the image below it (problably) just scales the width to be 100% but ignores the fact that the height is too big for the viewport.

![image](https://user-images.githubusercontent.com/5014509/64019526-aabe2400-cb2f-11e9-854d-39ea2fab6885.png)

this seems to be happening when setting a description

**Comment by biati-digital** [comment]
Hi, please download the latest version, now images with description are resized correctly when the screen height is lower than the slide height.
