### ISSUE TITLE
2.0.2 does not load type video - youtube

### ISSUE THREAD

**Issue by carstengrimm** [biati-digital/glightbox#60]
tried embedding youtube (non cookie as well as normal) with the newest update and it seems like it's not going any further then the loading screen. it's appending the plyr class and whatsoever, however it seems like all those html ways of doing things do not seem to work for me...

```
                        <a href="https://www.youtube-nocookie.com/embed/<?= $video->key() ?>" class="ytlightbox" data-type="video"><img data-src="https://img.youtube.com/vi/<?= $video->key() ?>/hqdefault.jpg" class="lazyload blur-up" alt="<?= $video->title() ?>">
                            <div class="play">
                                <i class="fab fa-4x fa-youtube hvr-bounce-in"></i>
                                <h3>
                                    <?= $video->title() ?>
                                </h3>
                            </div>
                        </a>

<script>
document.addEventListener('DOMContentLoaded', function() {
    var lightboxDescription = GLightbox({
    selector: 'ytlightbox'
    });
});
</script>
```

**Comment by biati-digital** [comment]
Hi, thanks for letting me know. 

That error is not a problem with the update itself, GLightbox was not able to detect a youtube video with a URL like www.youtube-nocookie.com/embed/.... and it was inserted as an iframe.

Fixed in the latest version.

**Comment by carstengrimm** [comment]
now it's working. thanks
