### ISSUE TITLE
descPosition not working as javascript option

### ISSUE THREAD

**Issue by poldixd** [biati-digital/glightbox#62]
**Describe the bug**
I've created a button in Vue.JS. If the use clicks on the button, images where load via xhr and the glightbox open the images. When I set `descPosition` to any value, the position is always bottom.

Mybe this bug is related to #32.

Here is a simple demo with plain javascript and no xhr:
```
document.querySelector('#button').addEventListener('click', function (event) {
	var lightbox = GLightbox({
		descPosition: 'top',
	})
	lightbox.setElements([
		{
			href: 'https://dummyimage.com/600x400/000/fff',
			description: 'test',
			type: 'image'
		}
	])
	lightbox.open()
	
	alert('Position: ' + lightbox.settings.descPosition)
})
```
Here is a screenshot of the DOM:
![image](https://user-images.githubusercontent.com/695449/64168117-229b8f80-ce4b-11e9-92f0-91d3a5b8bac6.png)

And here is a screenshot of `console.log(lightbox)`

![image](https://user-images.githubusercontent.com/695449/64168237-5aa2d280-ce4b-11e9-87fe-67fcf8a1a802.png)

**Are you able to reproduce the bug in the demo site**
No, but in jsfiddle: https://jsfiddle.net/tungon/gsox4rL8/

**To Reproduce**
https://jsfiddle.net/tungon/gsox4rL8/

**Desktop:**
 - OS: Windows
 - Browser Chrome
 - Version Version 76.0.3809.132 (Offizieller Build) (64-Bit)

**Comment by biati-digital** [comment]
Thank you for the jsfiddle, already pushed a fix for this error, please download again and let me know if it's working correctly for you.

**Comment by poldixd** [comment]
Hey @biati-digital I'm sorry for the late answer. I forgot this issue. Now everything works! Thanks.

**Comment by jeykodev** [comment]
@biati-digital, @biati-digital unfortunately it is not working again. Check the fiddle from the first post (which is using the latest version).

**Comment by gingerchew** [comment]
Hey there @jeykodev 

This appears to be a quirk with how setElements works, if you add the `descPosition` to the object you're using in `setElements` it should place it correctly.
