### ISSUE TITLE
Local video in fullscreen does not scale to screen size

### ISSUE THREAD

**Issue by arning** [biati-digital/glightbox#63]
**Describe the bug**
When using a local video file with plyr.js, after clicking the fullscreen button the video does not scale to fullscreen, while the viewer is in fullscreen.

**Are you able to reproduce the bug in the demo site**
Yes

**To Reproduce**
1. Go to demo site -> Videos Gallery
2. Click on 3rd picture
3. In the viewern click the fullscreen button

**Expected behavior**
Video scale to fullscreen

**Desktop:**
 - OS: Windows 10 
 - Chrome/Firefox
 - latest

**Comment by biati-digital** [comment]
Pushed a fix for this.

**Comment by arning** [comment]
Great! Thanx
