### ISSUE TITLE
If no data-gallery attribute added, maybe don`t add slide to gallery?

### ISSUE THREAD

**Issue by gitrequests** [biati-digital/glightbox#64]
Or add some option to disable auto gallery create. Many images on a page is not always the gallery.

**Comment by biati-digital** [comment]
Hi @gitrequests this is not something i'm planning to do because of several reasons.

The idea of data-gallery attribute is to create multiple galleries using the same GLightbox instance, if attibute gallery is not added the GLightbox will use the elements with the same class.

It's easier to use the API to achieve what you want instead of modifying the code and add more options, etc.

```javascript
const lightbox = GLightbox();
youritem.addEventListener("click", () => {
    lightbox.setElements([{yoursinglegalleryitem}]);
    lightbox.open();
});
```

This is an example code, adjust to fit your needs.

**Comment by marcamos** [comment]
I found myself in the same situation: many **single** videos on a page, and I didn't want them to automatically turn into a gallery; just a one-at-a-time open/close experience. If it helps anybody else in the future, I used the small code-example above for my own fix, which became:

```js
const lightbox = GLightbox()
const allLightboxTriggers = document.querySelectorAll('.lightbox-trigger')
if (allLightboxTriggers) {
  allLightboxTriggers.forEach(function(trigger) {
    trigger.addEventListener('click', function(e) {
      e.preventDefault()
      let targetHref = this.getAttribute('href')
      lightbox.setElements([{'href': targetHref}])
      lightbox.open()
    })
  })
}
```

**Comment by biati-digital** [comment]
Hi @marcamos thank you for sharing your solution, i'm still firm on the current functionality so i'm not planning to change it, instead i'm planning to add a new option to achieve this. it will be added in v4. in the meantime your solution will do the work.

**Comment by marcamos** [comment]
Happy to share, thanks for the great work!

**Comment by hasenov** [comment]
Hi, I had same issue, what I did is really simple but it works. All you need to do is add custom skin, disable dragging and all the navigations.
`const lightboxModal = GLightbox({
		selector: ".glightbox-single",
		skin: "modal-single",
		draggable: false,
		keyboardNavigation: false,
		touchNavigation: false,
	});`

**Comment by mrleblanc101** [comment]
I also find it very odd that it default to gallery
