### ISSUE TITLE
Awesome script!

### ISSUE THREAD

**Issue by inglesuniversal** [biati-digital/glightbox#65]
Can it be possible for the iframe to expand 100% w and 100% h for html5 videos as well as youtube videos? So that videos cover the entire screen (web and mobile) and on (portrait or landscape mode)

Thanks

**Comment by biati-digital** [comment]
I'm glad you like the script :) about your question, yes it's possible but it will require some changes to the code,  as soon as I've some free time I'll take a look to implement this.

**Comment by inglesuniversal** [comment]
Hi, I see a new update on your script. Were you able to implement the 100% h & w iframe feature?

thanks

**Comment by biati-digital** [comment]
Hi @inglesuniversal 

I did some tests but still requires some work, [View screenshot](https://ibb.co/YbCcDSx) for what i can see videos are the type of slides that will require more work and tests as resizing cuts part of the videos. As soon as this is completely functional I'll let you know.

**Comment by biati-digital** [comment]
In the latest version 2.0.6 you can set dimensions using any unit you want for example:

videosWidth: '100vw'
or
videosWidth: '100%'
etc.

The same for inline and iframes:

width: '90%',
height: '506px',

**Please note the selector was also updated to allow data attributes and more, so you need to update the selector in your code** More information in the readme.
