### ISSUE TITLE
scroll/vertical drag to close

### ISSUE THREAD

**Issue by oozrafa** [biati-digital/glightbox#67]
Would it be possible to add the feature that either when scrolling up\down using the mouse wheel or draging up/down (the whole screen, not just the image) on a mobile device will cause the lightbox to close? Similar functionality can be found on Medium's website.

Also, on mobile, is it possible to lock the drag axis to x and/or y without allowing diagonal dragging as it is not very comfortable to look at and feels weird on the screen 😜

Thanks!

Btw, AMAZING library!

**Comment by biati-digital** [comment]
I'm glad you like the script. Can you point me to an example on Medium? 

There's no option to lock the drag axis for mobile, I'll consider it for the next update.

**Comment by biati-digital** [comment]
Closing this one because never received a response, feel free to open new issues if you have any questions.
