### ISSUE TITLE
SVG icons issue - not appearing

### ISSUE THREAD

**Issue by mediabeastnz** [biati-digital/glightbox#71]
**Describe the bug**
SVG icons not appearing, seem to have no dimensions.

**Are you able to reproduce the bug in the demo site**
No.

**To Reproduce**
Install 2.0.4, import styles.

**Browser:**
Firefox 70

**Comment by biati-digital** [comment]
Can you provide a live example?

**Comment by biati-digital** [comment]
if you're still interested on this issue feel free to comment :)
