### ISSUE TITLE
Videos will not load on first open

### ISSUE THREAD

**Issue by frankie-tech** [biati-digital/glightbox#72]
**Describe bug**
When a video slide is opened, the video does not load citing “cannot read property ‘split’ of undefined.”

When navigating away from initial slide or opening a different slide and navigating to the video slide, the video loads normally.

Investigating, this was related to a setting in the plyr config for the ratio, I added the ratio “16:9”, but had the same issue. 

**Are you able to reproduce the bug in the demo site**
No.

**To Reproduce**
1. Go to 'Excelerondesigns.com/~swspinea/'
2. Click on ‘ pictures in the “successful relief” section that have play buttons on them'
3. Light box should open, but no video should play.

**Expected behavior**
Player and light box should open with the video then auto playing.

**Desktop:**
 - OS: MacOS
 - Browser: Chrome
 - Version: 77.0.3

**Smartphone:**
 - Device: iPhone 8 Plus
 - OS: iOS 13.1
 - Browser: Safari
 - Version: 13.1

**Comment by biati-digital** [comment]
I see the following error.

 undefined is not an object 'this.settings.plyr.ratio.split ...

Your error is for the ratio setting, you are either not adding it correctly or it does not exist at all, please check the source code to see how the setting should be added.

**Comment by frankie-tech** [comment]
Yep, that was it. Misread the docs on plyr github. Thanks for helping out!
