### ISSUE TITLE
Prevent to open lightbox when user is dragging element with `-webkit-user-drag: none;`

### ISSUE THREAD

**Issue by kieusonlam** [biati-digital/glightbox#75]
**Please describe the feature you want to be implemented.**

I don't think this is a bug so I create a Feature Request. As what title said, prevent to open lightbox when user drag the `a` that set `-webkit-user-drag: none;`

**Explain why the feature is useful**

I have a drag scroll vericle gallery with glightbox implemented. The `a` tag have been set `-webkit-user-drag` to `none`. User explore the content by dragging element to right or left, and then clicking on the media that they want to open the lightbox.

The current behavior when user dragging on the image to left or right will open the lightbox when `mouseup`. It's happen on both PC and mobile.

**Have you seen it somewhere else?**

My current gallery working on is pretty much the same functions as the gallery from this site.
https://www.flexaworld.com/en/product/80-31102-95/single-bed

**Additional context**
![image](https://user-images.githubusercontent.com/13093313/66896576-4a237180-f01f-11e9-8ccd-b88793f95b47.png)

**Comment by biati-digital** [comment]
Hi, sorry for the late reply, I just did a quick test adding -webkit-user-drag: none; to the first a tag and dragged it and the Lightbox was not opened, I had to click it and it opened normally.

Can you please provide a working demo?

**Comment by kieusonlam** [comment]
Thanks for reply @biati-digital , after dragging, keep your mouse stablize and then release the mouse, you will get a click event. I think it's happen quite offen drag scroll element. https://greensock.com/forums/topic/8907-draggable-click-triggered-on-drag/

Flexa got the same problem: https://www.flexaworld.com/en/product/80-31102-95/single-bed

It's not really an issue for this package, I'll close this issue for now. But it would be great if you can do something with it.
