### ISSUE TITLE
Loop should work in both directions

### ISSUE THREAD

**Issue by DevelGitH** [biati-digital/glightbox#78]
**Please describe the feature you want to be implemented.**
Currently there's only an option to loop from the end to the beginning but not in the reverse direction (navigation is disabled).
My suggestion would be to rename the option 'loopAtEnd' to 'loop', because I think in the most of cases an infinite gallery in both directions is necessary.

**Comment by biati-digital** [comment]
Makes sense, I'll work on this as soon as I have some free time.

**Comment by DevelGitH** [comment]
Perfekt thanks :) By the way a good plugin that you have made. One of the best one that I have found that is written in plain javascript :)

**Comment by biati-digital** [comment]
Added option loop in the latest version 2.0.5 👍

**Comment by DevelGitH** [comment]
Awesome, thanks :) I'll check it later.
