### ISSUE TITLE
Width and height settings doesn't work on iframe

### ISSUE THREAD

**Issue by o-eborn** [biati-digital/glightbox#80]
Hi! I think your script looks really great. It clean and smooth and seem simple to use.

However, i need to be able to use it with an iframe and i just cannot get the height value to work.

**Describe the bug**
The hieght and width values are not working properly.

**Are you able to reproduce the bug in the demo site**
Yes

**To Reproduce**
1. Go to 'http://develop.eborninteractive.se/lightbox-test/'
2. Click on 'Iframe content'

**Expected behavior**
I have set the height to 800px by using the data-height="800px" in the a-tag for iframe-content-link but as you can see, the height is much less.

**Desktop:**
 - OS: MacOS
 - Browser: Chrome
 - Version 78.0.3904.87

Thanks
Ola Eborn

**Comment by biati-digital** [comment]
Width and height should be passed as data-glightbox="**width: 900; height: 700;**" remove the px
