### ISSUE TITLE
Video Question: Linking Plyr locally in glightbox

### ISSUE THREAD

**Issue by jeanmeyer7** [biati-digital/glightbox#81]
glightbox is a awesome project. Thanks to all!

The demo included in the master works well with linking to the CDN of Plyr (plyr: js and css). Plyr is also configured to fetch plyr.svg from the CDN.

I would like to host Plyr locally. How do I include plyr.js, plyr.css, plyr.svg locally? And SVG?
Shall I put the information in the header section of my html document in 
<link rel="stylesheet" href="dist/css/glightbox.css"><br>
<script src="dist/js/glightbox.min.js"></script><br>
<script type="text/javascript"><br>
const lightbox = GLightbox({ <br>
plyr: { /relative path to /plyr.js and plyr.css  },<br>
svg: {  here SVG code for glightbox and plyr?  }<br>
 });<br>
</script><br>
Thanks in advance!

**Comment by biati-digital** [comment]
Hi @jeanmeyer7 your config should look like this:

```
plyr: {
    css: 'pathto/plyr.css',
    js: 'pathto/plyr.js',
    config: {
        iconUrl: 'pathto/plyr.svg',
        anyotherconfiglike...
        youtube: {
            noCookie: true,
            rel: 0,
            showinfo: 0,
            iv_load_policy: 3
        },
        vimeo: {
            byline: false,
            portrait: false,
            title: false,
            transparent: false
        }
    }
}
```

Here you can see the options of Plyr. [view options](https://github.com/sampotts/plyr/blob/master/dist/plyr.js#L3607)
