### ISSUE TITLE
moreLength: 0 not working inside data-glightbox

### ISSUE THREAD

**Issue by srikat** [biati-digital/glightbox#82]
This doesn't seem to be working:

```
data-glightbox="description: .custom-desc1; descPosition: right; moreLength: 0"
```

When `moreLength: 0` is added, the right position class is not added in the HTML and moreText continues to appear in mobile.

**Comment by biati-digital** [comment]
moreLength is a **global option**, please take a look at the [Slide options](https://github.com/biati-digital/glightbox#slide-options) section to check the available options for individual slides.

**Comment by srikat** [comment]
Thank you.
