### ISSUE TITLE
Display video quality setting

### ISSUE THREAD

**Issue by notrealdev** [biati-digital/glightbox#84]
Hi, thank you for awesome script.
How can i display quality setting on my video?
Thanks.
![Imgur](https://i.imgur.com/23xLR1f.jpg)

**Comment by biati-digital** [comment]
Hi @notrealdev I'm glad you like the script. 

You need to check the available options for the player and pass them to GLightbox:
Check the [Player options here](https://github.com/sampotts/plyr#options) If you have more specific questions about configuring the player or extending it, please open an issue in the Plyr repository.

```javascript
const lightbox = GLightbox({
    plyr: {
        config: {
            ....Here all the options you want to pass
            muted: false,
            hideControls: true,
            youtube: {
                noCookie: true,
                rel: 0,
                showinfo: 0,
                iv_load_policy: 3
            },
            vimeo: {
                byline: false,
                portrait: false,
                title: false,
                speed: true,
                transparent: false
            }
        }
    }
});
```

**Comment by notrealdev** [comment]
Thank you ♥️
