### ISSUE TITLE
Lightbox for videos does not work on IE 11 due to Plyr.js missing polyfills

### ISSUE THREAD

**Issue by didrip** [biati-digital/glightbox#85]
**Describe the bug**

Lightbox does not work on IE 11 out of the box. polyfills are missing for some JS used by [plyr.js](https://github.com/sampotts/plyr)

Error shown is `Object doesn't support property or method 'find'`
If using a [polyfill](https://stackoverflow.com/questions/37788536/object-doesnt-support-property-or-method-find-in-ie) for `find` then other error comes up ex `Object doesn't support property or method 'includes'`.

Related to this plyr.js issue : https://github.com/sampotts/plyr/issues/890 

**Are you able to reproduce the bug in the demo site**

Yes.

**To Reproduce**

1. Go to https://biati-digital.github.io/glightbox/#examples
2. Click on a video thumbnail
...loading indicator loads forever
3. See error in Console : Object doesn't support property or method 'find'

**Expected behavior**

**Screenshots**

**Desktop:**
 - OS : Windows 10
 - Browser : Internet Explorer
 - Version : 11

**Comment by didrip** [comment]
plyr is included via `https://cdn.plyr.io/3.5.6/plyr.js` in [glightbox.js](https://github.com/biati-digital/glightbox/blob/93a013ef356ca252f753b03a7d9edc3e6fa1fce8/dist/js/glightbox.js#L630) but the polyfilled version 

>  There's 2 versions; one with and one without polyfills.
> <script src="https://cdn.plyr.io/3.5.6/plyr.js"></script>
> <script src="https://cdn.plyr.io/3.5.6/plyr.polyfilled.js"></script>

I understand that it might better to manage polyfills externally but it should be written somewhere in the docs that we need to add them for IE support if using glightbox for videos.

**Comment by biati-digital** [comment]
Hi @didrip  I'll update the documentation to let users know about this 😃

**Comment by biati-digital** [comment]
The readme was updated.
