### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by nathanael3d** [biati-digital/glightbox#89]
Hey there

I've been looking for a script to replace Shadowbox, which does not play videos anymore.
Glightbox seems to be exactly what I need (on the demos) but I can't manage to make it work. I would like to display a lightbox gallery containing pictures and videos (local).

The documentation gives way too many examples, I cannot find what is relevant to my case. The few lines to use a gallery uses a class "glightbox3", what is that?? What should I put in my header (I have a blog on blogger where I can modify index.html) and in the body of my page?

Additionnaly, I'm looking for these two options:
- Local videos should be looping (they are walk cycles of just a few frames, so they should loop to give the viewer the time to watch it)
- Local videos should be displayed with a title, to add information about the video (software used, date, etc)

I hope you can give me a hand, because this is driving me crazy. I'd be glad to buy you a beer or coffee :)

Thx and best
Alexandre

**Comment by nathanael3d** [comment]
**This is in my page HEADER:**

`
<link href='https://cdn.jsdelivr.net/npm/glightbox/dist/css/glightbox.min.css' rel='stylesheet'/>
<script src='https://cdn.jsdelivr.net/gh/mcstudios/glightbox/dist/js/glightbox.min.js'/>

<script type="text/javascript">
const glightbox1 = GLightbox({
    touchNavigation: true,
    loop: true,
    autoplayVideos: true,
    onOpen: () => {
        console.log('Lightbox opened')
    },
    beforeSlideLoad: (slide, data) => {
        // Need to execute a script in the slide?
        // You can do that here...
    }
});
</script>
`

**And this is in my page BODY:**
`
<a href="https://media.nathanael3D.com/gallery/anim_game/fighter.png" class="glightbox1" data-gallery="gallery1">
    <img src="https://media.nathanael3D.com/gallery/anim_game/fighter.png" alt="image">
</a>
<a href="http://media.nathanael3D.com/gallery/anim_game/orc/orc_attack.mp4" class="glightbox1" data-gallery="gallery1">
    <img src="https://media.nathanael3D.com/gallery/anim_game/fighter.png" alt="image">
</a>
`

**Comment by nathanael3d** [comment]
The page is here:
http://www.nathanael3d.com/p/gallery.html

**Comment by biati-digital** [comment]
You need to specify the selector you are using, for example the code in your body has a class of **glightbox1** so you should specify that class when you initialize GLightbox:

```javascript
const lightbox = GLightbox({
    selector:  'glightbox1',
    touchNavigation: true,
    loop: true,
    autoplayVideos: true,
    onOpen: () => {
        console.log('Lightbox opened')
    },
    beforeSlideLoad: (slide, data) => {
        // Need to execute a script in the slide?
        // You can do that here...
    }
});
```

I'll update the documentation to make this more clear.

**Comment by nathanael3d** [comment]
Hey, thanks.

I see, but I'm not sure why it is still not working. I tried this:

**Header:**
`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/glightbox/dist/css/glightbox.min.css">
<script src="https://cdn.jsdelivr.net/gh/mcstudios/glightbox/dist/js/glightbox.min.js"></script>

<script type="text/javascript">
const lightbox = GLightbox({
    selector:  'glightbox1',
    touchNavigation: true,
    loop: true,
    autoplayVideos: true,
    onOpen: () => {
        console.log('Lightbox opened')
    },
    beforeSlideLoad: (slide, data) => {
        // Need to execute a script in the slide?
        // You can do that here...
    }
});
</script>`


**Body:**
`<a href="https://vimeo.com/115041822" class="glightbox3" data-gallery="gallery1">
    <img src="https://media.nathanael3D.com/gallery/anim_game/fighter.png" alt="image">
</a>
<a href="https://www.youtube-nocookie.com/embed/Ga6RYejo6Hk" class="glightbox3" data-gallery="gallery1">
    <img src="https://media.nathanael3D.com/gallery/anim_game/fighter.png" alt="image">
</a>`

Btw, how do you make the code show up nicely in my answers, like you did? I'm new on GitHub ^^
Cheers
Alex

**Comment by biati-digital** [comment]
Move this code to the footer

```html
<script type="text/javascript">
const lightbox = GLightbox({
    selector:  'glightbox1',
    touchNavigation: true,
    loop: true,
    autoplayVideos: true,
    onOpen: () => {
        console.log('Lightbox opened')
    },
    beforeSlideLoad: (slide, data) => {
        // Need to execute a script in the slide?
        // You can do that here...
    }
});
</script>
```

You are initializing the script when the [dom](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction)  is not ready so basically you tell the script to get all the elements with the class of "glightbox1" but they do not exist yet.

When executing scripts make sure to always do it in the footer otherwise you need an event listener to know when the dom is ready

```javascript
document.addEventListener('DOMContentLoaded', function(event) {
    const lightbox = GLightbox({
        selector:  'glightbox1',
        touchNavigation: true,
        loop: true,
        autoplayVideos: true,
        onOpen: () => {
            console.log('Lightbox opened')
        },
        beforeSlideLoad: (slide, data) => {
            // Need to execute a script in the slide?
            // You can do that here...
        }
    });
})
```


You can learn how to add syntax highlighting in the comments [here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)

**Comment by nathanael3d** [comment]
YES! You're amazing, it's working! I even found out how to add a title to the videos :)

Definitely update the documentation, as it is not clear where the different bits of code should go. I placed the instance declaration right after the </footer> as you said and it's working now:
http://www.nathanael3d.com/p/gallery.html

Now I have one small issues to make it perfect:
- How can I configure the Plyr player to loop my local videos (i.e. each video is looping forever, I need that for walk cycles for instance). I see that I can add **plyr: {options}** like in the documentation, but I'm not sure where to put it.

Thanks for your help :)

**Comment by nathanael3d** [comment]
Little snag in your Slide Options example too:
You write **width: 900px;** to define the lightbox width, but I noticed that it's only working with **width: 900;** (no px).

**Comment by biati-digital** [comment]
The width and height params were updated in the latest version 2.0.6, please check the readme if you have doubts

**Comment by chargingsleipnir** [comment]
> You need to specify the selector you are using, for example the code in your body has a class of **glightbox1** so you should specify that class when you initialize GLightbox:
> 
> ```js
> const lightbox = GLightbox({
>     selector:  'glightbox1',
>     touchNavigation: true,
>     loop: true,
>     autoplayVideos: true,
>     onOpen: () => {
>         console.log('Lightbox opened')
>     },
>     beforeSlideLoad: (slide, data) => {
>         // Need to execute a script in the slide?
>         // You can do that here...
>     }
> });
> ```
> 
> I'll update the documentation to make this more clear.

If it's a "class" of "glightbox1" the selector needs to be '.glightbox1', not 'glightbox1'. I just spent all morning ripping my goddamn hair out trying to figure out why your answer doesn't actually work. OP is right, your original instructions are not nearly specific enough on how to get just the most basic example running. It's been an infuriating experience due to lack of specificity, particularly regarding even requiring the selector option.

**Comment by biati-digital** [comment]
@chargingsleipnir that answer was from a year ago, next time you should read the README first instead of wasting your morning, the code and options will change as the library grows so do not just copy and paste the code you find in the issues section.
