### ISSUE TITLE
JS Error video lightbox - not working

### ISSUE THREAD

**Issue by gozo1985** [biati-digital/glightbox#90]
I'm using GLightbox for my gallery. Works fine.
Now I want to add this to my videos as well. Failed due to an error:
_glightbox.js:2465 Uncaught TypeError: Cannot read property 'split' of undefined_
References Line:
`var videoRatio = this.settings.plyr.ratio.split(':');`

HTML
`<a href="https://www.youtube.com/watch?v=5NV6Rdv1a3I" class="video__lightbox__link">lightbox link</a>`

JS
`  const lightbox = GLightbox({
    selector: 'video__lightbox__link',
    plyr: {
      css: 'https://cdn.plyr.io/3.5.6/plyr.css',
      js: 'https://cdn.plyr.io/3.5.6/plyr.polyfilled.js',
      config: {
        muted: false,
        hideControls: false,
        youtube: {
          rel: 0,
          showinfo: 0,
          iv_load_policy: 3
        },
        vimeo: {
          byline: false,
          portrait: false,
          title: false,
          speed: true,
          transparent: false
        }
      }
    }
  })`

Note:
css and js api path are mandatory despite in documentation mentioned it's not. I get an error if I don't add the js line, maybe take a look into this as well. I need the polyfill version anyways (same split error with non-polyfill version anyways btw.)

Browser: Chrome

Any ideas? Something wrong with my code? It is more or less copy paste from the demo

**Comment by biati-digital** [comment]
Hi

Add the ratio to your video, if you pass your own config to plyr it will use it and ignore the included config.

```
css: 'https://cdn.plyr.io/3.5.6/plyr.css',
js: 'https://cdn.plyr.io/3.5.6/plyr.js',
ratio: '16:9',
```

I'll make some updates to this part of the code.

**Comment by gozo1985** [comment]
Thanks you for the fast response! It worked adding the ratio :)
