### ISSUE TITLE
Open at different indexes depending on element clicked

### ISSUE THREAD

**Issue by Ariane-B** [biati-digital/glightbox#92]
Hi!
This is a pretty standard use case, so I'm pretty sure this is very doable, but I haven't figured out the right way to do it yet.

I have a series of links and images defined as such:
```html
<ul class="the-gallery lightbox-gallery">
	<li class="gallery-el">
		<a href="#" class="gallery-el-link lightbox-gallery-el">
			<img src="#" alt="" class="gallery-image lazy-loaded" src="#">
		</a>
	</li>
	<li class="gallery-el">
		<a href="#" class="gallery-el-link lightbox-gallery-el">
			<img src="#" alt="" class="gallery-image lazy-loaded" src="#">
		</a>
	</li>
	<!-- (more li) -->
</ul>
```
So far it mostly works fine, with the following exception: no matter which link I click, the GLightbox starts at index 0 (the first image).

My JS works this way:

```javascript
(function() {
	let lightboxGals = document.querySelectorAll('.lightbox-gallery');

	lightboxGals.forEach( function( thisGal ) {
		let lightboxEls = thisGal.querySelectorAll('.lightbox-gallery-el');

		let popupOptions = {
			elements: [],
			autoplayVideos: true,
			keyboardNavigation: true,
			skin: 'clean nubee nubee-gallery',
			startAt: 0,
		};

		let lightboxInstance;
		let galIndex = 0;

		lightboxEls.forEach( function( thisEl ) {
			let newElement = buildLightboxElement( thisEl );

			if( newElement ) {
				thisEl.setAttribute( 'data-lightbox-gallery-index', galIndex );

				thisEl.addEventListener( 'click', function( event ) {
					let clickedIndex = event.target.dataset.lightboxGalleryIndex;
					event.preventDefault();
					lightboxInstance.settings.startAt = clickedIndex;
					lightboxInstance.open();
				} );

				popupOptions.elements.push( newElement );

				++ galIndex;
			}
		} );

		if( popupOptions.elements.length ) {
			lightboxInstance = GLightbox( popupOptions );
			// console.log( lightboxInstance );
		}
	} );
}) ();
```

As you can see at `lightboxInstance.settings.startAt = clickedIndex;`, after having saved each element's index in a data attribute, I'm trying to alter the settings on-click, before opening, to make the lightbox open where I want it to. This has no effect though.

How should I proceed to open the gallery according to the link that was clicked?

This shouldn't be relevant to my question, but just in case, my `buildLightboxElement` function just builds each element object according to their URLs. Here it is, just in case:

```javascript
function buildLightboxElement( htmlEl ) {
	let elHref = htmlEl.href || null;
	let elSource = null;
	let elType = null;
	let newElement = null;

	if( elHref ) {
		newElement = {};

		if( elHref.match(/\.(jpg|jpeg|gif|png|svg|webp|tif|tiff|bmp|apng|ico|cur|jfif|pjpeg|pjp)$/i) ) {
			elType = 'image';
		} else if( elHref.match(/\.(mp4|ogg|mov|webm|avi|mkv|ogv)$/i) ) {
			elType = 'video';
			elSource = 'local';
		} else if( elHref.match(/youtu/i) ) {
			elType = 'video';
			elSource = 'youtube'
		} else if( elHref.match(/vimeo/i) ) {
			elType = 'video';
			elSource = 'vimeo'
		} else if( elHref.match(/^#/i) ) {
			elType = 'inline';
		} else {
			elType = 'external';
		}

		newElement.href = elHref;
		newElement.type = elType;

		if( elSource ) {
			newElement.source = elSource;
		}
	}

	return newElement;
}
```

**Comment by biati-digital** [comment]
Hi, I'm not sure what you are trying to do, currently we have a lot of work so we are not able to work on GLightbox until the end of April. GLightbox will open the clicked element correctly respecting their position, take a look at the demo. As I said, we have a lot of work so we do not have time to take a look at your code or provide any kind of help until the end of April.

**Comment by Ariane-B** [comment]
Hi,

I appreciate the honesty. For now I'll switch to using a separate selector for every gallery's elements. I hope you'll have time to look into this issue later.

With the `selector` option, everything works just fine. The problem is that I'd like every gallery to use the same selector, `lightbox-gallery-el`, and not end up in the same gallery as everything else. To do that, I need to dynamically build an array of `element`s and add the instance's `.open()` method onto it on-click manually. When I do that, I cannot get the gallery to open to a specific index. (Or rather, I don't know how to do it.)

**Comment by lamplightdev** [comment]
To get the gallery to open to a specific item you can manually set the `startAt` option in the lightbox `settings`, before you open it. E.g. in a click handler:

```js
lightbox.settings.startAt = myChosenIndex;
lightbox.open()
```

**Comment by Ariane-B** [comment]
I thought I tried that and it didn't work, but I'll give it another try soon. I'll be back with an update. Thank you!

**Comment by zothynine** [comment]
If you did a normal for loop over `lightboxEls` you could just do:
```
for (let i=0; i<lightboxEls.length; i++) {
    lightboxInstance.open(i);
}
```
