### ISSUE TITLE
Cant use data-attrib as selector

### ISSUE THREAD

**Issue by Lefthandmedia** [biati-digital/glightbox#93]
**Please describe the feature you want to be implemented.**
I would like a data attribute to be used as a selector
EG. ```<a href="bigpic.jpg" data-glightbox><img src="..."></a>```

**Explain why the feature is useful**
Some CMSs put data attributs on Ahrefs instead of classes

**Have you seen it somewhere else?**
If so please provide live examples, images, videos, etc. anything that help us understand the feature request

**Comment by biati-digital** [comment]
In the latest version 2.0.6 you can use data attributes as selector for example:
 '.glightbox' or 'data-glightbox' or '*[data-glightbox]'
