### ISSUE TITLE
page "jumps" depending on hiding scrollbars

### ISSUE THREAD

**Issue by BugFixNo1** [biati-digital/glightbox#95]
Hi folks, nice work but:

the page "jumps" depending on hiding scrollbars means when i click a pic to activate the script the scrollbars of the browser will be hidden by the script (or css?) this makes a streching behavior of the page when thhe script opens and closes.

**Are you able to reproduce the bug in the demo site**
Yes

**Expected behavior**
don't hide scrollbars to have a static behavior of the origin page.

h.a.n.d.
torsten

**Comment by adderpositive** [comment]
@BugFixNo1 maybe you cant just add `overflow-x: hidden;` instead of `overflow: hidden;` to `.glightbox-open`. It can partly fix this buggy behaviour.

**Comment by biati-digital** [comment]
Should be fixed in the latest version 2.0.6
