### ISSUE TITLE
YouTube video does not load!

### ISSUE THREAD

**Issue by ethereal94** [biati-digital/glightbox#97]
YouTube video does not load!
Can I fix it somehow? Thanks!

**Comment by biati-digital** [comment]
They do load in the demo site, please check your code and read the docs

**Comment by cacacobra** [comment]
> They do load in the demo site, please check your code and read the docs

HI, i just found this plugin, and i noticed that youtube video was not working, so a went to the Examples page and there its not working either.

https://biati-digital.github.io/glightbox/#examples
