### ISSUE TITLE
Scrolling Description triggers closing the lightbox on touch devices

### ISSUE THREAD

**Issue by zothynine** [biati-digital/glightbox#99]
**Describe the bug**
When you touch-scroll a longer slide description it also triggers the "close on vertical swipe" feature.

**Are you able to reproduce the bug in the demo site**
No, but I have a screen recording.

**To Reproduce**
1. Go to a slide with a longer scrollable text on a smartphone.
2. Scroll the text by swiping it upwards.
3. See error

**Expected behavior**
Scrolling the text without closing the lightbox.

**Screenshots**
![lightbox_scroll_bug](https://user-images.githubusercontent.com/6057489/78135236-de449200-7421-11ea-99f7-e6dcd42762cb.gif)

**Smartphone:**
 - Device: smartphone or Chrome DevTool with touch emulation
 - Several devices on browserstack.com
 - Real iPhone/Andoid Phone (reportet from testers)

**Comment by biati-digital** [comment]
This should be fixed in the latest version 2.0.6
